// Code generated by ucpgen. DO NOT EDIT.
// Source: capability.json (spec release/2026-04-08@a2d8bf0)

package ucp

import (
	"encoding/json"
	"errors"
)

// CapabilityBase is generated from capability.json.
type CapabilityBase struct {
	// Entity-specific configuration. Structure defined by each entity's schema.
	Config map[string]any `json:"config,omitzero"`
	// Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
	Extends json.RawMessage `json:"extends,omitzero"`
	// Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
	ID *string `json:"id,omitzero"`
	// URL to JSON Schema defining this entity's structure and payloads.
	//
	// Not enforced yet (phase 4): format.
	Schema *string `json:"schema,omitzero"`
	// URL to human-readable specification document.
	//
	// Not enforced yet (phase 4): format.
	Spec *string `json:"spec,omitzero"`
	// Entity version in YYYY-MM-DD format.
	Version UCPVersion `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *CapabilityBase) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("CapabilityBase: null is not a valid object")
	}
	type CapabilityBaseAlias CapabilityBase
	var named CapabilityBaseAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = CapabilityBase(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "config")
	delete(all, "extends")
	delete(all, "id")
	delete(all, "schema")
	delete(all, "spec")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v CapabilityBase) MarshalJSON() ([]byte, error) {
	type CapabilityBaseAlias CapabilityBase
	named, err := json.Marshal(CapabilityBaseAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *CapabilityBase) Validate() error {
	if v.present != nil {
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}

// CapabilityBusinessSchema Capability configuration for business/merchant level. May include business-specific config overrides.
type CapabilityBusinessSchema struct {
	// Entity-specific configuration. Structure defined by each entity's schema.
	Config map[string]any `json:"config,omitzero"`
	// Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
	Extends json.RawMessage `json:"extends,omitzero"`
	// Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
	ID *string `json:"id,omitzero"`
	// URL to JSON Schema defining this entity's structure and payloads.
	//
	// Not enforced yet (phase 4): format.
	Schema *string `json:"schema,omitzero"`
	// URL to human-readable specification document.
	//
	// Not enforced yet (phase 4): format.
	Spec *string `json:"spec,omitzero"`
	// Entity version in YYYY-MM-DD format.
	Version UCPVersion `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *CapabilityBusinessSchema) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("CapabilityBusinessSchema: null is not a valid object")
	}
	type CapabilityBusinessSchemaAlias CapabilityBusinessSchema
	var named CapabilityBusinessSchemaAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = CapabilityBusinessSchema(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "config")
	delete(all, "extends")
	delete(all, "id")
	delete(all, "schema")
	delete(all, "spec")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v CapabilityBusinessSchema) MarshalJSON() ([]byte, error) {
	type CapabilityBusinessSchemaAlias CapabilityBusinessSchema
	named, err := json.Marshal(CapabilityBusinessSchemaAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *CapabilityBusinessSchema) Validate() error {
	if v.present != nil {
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}

// CapabilityPlatformSchema Full capability declaration for platform-level discovery. Includes spec/schema URLs for agent fetching.
type CapabilityPlatformSchema struct {
	// Entity-specific configuration. Structure defined by each entity's schema.
	Config map[string]any `json:"config,omitzero"`
	// Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
	Extends json.RawMessage `json:"extends,omitzero"`
	// Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
	ID *string `json:"id,omitzero"`
	// URL to JSON Schema defining this entity's structure and payloads.
	//
	// Not enforced yet (phase 4): format.
	Schema string `json:"schema"`
	// URL to human-readable specification document.
	//
	// Not enforced yet (phase 4): format.
	Spec string `json:"spec"`
	// Entity version in YYYY-MM-DD format.
	Version UCPVersion `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *CapabilityPlatformSchema) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("CapabilityPlatformSchema: null is not a valid object")
	}
	type CapabilityPlatformSchemaAlias CapabilityPlatformSchema
	var named CapabilityPlatformSchemaAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = CapabilityPlatformSchema(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 3)
	for _, name := range []string{"schema", "spec", "version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "config")
	delete(all, "extends")
	delete(all, "id")
	delete(all, "schema")
	delete(all, "spec")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v CapabilityPlatformSchema) MarshalJSON() ([]byte, error) {
	type CapabilityPlatformSchemaAlias CapabilityPlatformSchema
	named, err := json.Marshal(CapabilityPlatformSchemaAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *CapabilityPlatformSchema) Validate() error {
	if v.present != nil {
		if !v.present["schema"] {
			return errors.New("schema: required property is missing")
		}
		if !v.present["spec"] {
			return errors.New("spec: required property is missing")
		}
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}

// CapabilityResponseSchema Capability reference in responses. Only name/version required to confirm active capabilities.
type CapabilityResponseSchema struct {
	// Entity-specific configuration. Structure defined by each entity's schema.
	Config map[string]any `json:"config,omitzero"`
	// Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
	Extends json.RawMessage `json:"extends,omitzero"`
	// Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
	ID *string `json:"id,omitzero"`
	// URL to JSON Schema defining this entity's structure and payloads.
	//
	// Not enforced yet (phase 4): format.
	Schema *string `json:"schema,omitzero"`
	// URL to human-readable specification document.
	//
	// Not enforced yet (phase 4): format.
	Spec *string `json:"spec,omitzero"`
	// Entity version in YYYY-MM-DD format.
	Version UCPVersion `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *CapabilityResponseSchema) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("CapabilityResponseSchema: null is not a valid object")
	}
	type CapabilityResponseSchemaAlias CapabilityResponseSchema
	var named CapabilityResponseSchemaAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = CapabilityResponseSchema(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "config")
	delete(all, "extends")
	delete(all, "id")
	delete(all, "schema")
	delete(all, "spec")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v CapabilityResponseSchema) MarshalJSON() ([]byte, error) {
	type CapabilityResponseSchemaAlias CapabilityResponseSchema
	named, err := json.Marshal(CapabilityResponseSchemaAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *CapabilityResponseSchema) Validate() error {
	if v.present != nil {
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}
