// Code generated by ucpgen. DO NOT EDIT.
// Source: service.json (spec release/2026-04-08@a2d8bf0)

package ucp

import (
	"encoding/json"
	"errors"
)

// ServiceBase is generated from service.json.
type ServiceBase struct {
	// Entity-specific configuration. Structure defined by each entity's schema.
	Config map[string]any `json:"config,omitzero"`
	// Endpoint URL for this transport binding.
	//
	// Not enforced yet (phase 4): format.
	Endpoint *string `json:"endpoint,omitzero"`
	// Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
	ID *string `json:"id,omitzero"`
	// URL to JSON Schema defining this entity's structure and payloads.
	//
	// Not enforced yet (phase 4): format.
	Schema *string `json:"schema,omitzero"`
	// URL to human-readable specification document.
	//
	// Not enforced yet (phase 4): format.
	Spec *string `json:"spec,omitzero"`
	// Transport protocol for this service binding.
	Transport string `json:"transport"`
	// Entity version in YYYY-MM-DD format.
	Version UCPVersion `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *ServiceBase) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("ServiceBase: null is not a valid object")
	}
	type ServiceBaseAlias ServiceBase
	var named ServiceBaseAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = ServiceBase(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"transport", "version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "config")
	delete(all, "endpoint")
	delete(all, "id")
	delete(all, "schema")
	delete(all, "spec")
	delete(all, "transport")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v ServiceBase) MarshalJSON() ([]byte, error) {
	type ServiceBaseAlias ServiceBase
	named, err := json.Marshal(ServiceBaseAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *ServiceBase) Validate() error {
	if v.present != nil {
		if !v.present["transport"] {
			return errors.New("transport: required property is missing")
		}
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if v.Transport != "rest" && v.Transport != "mcp" && v.Transport != "a2a" && v.Transport != "embedded" {
		return errors.New("transport: not one of the permitted values")
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}

// ServiceBusinessSchema Service binding for business/merchant configuration. May override platform endpoints.
//
// The schema also declares 4 anyOf variants that narrow or replace
// these fields; they are not modeled as distinct types yet (phase 4),
// so this type reflects only the shared base.
type ServiceBusinessSchema struct {
	// Entity-specific configuration. Structure defined by each entity's schema.
	Config map[string]any `json:"config,omitzero"`
	// Endpoint URL for this transport binding.
	//
	// Not enforced yet (phase 4): format.
	Endpoint *string `json:"endpoint,omitzero"`
	// Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
	ID *string `json:"id,omitzero"`
	// URL to JSON Schema defining this entity's structure and payloads.
	//
	// Not enforced yet (phase 4): format.
	Schema *string `json:"schema,omitzero"`
	// URL to human-readable specification document.
	//
	// Not enforced yet (phase 4): format.
	Spec *string `json:"spec,omitzero"`
	// Transport protocol for this service binding.
	Transport string `json:"transport"`
	// Entity version in YYYY-MM-DD format.
	Version UCPVersion `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *ServiceBusinessSchema) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("ServiceBusinessSchema: null is not a valid object")
	}
	type ServiceBusinessSchemaAlias ServiceBusinessSchema
	var named ServiceBusinessSchemaAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = ServiceBusinessSchema(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"transport", "version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "config")
	delete(all, "endpoint")
	delete(all, "id")
	delete(all, "schema")
	delete(all, "spec")
	delete(all, "transport")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v ServiceBusinessSchema) MarshalJSON() ([]byte, error) {
	type ServiceBusinessSchemaAlias ServiceBusinessSchema
	named, err := json.Marshal(ServiceBusinessSchemaAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *ServiceBusinessSchema) Validate() error {
	if v.present != nil {
		if !v.present["transport"] {
			return errors.New("transport: required property is missing")
		}
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if v.Transport != "rest" && v.Transport != "mcp" && v.Transport != "a2a" && v.Transport != "embedded" {
		return errors.New("transport: not one of the permitted values")
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}

// ServicePlatformSchema Full service declaration for platform-level discovery. All transports require `version`, `spec`, and `transport`. REST, MCP, and embedded additionally require `schema`.
//
// The schema also declares 4 anyOf variants that narrow or replace
// these fields; they are not modeled as distinct types yet (phase 4),
// so this type reflects only the shared base.
type ServicePlatformSchema struct {
	// Entity-specific configuration. Structure defined by each entity's schema.
	Config map[string]any `json:"config,omitzero"`
	// Endpoint URL for this transport binding.
	//
	// Not enforced yet (phase 4): format.
	Endpoint *string `json:"endpoint,omitzero"`
	// Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
	ID *string `json:"id,omitzero"`
	// URL to JSON Schema defining this entity's structure and payloads.
	//
	// Not enforced yet (phase 4): format.
	Schema *string `json:"schema,omitzero"`
	// URL to human-readable specification document.
	//
	// Not enforced yet (phase 4): format.
	Spec string `json:"spec"`
	// Transport protocol for this service binding.
	Transport string `json:"transport"`
	// Entity version in YYYY-MM-DD format.
	Version UCPVersion `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *ServicePlatformSchema) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("ServicePlatformSchema: null is not a valid object")
	}
	type ServicePlatformSchemaAlias ServicePlatformSchema
	var named ServicePlatformSchemaAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = ServicePlatformSchema(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 3)
	for _, name := range []string{"spec", "transport", "version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "config")
	delete(all, "endpoint")
	delete(all, "id")
	delete(all, "schema")
	delete(all, "spec")
	delete(all, "transport")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v ServicePlatformSchema) MarshalJSON() ([]byte, error) {
	type ServicePlatformSchemaAlias ServicePlatformSchema
	named, err := json.Marshal(ServicePlatformSchemaAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *ServicePlatformSchema) Validate() error {
	if v.present != nil {
		if !v.present["spec"] {
			return errors.New("spec: required property is missing")
		}
		if !v.present["transport"] {
			return errors.New("transport: required property is missing")
		}
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if v.Transport != "rest" && v.Transport != "mcp" && v.Transport != "a2a" && v.Transport != "embedded" {
		return errors.New("transport: not one of the permitted values")
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}

// ServiceResponseSchema Service binding in API responses. Includes per-resource transport configuration via typed config.
//
// The schema also declares 4 anyOf variants that narrow or replace
// these fields; they are not modeled as distinct types yet (phase 4),
// so this type reflects only the shared base.
type ServiceResponseSchema struct {
	// Entity-specific configuration. Structure defined by each entity's schema.
	Config map[string]any `json:"config,omitzero"`
	// Endpoint URL for this transport binding.
	//
	// Not enforced yet (phase 4): format.
	Endpoint *string `json:"endpoint,omitzero"`
	// Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
	ID *string `json:"id,omitzero"`
	// URL to JSON Schema defining this entity's structure and payloads.
	//
	// Not enforced yet (phase 4): format.
	Schema *string `json:"schema,omitzero"`
	// URL to human-readable specification document.
	//
	// Not enforced yet (phase 4): format.
	Spec *string `json:"spec,omitzero"`
	// Transport protocol for this service binding.
	Transport string `json:"transport"`
	// Entity version in YYYY-MM-DD format.
	Version UCPVersion `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *ServiceResponseSchema) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("ServiceResponseSchema: null is not a valid object")
	}
	type ServiceResponseSchemaAlias ServiceResponseSchema
	var named ServiceResponseSchemaAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = ServiceResponseSchema(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"transport", "version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "config")
	delete(all, "endpoint")
	delete(all, "id")
	delete(all, "schema")
	delete(all, "spec")
	delete(all, "transport")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v ServiceResponseSchema) MarshalJSON() ([]byte, error) {
	type ServiceResponseSchemaAlias ServiceResponseSchema
	named, err := json.Marshal(ServiceResponseSchemaAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *ServiceResponseSchema) Validate() error {
	if v.present != nil {
		if !v.present["transport"] {
			return errors.New("transport: required property is missing")
		}
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if v.Transport != "rest" && v.Transport != "mcp" && v.Transport != "a2a" && v.Transport != "embedded" {
		return errors.New("transport: not one of the permitted values")
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}
