// Code generated by ucpgen. DO NOT EDIT.
// Source: ucp.json (spec release/2026-04-08@a2d8bf0)

package ucp

import (
	"encoding/json"
	"errors"
	"regexp"
	"sync"
)

// UCPMetadata Protocol metadata for discovery profiles and responses. Uses slim schema pattern with context-specific required fields.
//
// UCPMetadata is a closed anyOf union: one field is set, holding the
// first alternative that accepted the input. The schema permits more
// than one to match.
type UCPMetadata struct {
	UCPBusinessSchema         *UCPBusinessSchema         `json:"-"`
	UCPPlatformSchema         *UCPPlatformSchema         `json:"-"`
	UCPResponseCartSchema     *UCPResponseCartSchema     `json:"-"`
	UCPResponseCatalogSchema  *UCPResponseCatalogSchema  `json:"-"`
	UCPResponseCheckoutSchema *UCPResponseCheckoutSchema `json:"-"`
	UCPResponseOrderSchema    *UCPResponseOrderSchema    `json:"-"`
}

// UnmarshalJSON decodes the union member that accepts the input,
// preferring one that also validates.
func (v *UCPMetadata) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("UCPMetadata: null is not a valid object")
	}
	var matched, fallback UCPMetadata
	matches := 0
	parsed := false
	var asUCPBusinessSchema UCPBusinessSchema
	if err := json.Unmarshal(data, &asUCPBusinessSchema); err == nil {
		if asUCPBusinessSchema.Validate() == nil {
			if matches == 0 {
				matched = UCPMetadata{UCPBusinessSchema: &asUCPBusinessSchema}
			}
			matches++
		}
		if !parsed {
			fallback, parsed = UCPMetadata{UCPBusinessSchema: &asUCPBusinessSchema}, true
		}
	}
	var asUCPPlatformSchema UCPPlatformSchema
	if err := json.Unmarshal(data, &asUCPPlatformSchema); err == nil {
		if asUCPPlatformSchema.Validate() == nil {
			if matches == 0 {
				matched = UCPMetadata{UCPPlatformSchema: &asUCPPlatformSchema}
			}
			matches++
		}
		if !parsed {
			fallback, parsed = UCPMetadata{UCPPlatformSchema: &asUCPPlatformSchema}, true
		}
	}
	var asUCPResponseCartSchema UCPResponseCartSchema
	if err := json.Unmarshal(data, &asUCPResponseCartSchema); err == nil {
		if asUCPResponseCartSchema.Validate() == nil {
			if matches == 0 {
				matched = UCPMetadata{UCPResponseCartSchema: &asUCPResponseCartSchema}
			}
			matches++
		}
		if !parsed {
			fallback, parsed = UCPMetadata{UCPResponseCartSchema: &asUCPResponseCartSchema}, true
		}
	}
	var asUCPResponseCatalogSchema UCPResponseCatalogSchema
	if err := json.Unmarshal(data, &asUCPResponseCatalogSchema); err == nil {
		if asUCPResponseCatalogSchema.Validate() == nil {
			if matches == 0 {
				matched = UCPMetadata{UCPResponseCatalogSchema: &asUCPResponseCatalogSchema}
			}
			matches++
		}
		if !parsed {
			fallback, parsed = UCPMetadata{UCPResponseCatalogSchema: &asUCPResponseCatalogSchema}, true
		}
	}
	var asUCPResponseCheckoutSchema UCPResponseCheckoutSchema
	if err := json.Unmarshal(data, &asUCPResponseCheckoutSchema); err == nil {
		if asUCPResponseCheckoutSchema.Validate() == nil {
			if matches == 0 {
				matched = UCPMetadata{UCPResponseCheckoutSchema: &asUCPResponseCheckoutSchema}
			}
			matches++
		}
		if !parsed {
			fallback, parsed = UCPMetadata{UCPResponseCheckoutSchema: &asUCPResponseCheckoutSchema}, true
		}
	}
	var asUCPResponseOrderSchema UCPResponseOrderSchema
	if err := json.Unmarshal(data, &asUCPResponseOrderSchema); err == nil {
		if asUCPResponseOrderSchema.Validate() == nil {
			if matches == 0 {
				matched = UCPMetadata{UCPResponseOrderSchema: &asUCPResponseOrderSchema}
			}
			matches++
		}
		if !parsed {
			fallback, parsed = UCPMetadata{UCPResponseOrderSchema: &asUCPResponseOrderSchema}, true
		}
	}
	if matches > 0 {
		*v = matched
		return nil
	}
	if parsed {
		*v = fallback
		return nil
	}
	return errors.New("UCPMetadata: no union member accepted the input")
}

// MarshalJSON encodes whichever union member is set.
func (v UCPMetadata) MarshalJSON() ([]byte, error) {
	if v.UCPBusinessSchema != nil {
		return json.Marshal(v.UCPBusinessSchema)
	}
	if v.UCPPlatformSchema != nil {
		return json.Marshal(v.UCPPlatformSchema)
	}
	if v.UCPResponseCartSchema != nil {
		return json.Marshal(v.UCPResponseCartSchema)
	}
	if v.UCPResponseCatalogSchema != nil {
		return json.Marshal(v.UCPResponseCatalogSchema)
	}
	if v.UCPResponseCheckoutSchema != nil {
		return json.Marshal(v.UCPResponseCheckoutSchema)
	}
	if v.UCPResponseOrderSchema != nil {
		return json.Marshal(v.UCPResponseOrderSchema)
	}
	return nil, errors.New("UCPMetadata: no union member is set")
}

// Validate reports the first constraint violation, or nil.
func (v *UCPMetadata) Validate() error {
	if v.UCPBusinessSchema != nil {
		return v.UCPBusinessSchema.Validate()
	}
	if v.UCPPlatformSchema != nil {
		return v.UCPPlatformSchema.Validate()
	}
	if v.UCPResponseCartSchema != nil {
		return v.UCPResponseCartSchema.Validate()
	}
	if v.UCPResponseCatalogSchema != nil {
		return v.UCPResponseCatalogSchema.Validate()
	}
	if v.UCPResponseCheckoutSchema != nil {
		return v.UCPResponseCheckoutSchema.Validate()
	}
	if v.UCPResponseOrderSchema != nil {
		return v.UCPResponseOrderSchema.Validate()
	}
	return nil
}

// UCPBase Base UCP metadata with shared properties for all schema types.
type UCPBase struct {
	// Capability registry keyed by reverse-domain name.
	Capabilities map[string][]CapabilityBase `json:"capabilities,omitzero"`
	// Payment handler registry keyed by reverse-domain name.
	PaymentHandlers map[string][]PaymentHandlerBase `json:"payment_handlers,omitzero"`
	// Service registry keyed by reverse-domain name.
	Services map[string][]ServiceBase `json:"services,omitzero"`
	// Application-level status of the UCP operation.
	Status  *string    `json:"status,omitzero"`
	Version UCPVersion `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *UCPBase) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("UCPBase: null is not a valid object")
	}
	type UCPBaseAlias UCPBase
	var named UCPBaseAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = UCPBase(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "capabilities")
	delete(all, "payment_handlers")
	delete(all, "services")
	delete(all, "status")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v UCPBase) MarshalJSON() ([]byte, error) {
	type UCPBaseAlias UCPBase
	named, err := json.Marshal(UCPBaseAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *UCPBase) Validate() error {
	if v.present != nil {
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if v.Status != nil && *v.Status != "success" && *v.Status != "error" {
		return errors.New("status: not one of the permitted values")
	}
	for _, m := range v.Capabilities {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.PaymentHandlers {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.Services {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}

// UCPBusinessSchema UCP metadata for business/merchant-level configuration. Subset of platform schema with business-specific settings.
type UCPBusinessSchema struct {
	Capabilities    map[string][]CapabilityBusinessSchema     `json:"capabilities,omitzero"`
	PaymentHandlers map[string][]PaymentHandlerBusinessSchema `json:"payment_handlers"`
	Services        map[string][]ServiceBusinessSchema        `json:"services"`
	// Application-level status of the UCP operation.
	Status *string `json:"status,omitzero"`
	// Previous protocol versions this business supports, mapped to profile URIs. Businesses that support older protocol versions SHOULD advertise each version and link to its profile. Each URI points to a complete, self-contained profile for that version. When omitted, only `version` is supported.
	SupportedVersions map[string]string `json:"supported_versions,omitzero"`
	Version           UCPVersion        `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *UCPBusinessSchema) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("UCPBusinessSchema: null is not a valid object")
	}
	type UCPBusinessSchemaAlias UCPBusinessSchema
	var named UCPBusinessSchemaAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = UCPBusinessSchema(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 3)
	for _, name := range []string{"payment_handlers", "services", "version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "capabilities")
	delete(all, "payment_handlers")
	delete(all, "services")
	delete(all, "status")
	delete(all, "supported_versions")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v UCPBusinessSchema) MarshalJSON() ([]byte, error) {
	type UCPBusinessSchemaAlias UCPBusinessSchema
	named, err := json.Marshal(UCPBusinessSchemaAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *UCPBusinessSchema) Validate() error {
	if v.present != nil {
		if !v.present["payment_handlers"] {
			return errors.New("payment_handlers: required property is missing")
		}
		if !v.present["services"] {
			return errors.New("services: required property is missing")
		}
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if v.Status != nil && *v.Status != "success" && *v.Status != "error" {
		return errors.New("status: not one of the permitted values")
	}
	for _, m := range v.Capabilities {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.PaymentHandlers {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.Services {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}

// UCPEntity Shared foundation for all UCP entities.
type UCPEntity struct {
	// Entity-specific configuration. Structure defined by each entity's schema.
	Config map[string]any `json:"config,omitzero"`
	// Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
	ID *string `json:"id,omitzero"`
	// URL to JSON Schema defining this entity's structure and payloads.
	//
	// Annotation only in draft 2020-12, so not asserted: format.
	Schema *string `json:"schema,omitzero"`
	// URL to human-readable specification document.
	//
	// Annotation only in draft 2020-12, so not asserted: format.
	Spec *string `json:"spec,omitzero"`
	// Entity version in YYYY-MM-DD format.
	Version UCPVersion `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *UCPEntity) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("UCPEntity: null is not a valid object")
	}
	type UCPEntityAlias UCPEntity
	var named UCPEntityAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = UCPEntity(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "config")
	delete(all, "id")
	delete(all, "schema")
	delete(all, "spec")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v UCPEntity) MarshalJSON() ([]byte, error) {
	type UCPEntityAlias UCPEntity
	named, err := json.Marshal(UCPEntityAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *UCPEntity) Validate() error {
	if v.present != nil {
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}

// UCPError UCP metadata with status 'error'. Use for response branches that carry error information.
type UCPError struct {
	// Capability registry keyed by reverse-domain name.
	Capabilities map[string][]CapabilityBase `json:"capabilities,omitzero"`
	// Payment handler registry keyed by reverse-domain name.
	PaymentHandlers map[string][]PaymentHandlerBase `json:"payment_handlers,omitzero"`
	// Service registry keyed by reverse-domain name.
	Services map[string][]ServiceBase `json:"services,omitzero"`
	Status   string                   `json:"status"`
	Version  UCPVersion               `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *UCPError) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("UCPError: null is not a valid object")
	}
	type UCPErrorAlias UCPError
	var named UCPErrorAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = UCPError(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"status", "version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "capabilities")
	delete(all, "payment_handlers")
	delete(all, "services")
	delete(all, "status")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v UCPError) MarshalJSON() ([]byte, error) {
	type UCPErrorAlias UCPError
	named, err := json.Marshal(UCPErrorAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *UCPError) Validate() error {
	if v.present != nil {
		if !v.present["status"] {
			return errors.New("status: required property is missing")
		}
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if v.Status != "error" {
		return errors.New("status: must be \"error\"")
	}
	for _, m := range v.Capabilities {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.PaymentHandlers {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.Services {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}

// UCPPlatformSchema Full UCP metadata for platform-level configuration. Hosted at a URI advertised by the platform in request headers.
type UCPPlatformSchema struct {
	Capabilities    map[string][]CapabilityPlatformSchema     `json:"capabilities,omitzero"`
	PaymentHandlers map[string][]PaymentHandlerPlatformSchema `json:"payment_handlers"`
	Services        map[string][]ServicePlatformSchema        `json:"services"`
	// Application-level status of the UCP operation.
	Status  *string    `json:"status,omitzero"`
	Version UCPVersion `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *UCPPlatformSchema) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("UCPPlatformSchema: null is not a valid object")
	}
	type UCPPlatformSchemaAlias UCPPlatformSchema
	var named UCPPlatformSchemaAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = UCPPlatformSchema(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 3)
	for _, name := range []string{"payment_handlers", "services", "version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "capabilities")
	delete(all, "payment_handlers")
	delete(all, "services")
	delete(all, "status")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v UCPPlatformSchema) MarshalJSON() ([]byte, error) {
	type UCPPlatformSchemaAlias UCPPlatformSchema
	named, err := json.Marshal(UCPPlatformSchemaAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *UCPPlatformSchema) Validate() error {
	if v.present != nil {
		if !v.present["payment_handlers"] {
			return errors.New("payment_handlers: required property is missing")
		}
		if !v.present["services"] {
			return errors.New("services: required property is missing")
		}
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if v.Status != nil && *v.Status != "success" && *v.Status != "error" {
		return errors.New("status: not one of the permitted values")
	}
	for _, m := range v.Capabilities {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.PaymentHandlers {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.Services {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}

// UCPRequires Version requirements for extension schemas. Declares minimum (and optionally maximum) protocol and capability versions needed for correct operation.
type UCPRequires struct {
	// Required capability versions, keyed by capability name. Keys must be a subset of the extension's $defs keys.
	Capabilities map[string]UCPVersionConstraint `json:"capabilities,omitzero"`
	// Required protocol version.
	Protocol *UCPVersionConstraint `json:"protocol,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *UCPRequires) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("UCPRequires: null is not a valid object")
	}
	type UCPRequiresAlias UCPRequires
	var named UCPRequiresAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = UCPRequires(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "capabilities")
	delete(all, "protocol")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v UCPRequires) MarshalJSON() ([]byte, error) {
	type UCPRequiresAlias UCPRequires
	named, err := json.Marshal(UCPRequiresAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *UCPRequires) Validate() error {
	for _, m := range v.Capabilities {
		if err := m.Validate(); err != nil {
			return err
		}
	}
	if v.Protocol != nil {
		if err := v.Protocol.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// UCPResponseCartSchema UCP metadata for cart responses. No payment handlers needed pre-checkout.
type UCPResponseCartSchema struct {
	Capabilities map[string][]CapabilityResponseSchema `json:"capabilities,omitzero"`
	// Payment handler registry keyed by reverse-domain name.
	PaymentHandlers map[string][]PaymentHandlerBase `json:"payment_handlers,omitzero"`
	// Service registry keyed by reverse-domain name.
	Services map[string][]ServiceBase `json:"services,omitzero"`
	// Application-level status of the UCP operation.
	Status  *string    `json:"status,omitzero"`
	Version UCPVersion `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *UCPResponseCartSchema) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("UCPResponseCartSchema: null is not a valid object")
	}
	type UCPResponseCartSchemaAlias UCPResponseCartSchema
	var named UCPResponseCartSchemaAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = UCPResponseCartSchema(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "capabilities")
	delete(all, "payment_handlers")
	delete(all, "services")
	delete(all, "status")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v UCPResponseCartSchema) MarshalJSON() ([]byte, error) {
	type UCPResponseCartSchemaAlias UCPResponseCartSchema
	named, err := json.Marshal(UCPResponseCartSchemaAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *UCPResponseCartSchema) Validate() error {
	if v.present != nil {
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if v.Status != nil && *v.Status != "success" && *v.Status != "error" {
		return errors.New("status: not one of the permitted values")
	}
	for _, m := range v.Capabilities {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.PaymentHandlers {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.Services {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}

// UCPResponseCatalogSchema UCP metadata for catalog responses.
type UCPResponseCatalogSchema struct {
	Capabilities map[string][]CapabilityResponseSchema `json:"capabilities,omitzero"`
	// Payment handler registry keyed by reverse-domain name.
	PaymentHandlers map[string][]PaymentHandlerBase `json:"payment_handlers,omitzero"`
	// Service registry keyed by reverse-domain name.
	Services map[string][]ServiceBase `json:"services,omitzero"`
	// Application-level status of the UCP operation.
	Status  *string    `json:"status,omitzero"`
	Version UCPVersion `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *UCPResponseCatalogSchema) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("UCPResponseCatalogSchema: null is not a valid object")
	}
	type UCPResponseCatalogSchemaAlias UCPResponseCatalogSchema
	var named UCPResponseCatalogSchemaAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = UCPResponseCatalogSchema(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "capabilities")
	delete(all, "payment_handlers")
	delete(all, "services")
	delete(all, "status")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v UCPResponseCatalogSchema) MarshalJSON() ([]byte, error) {
	type UCPResponseCatalogSchemaAlias UCPResponseCatalogSchema
	named, err := json.Marshal(UCPResponseCatalogSchemaAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *UCPResponseCatalogSchema) Validate() error {
	if v.present != nil {
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if v.Status != nil && *v.Status != "success" && *v.Status != "error" {
		return errors.New("status: not one of the permitted values")
	}
	for _, m := range v.Capabilities {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.PaymentHandlers {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.Services {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}

// UCPResponseCheckoutSchema UCP metadata for checkout responses.
type UCPResponseCheckoutSchema struct {
	Capabilities    map[string][]CapabilityResponseSchema     `json:"capabilities,omitzero"`
	PaymentHandlers map[string][]PaymentHandlerResponseSchema `json:"payment_handlers"`
	Services        map[string][]ServiceResponseSchema        `json:"services,omitzero"`
	// Application-level status of the UCP operation.
	Status  *string    `json:"status,omitzero"`
	Version UCPVersion `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *UCPResponseCheckoutSchema) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("UCPResponseCheckoutSchema: null is not a valid object")
	}
	type UCPResponseCheckoutSchemaAlias UCPResponseCheckoutSchema
	var named UCPResponseCheckoutSchemaAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = UCPResponseCheckoutSchema(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"payment_handlers", "version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "capabilities")
	delete(all, "payment_handlers")
	delete(all, "services")
	delete(all, "status")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v UCPResponseCheckoutSchema) MarshalJSON() ([]byte, error) {
	type UCPResponseCheckoutSchemaAlias UCPResponseCheckoutSchema
	named, err := json.Marshal(UCPResponseCheckoutSchemaAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *UCPResponseCheckoutSchema) Validate() error {
	if v.present != nil {
		if !v.present["payment_handlers"] {
			return errors.New("payment_handlers: required property is missing")
		}
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if v.Status != nil && *v.Status != "success" && *v.Status != "error" {
		return errors.New("status: not one of the permitted values")
	}
	for _, m := range v.Capabilities {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.PaymentHandlers {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.Services {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}

// UCPResponseOrderSchema UCP metadata for order responses. No payment handlers needed post-purchase.
type UCPResponseOrderSchema struct {
	Capabilities map[string][]CapabilityResponseSchema `json:"capabilities,omitzero"`
	// Payment handler registry keyed by reverse-domain name.
	PaymentHandlers map[string][]PaymentHandlerBase `json:"payment_handlers,omitzero"`
	// Service registry keyed by reverse-domain name.
	Services map[string][]ServiceBase `json:"services,omitzero"`
	// Application-level status of the UCP operation.
	Status  *string    `json:"status,omitzero"`
	Version UCPVersion `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *UCPResponseOrderSchema) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("UCPResponseOrderSchema: null is not a valid object")
	}
	type UCPResponseOrderSchemaAlias UCPResponseOrderSchema
	var named UCPResponseOrderSchemaAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = UCPResponseOrderSchema(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "capabilities")
	delete(all, "payment_handlers")
	delete(all, "services")
	delete(all, "status")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v UCPResponseOrderSchema) MarshalJSON() ([]byte, error) {
	type UCPResponseOrderSchemaAlias UCPResponseOrderSchema
	named, err := json.Marshal(UCPResponseOrderSchemaAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *UCPResponseOrderSchema) Validate() error {
	if v.present != nil {
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if v.Status != nil && *v.Status != "success" && *v.Status != "error" {
		return errors.New("status: not one of the permitted values")
	}
	for _, m := range v.Capabilities {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.PaymentHandlers {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.Services {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}

// UCPSuccess UCP metadata with status 'success'. Use for response branches that carry the expected payload.
type UCPSuccess struct {
	// Capability registry keyed by reverse-domain name.
	Capabilities map[string][]CapabilityBase `json:"capabilities,omitzero"`
	// Payment handler registry keyed by reverse-domain name.
	PaymentHandlers map[string][]PaymentHandlerBase `json:"payment_handlers,omitzero"`
	// Service registry keyed by reverse-domain name.
	Services map[string][]ServiceBase `json:"services,omitzero"`
	Status   string                   `json:"status"`
	Version  UCPVersion               `json:"version"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *UCPSuccess) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("UCPSuccess: null is not a valid object")
	}
	type UCPSuccessAlias UCPSuccess
	var named UCPSuccessAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = UCPSuccess(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"status", "version"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "capabilities")
	delete(all, "payment_handlers")
	delete(all, "services")
	delete(all, "status")
	delete(all, "version")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v UCPSuccess) MarshalJSON() ([]byte, error) {
	type UCPSuccessAlias UCPSuccess
	named, err := json.Marshal(UCPSuccessAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *UCPSuccess) Validate() error {
	if v.present != nil {
		if !v.present["status"] {
			return errors.New("status: required property is missing")
		}
		if !v.present["version"] {
			return errors.New("version: required property is missing")
		}
	}
	if v.Status != "success" {
		return errors.New("status: must be \"success\"")
	}
	for _, m := range v.Capabilities {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.PaymentHandlers {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	for _, m := range v.Services {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	if err := v.Version.Validate(); err != nil {
		return err
	}
	return nil
}

// UCPVersion UCP version in YYYY-MM-DD format.
type UCPVersion string

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *UCPVersion) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("UCPVersion: null is not a valid string")
	}
	type UCPVersionAlias UCPVersion
	var alias UCPVersionAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = UCPVersion(alias)
	return nil
}

var pattern_UCPVersion = sync.OnceValue(func() *regexp.Regexp { return regexp.MustCompile("^\\d{4}-\\d{2}-\\d{2}$") })

// Validate reports the first constraint violation, or nil.
func (v *UCPVersion) Validate() error {
	if !pattern_UCPVersion().MatchString(string(*v)) {
		return errors.New("UCPVersion: does not match pattern")
	}
	return nil
}

// UCPVersionConstraint Version range requirement with minimum and optional maximum.
type UCPVersionConstraint struct {
	// Maximum compatible version (inclusive). When absent, no upper bound.
	Max *UCPVersion `json:"max,omitzero"`
	// Minimum required version (inclusive).
	Min UCPVersion `json:"min"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *UCPVersionConstraint) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("UCPVersionConstraint: null is not a valid object")
	}
	type UCPVersionConstraintAlias UCPVersionConstraint
	var named UCPVersionConstraintAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = UCPVersionConstraint(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"min"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "max")
	delete(all, "min")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v UCPVersionConstraint) MarshalJSON() ([]byte, error) {
	type UCPVersionConstraintAlias UCPVersionConstraint
	named, err := json.Marshal(UCPVersionConstraintAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *UCPVersionConstraint) Validate() error {
	if v.present != nil {
		if !v.present["min"] {
			return errors.New("min: required property is missing")
		}
	}
	if v.Max != nil {
		if err := v.Max.Validate(); err != nil {
			return err
		}
	}
	if err := v.Min.Validate(); err != nil {
		return err
	}
	return nil
}
