package conformance

import (
	"bytes"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// generatedHeader marks a file as ucpgen output. It is the reliable way to
// tell shipped models from hand-written code in the same directories.
const generatedHeader = "// Code generated by ucpgen. DO NOT EDIT."

// TestCommittedModelsMatchGenerator is the gate that makes committing
// generated code safe: it proves the committed tree is exactly what the
// generator produces from the committed goldens.
//
// The provenance stamp is read back out of the committed MANIFEST.json and
// fed to the regeneration. Without that, every file's "(spec ...)" header
// line would differ and the diff would have to special-case it.
//
// This does not check the goldens against the upstream spec — that is
// TestPreprocessMatchesGoldens, and spec drift is caught by running
// generate.sh, which is a deliberate act requiring network.
func TestCommittedModelsMatchGenerator(t *testing.T) {
	repoRoot, err := filepath.Abs("..")
	if err != nil {
		t.Fatal(err)
	}
	goldens := filepath.Join(repoRoot, "goldens", goldenVersion)
	if _, err := os.Stat(goldens); err != nil {
		t.Skipf("goldens missing (%v)", err)
	}

	raw, err := os.ReadFile(filepath.Join(repoRoot, "MANIFEST.json"))
	if err != nil {
		t.Fatalf("read committed MANIFEST.json: %v (are the models committed?)", err)
	}
	var manifest struct {
		SpecRef string `json:"spec_ref"`
	}
	if err := json.Unmarshal(raw, &manifest); err != nil {
		t.Fatalf("parse MANIFEST.json: %v", err)
	}
	if manifest.SpecRef == "" {
		t.Fatal("MANIFEST.json has no spec_ref; regeneration cannot reproduce the header stamp")
	}

	out := t.TempDir()
	gen := exec.Command("go", "run", "./cmd/ucpgen", "emit",
		"-schemas", goldens, "-out", out, "-spec-ref", manifest.SpecRef)
	gen.Dir = repoRoot
	if b, err := gen.CombinedOutput(); err != nil {
		t.Fatalf("emit failed: %v\n%s", err, b)
	}

	fresh := collectFiles(t, out)
	committed := collectGenerated(t, repoRoot)

	var problems []string
	for _, rel := range sortedKeys(fresh) {
		got, ok := committed[rel]
		if !ok {
			problems = append(problems, "missing from the repo: "+rel)
			continue
		}
		if !bytes.Equal(fresh[rel], got) {
			problems = append(problems, "differs from the generator: "+rel)
		}
	}
	for _, rel := range sortedKeys(committed) {
		if _, ok := fresh[rel]; !ok {
			problems = append(problems, "stale, no longer generated: "+rel)
		}
	}
	if len(problems) > 0 {
		t.Errorf("committed models are out of date — run ./generate.sh and commit the result:\n  %s",
			strings.Join(problems, "\n  "))
	}
}

// collectFiles reads every file under root, keyed by its path relative to
// root.
func collectFiles(t *testing.T, root string) map[string][]byte {
	t.Helper()
	out := map[string][]byte{}
	err := filepath.Walk(root, func(p string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		rel, err := filepath.Rel(root, p)
		if err != nil {
			return err
		}
		b, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		out[filepath.ToSlash(rel)] = b
		return nil
	})
	if err != nil {
		t.Fatalf("walk %s: %v", root, err)
	}
	return out
}

// collectGenerated reads the committed generated tree: every .go file
// carrying the generated header, plus MANIFEST.json. Hand-written packages
// under cmd/ and conformance/ are skipped, as is the goldens corpus.
func collectGenerated(t *testing.T, root string) map[string][]byte {
	t.Helper()
	out := map[string][]byte{}
	skip := map[string]bool{".git": true, "cmd": true, "conformance": true,
		"goldens": true, "docs": true, "scripts": true, ".github": true}

	entries, err := os.ReadDir(root)
	if err != nil {
		t.Fatalf("read %s: %v", root, err)
	}
	for _, e := range entries {
		if skip[e.Name()] || strings.HasPrefix(e.Name(), ".") {
			continue
		}
		p := filepath.Join(root, e.Name())
		if e.IsDir() {
			for rel, b := range collectFiles(t, p) {
				if strings.HasSuffix(rel, ".go") && bytes.HasPrefix(b, []byte(generatedHeader)) {
					out[e.Name()+"/"+rel] = b
				}
			}
			continue
		}
		b, err := os.ReadFile(p)
		if err != nil {
			t.Fatal(err)
		}
		if e.Name() == "MANIFEST.json" ||
			(strings.HasSuffix(e.Name(), ".go") && bytes.HasPrefix(b, []byte(generatedHeader))) {
			out[e.Name()] = b
		}
	}
	return out
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
