package conformance

import (
	"sort"
	"testing"

	ucp "github.com/chaz8081/ucp-go"
	common "github.com/chaz8081/ucp-go/common"
	commontypes "github.com/chaz8081/ucp-go/common/types"
	shopping "github.com/chaz8081/ucp-go/shopping"
	shoppingtypes "github.com/chaz8081/ucp-go/shopping/types"
	transports "github.com/chaz8081/ucp-go/transports"
)

// validator is the uniform interface every generated type satisfies.
type validator interface{ Validate() error }

// models maps a schema location to a fresh value of the Go type it
// produces. A location is a schema path for a file-level type, or
// "<path>#<defName>" for a type emitted from a $def.
//
// Go cannot construct a type from a name, so driving the corpus by schema
// location needs an explicit table. It is generated from the emitter's type
// index rather than hand-written, and TestModelsCoverCorpus and
// TestModelsCoverDefs below fail if it ever falls behind the corpus.
//
// Only locations that emit a type appear: the rest — a document root that is
// nothing but a $defs container, a $def that is a namespace grouping other
// schemas — produce no value to construct.
var models = map[string]func() validator{
	"capability.json#base":                                                              func() validator { return new(ucp.CapabilityBase) },
	"capability.json#business_schema":                                                   func() validator { return new(ucp.CapabilityBusinessSchema) },
	"capability.json#platform_schema":                                                   func() validator { return new(ucp.CapabilityPlatformSchema) },
	"capability.json#response_schema":                                                   func() validator { return new(ucp.CapabilityResponseSchema) },
	"common/identity_linking.json#provider":                                             func() validator { return new(common.IdentityLinkingProvider) },
	"common/identity_linking.json#scope_policy":                                         func() validator { return new(common.IdentityLinkingScopePolicy) },
	"common/identity_linking.json#scope_token":                                          func() validator { return new(common.IdentityLinkingScopeToken) },
	"common/location_lookup.json":                                                       func() validator { return new(common.LocationLookup) },
	"common/location_lookup.json#lookup_location":                                       func() validator { return new(common.LocationLookupLookupLocation) },
	"common/location_lookup.json#lookup_request":                                        func() validator { return new(common.LocationLookupLookupRequest) },
	"common/location_lookup.json#lookup_response":                                       func() validator { return new(common.LocationLookupLookupResponse) },
	"common/location_search.json":                                                       func() validator { return new(common.LocationSearch) },
	"common/location_search.json#search_request":                                        func() validator { return new(common.LocationSearchSearchRequest) },
	"common/location_search.json#search_response":                                       func() validator { return new(common.LocationSearchSearchResponse) },
	"common/loyalty.json#cart":                                                          func() validator { return new(common.LoyaltyCart) },
	"common/loyalty.json#checkout":                                                      func() validator { return new(common.LoyaltyCheckout) },
	"common/loyalty.json#earning_breakdown":                                             func() validator { return new(common.LoyaltyEarningBreakdown) },
	"common/loyalty.json#earning_forecast":                                              func() validator { return new(common.LoyaltyEarningForecast) },
	"common/loyalty.json#lookup":                                                        func() validator { return new(common.LoyaltyLookup) },
	"common/loyalty.json#loyalty":                                                       func() validator { return new(common.LoyaltyLoyalty) },
	"common/loyalty.json#loyalty_membership":                                            func() validator { return new(common.LoyaltyLoyaltyMembership) },
	"common/loyalty.json#membership_reward":                                             func() validator { return new(common.LoyaltyMembershipReward) },
	"common/loyalty.json#membership_tier":                                               func() validator { return new(common.LoyaltyMembershipTier) },
	"common/loyalty.json#membership_tier_benefit":                                       func() validator { return new(common.LoyaltyMembershipTierBenefit) },
	"common/loyalty.json#reward_amount":                                                 func() validator { return new(common.LoyaltyRewardAmount) },
	"common/loyalty.json#reward_currency":                                               func() validator { return new(common.LoyaltyRewardCurrency) },
	"common/loyalty.json#search":                                                        func() validator { return new(common.LoyaltySearch) },
	"common/payment_ap2_mandate.json#ap2_with_checkout_mandate":                         func() validator { return new(common.PaymentAP2MandateAP2WithCheckoutMandate) },
	"common/payment_ap2_mandate.json#ap2_with_merchant_authorization":                   func() validator { return new(common.PaymentAP2MandateAP2WithMerchantAuthorization) },
	"common/payment_ap2_mandate.json#checkout":                                          func() validator { return new(common.PaymentAP2MandateCheckout) },
	"common/payment_ap2_mandate.json#checkout_mandate":                                  func() validator { return new(common.PaymentAP2MandateCheckoutMandate) },
	"common/payment_ap2_mandate.json#error_code":                                        func() validator { return new(common.PaymentAP2MandateErrorCode) },
	"common/payment_ap2_mandate.json#merchant_authorization":                            func() validator { return new(common.PaymentAP2MandateMerchantAuthorization) },
	"common/payment_authentication.json#checkout":                                       func() validator { return new(common.PaymentAuthenticationCheckout) },
	"common/payment_split_payments.json#checkout":                                       func() validator { return new(common.PaymentSplitPaymentsCheckout) },
	"common/payment_split_payments.json#instrument_group":                               func() validator { return new(common.PaymentSplitPaymentsInstrumentGroup) },
	"common/payment_split_payments.json#payment_instrument":                             func() validator { return new(common.PaymentSplitPaymentsPaymentInstrument) },
	"common/payment_terms.json#checkout":                                                func() validator { return new(common.PaymentTermsCheckout) },
	"common/payment_terms.json#order":                                                   func() validator { return new(common.PaymentTermsOrder) },
	"common/payment_terms.json#order_payment":                                           func() validator { return new(common.PaymentTermsOrderPayment) },
	"common/payment_terms.json#payment":                                                 func() validator { return new(common.PaymentTermsPayment) },
	"common/payment_terms.json#payment_term":                                            func() validator { return new(common.PaymentTermsPaymentTerm) },
	"common/types/actions.json":                                                         func() validator { return new(commontypes.Actions) },
	"common/types/actions.json#instance":                                                func() validator { return new(commontypes.ActionsInstance) },
	"common/types/amenity_type.json":                                                    func() validator { return new(commontypes.AmenityType) },
	"common/types/amount.json":                                                          func() validator { return new(commontypes.Amount) },
	"common/types/available_payment_instrument.json":                                    func() validator { return new(commontypes.AvailablePaymentInstrument) },
	"common/types/binding.json":                                                         func() validator { return new(commontypes.Binding) },
	"common/types/business_split_payments_config.json":                                  func() validator { return new(commontypes.BusinessSplitPaymentsConfig) },
	"common/types/card_credential.json":                                                 func() validator { return new(commontypes.CardCredential) },
	"common/types/card_payment_instrument.json":                                         func() validator { return new(commontypes.CardPaymentInstrument) },
	"common/types/card_payment_instrument.json#constraint_target":                       func() validator { return new(commontypes.CardPaymentInstrumentConstraintTarget) },
	"common/types/constraint_expression.json":                                           func() validator { return new(commontypes.ConstraintExpression) },
	"common/types/constraint_expression.json#value_constraint":                          func() validator { return new(commontypes.ConstraintExpressionValueConstraint) },
	"common/types/context.json":                                                         func() validator { return new(commontypes.Context) },
	"common/types/context_create_request.json":                                          func() validator { return new(commontypes.ContextCreateRequest) },
	"common/types/context_update_request.json":                                          func() validator { return new(commontypes.ContextUpdateRequest) },
	"common/types/daily_hour.json":                                                      func() validator { return new(commontypes.DailyHour) },
	"common/types/daily_hour_create_request.json":                                       func() validator { return new(commontypes.DailyHourCreateRequest) },
	"common/types/daily_hour_update_request.json":                                       func() validator { return new(commontypes.DailyHourUpdateRequest) },
	"common/types/description.json":                                                     func() validator { return new(commontypes.Description) },
	"common/types/error_code.json":                                                      func() validator { return new(commontypes.ErrorCode) },
	"common/types/error_code_create_request.json":                                       func() validator { return new(commontypes.ErrorCodeCreateRequest) },
	"common/types/error_code_update_request.json":                                       func() validator { return new(commontypes.ErrorCodeUpdateRequest) },
	"common/types/error_response.json":                                                  func() validator { return new(commontypes.ErrorResponse) },
	"common/types/exception_hour.json":                                                  func() validator { return new(commontypes.ExceptionHour) },
	"common/types/exception_hour_create_request.json":                                   func() validator { return new(commontypes.ExceptionHourCreateRequest) },
	"common/types/exception_hour_update_request.json":                                   func() validator { return new(commontypes.ExceptionHourUpdateRequest) },
	"common/types/geo.json":                                                             func() validator { return new(commontypes.Geo) },
	"common/types/geo_create_request.json":                                              func() validator { return new(commontypes.GeoCreateRequest) },
	"common/types/geo_update_request.json":                                              func() validator { return new(commontypes.GeoUpdateRequest) },
	"common/types/info_code.json":                                                       func() validator { return new(commontypes.InfoCode) },
	"common/types/info_code_create_request.json":                                        func() validator { return new(commontypes.InfoCodeCreateRequest) },
	"common/types/info_code_update_request.json":                                        func() validator { return new(commontypes.InfoCodeUpdateRequest) },
	"common/types/instrument_group.json":                                                func() validator { return new(commontypes.InstrumentGroup) },
	"common/types/link.json":                                                            func() validator { return new(commontypes.Link) },
	"common/types/locality.json":                                                        func() validator { return new(commontypes.Locality) },
	"common/types/locality_create_request.json":                                         func() validator { return new(commontypes.LocalityCreateRequest) },
	"common/types/locality_update_request.json":                                         func() validator { return new(commontypes.LocalityUpdateRequest) },
	"common/types/location.json":                                                        func() validator { return new(commontypes.Location) },
	"common/types/location.json#amenity":                                                func() validator { return new(commontypes.LocationAmenity) },
	"common/types/location_create_request.json":                                         func() validator { return new(commontypes.LocationCreateRequest) },
	"common/types/location_create_request.json#amenity":                                 func() validator { return new(commontypes.LocationCreateRequestAmenity) },
	"common/types/location_distance.json":                                               func() validator { return new(commontypes.LocationDistance) },
	"common/types/location_filter.json":                                                 func() validator { return new(commontypes.LocationFilter) },
	"common/types/location_serves.json":                                                 func() validator { return new(commontypes.LocationServes) },
	"common/types/location_serves_create_request.json":                                  func() validator { return new(commontypes.LocationServesCreateRequest) },
	"common/types/location_serves_update_request.json":                                  func() validator { return new(commontypes.LocationServesUpdateRequest) },
	"common/types/location_summary.json":                                                func() validator { return new(commontypes.LocationSummary) },
	"common/types/location_summary_create_request.json":                                 func() validator { return new(commontypes.LocationSummaryCreateRequest) },
	"common/types/location_summary_update_request.json":                                 func() validator { return new(commontypes.LocationSummaryUpdateRequest) },
	"common/types/location_update_request.json":                                         func() validator { return new(commontypes.LocationUpdateRequest) },
	"common/types/location_update_request.json#amenity":                                 func() validator { return new(commontypes.LocationUpdateRequestAmenity) },
	"common/types/measure.json":                                                         func() validator { return new(commontypes.Measure) },
	"common/types/measure_create_request.json":                                          func() validator { return new(commontypes.MeasureCreateRequest) },
	"common/types/measure_update_request.json":                                          func() validator { return new(commontypes.MeasureUpdateRequest) },
	"common/types/media.json":                                                           func() validator { return new(commontypes.Media) },
	"common/types/message.json":                                                         func() validator { return new(commontypes.Message) },
	"common/types/message_create_request.json":                                          func() validator { return new(commontypes.MessageCreateRequest) },
	"common/types/message_error.json":                                                   func() validator { return new(commontypes.MessageError) },
	"common/types/message_error_create_request.json":                                    func() validator { return new(commontypes.MessageErrorCreateRequest) },
	"common/types/message_error_update_request.json":                                    func() validator { return new(commontypes.MessageErrorUpdateRequest) },
	"common/types/message_info.json":                                                    func() validator { return new(commontypes.MessageInfo) },
	"common/types/message_info_create_request.json":                                     func() validator { return new(commontypes.MessageInfoCreateRequest) },
	"common/types/message_info_update_request.json":                                     func() validator { return new(commontypes.MessageInfoUpdateRequest) },
	"common/types/message_update_request.json":                                          func() validator { return new(commontypes.MessageUpdateRequest) },
	"common/types/message_warning.json":                                                 func() validator { return new(commontypes.MessageWarning) },
	"common/types/message_warning_create_request.json":                                  func() validator { return new(commontypes.MessageWarningCreateRequest) },
	"common/types/message_warning_update_request.json":                                  func() validator { return new(commontypes.MessageWarningUpdateRequest) },
	"common/types/network_token_credential.json":                                        func() validator { return new(commontypes.NetworkTokenCredential) },
	"common/types/pagination.json":                                                      func() validator { return new(commontypes.Pagination) },
	"common/types/pagination.json#request":                                              func() validator { return new(commontypes.PaginationRequest) },
	"common/types/pagination.json#response":                                             func() validator { return new(commontypes.PaginationResponse) },
	"common/types/pan_credential.json":                                                  func() validator { return new(commontypes.PanCredential) },
	"common/types/payment.json":                                                         func() validator { return new(commontypes.Payment) },
	"common/types/payment_complete_request.json":                                        func() validator { return new(commontypes.PaymentCompleteRequest) },
	"common/types/payment_create_request.json":                                          func() validator { return new(commontypes.PaymentCreateRequest) },
	"common/types/payment_credential.json":                                              func() validator { return new(commontypes.PaymentCredential) },
	"common/types/payment_credential_complete_request.json":                             func() validator { return new(commontypes.PaymentCredentialCompleteRequest) },
	"common/types/payment_credential_create_request.json":                               func() validator { return new(commontypes.PaymentCredentialCreateRequest) },
	"common/types/payment_credential_update_request.json":                               func() validator { return new(commontypes.PaymentCredentialUpdateRequest) },
	"common/types/payment_identity.json":                                                func() validator { return new(commontypes.PaymentIdentity) },
	"common/types/payment_instrument.json":                                              func() validator { return new(commontypes.PaymentInstrument) },
	"common/types/payment_instrument.json#selected_payment_instrument":                  func() validator { return new(commontypes.PaymentInstrumentSelectedPaymentInstrument) },
	"common/types/payment_instrument_complete_request.json":                             func() validator { return new(commontypes.PaymentInstrumentCompleteRequest) },
	"common/types/payment_instrument_complete_request.json#selected_payment_instrument": func() validator { return new(commontypes.PaymentInstrumentCompleteRequestSelectedPaymentInstrument) },
	"common/types/payment_instrument_create_request.json":                               func() validator { return new(commontypes.PaymentInstrumentCreateRequest) },
	"common/types/payment_instrument_create_request.json#selected_payment_instrument":   func() validator { return new(commontypes.PaymentInstrumentCreateRequestSelectedPaymentInstrument) },
	"common/types/payment_instrument_update_request.json":                               func() validator { return new(commontypes.PaymentInstrumentUpdateRequest) },
	"common/types/payment_instrument_update_request.json#selected_payment_instrument":   func() validator { return new(commontypes.PaymentInstrumentUpdateRequestSelectedPaymentInstrument) },
	"common/types/payment_schedule.json":                                                func() validator { return new(commontypes.PaymentSchedule) },
	"common/types/payment_term.json":                                                    func() validator { return new(commontypes.PaymentTerm) },
	"common/types/payment_update_request.json":                                          func() validator { return new(commontypes.PaymentUpdateRequest) },
	"common/types/policy.json":                                                          func() validator { return new(commontypes.Policy) },
	"common/types/postal_address.json":                                                  func() validator { return new(commontypes.PostalAddress) },
	"common/types/postal_address_complete_request.json":                                 func() validator { return new(commontypes.PostalAddressCompleteRequest) },
	"common/types/postal_address_create_request.json":                                   func() validator { return new(commontypes.PostalAddressCreateRequest) },
	"common/types/postal_address_update_request.json":                                   func() validator { return new(commontypes.PostalAddressUpdateRequest) },
	"common/types/price.json":                                                           func() validator { return new(commontypes.Price) },
	"common/types/price_filter.json":                                                    func() validator { return new(commontypes.PriceFilter) },
	"common/types/price_range.json":                                                     func() validator { return new(commontypes.PriceRange) },
	"common/types/quantity_unit.json":                                                   func() validator { return new(commontypes.QuantityUnit) },
	"common/types/quantity_unit_create_request.json":                                    func() validator { return new(commontypes.QuantityUnitCreateRequest) },
	"common/types/quantity_unit_update_request.json":                                    func() validator { return new(commontypes.QuantityUnitUpdateRequest) },
	"common/types/request_constraints.json":                                             func() validator { return new(commontypes.RequestConstraints) },
	"common/types/reverse_domain_name.json":                                             func() validator { return new(commontypes.ReverseDomainName) },
	"common/types/reverse_domain_name_create_request.json":                              func() validator { return new(commontypes.ReverseDomainNameCreateRequest) },
	"common/types/reverse_domain_name_update_request.json":                              func() validator { return new(commontypes.ReverseDomainNameUpdateRequest) },
	"common/types/signals.json":                                                         func() validator { return new(commontypes.Signals) },
	"common/types/signals_complete_request.json":                                        func() validator { return new(commontypes.SignalsCompleteRequest) },
	"common/types/signals_create_request.json":                                          func() validator { return new(commontypes.SignalsCreateRequest) },
	"common/types/signals_update_request.json":                                          func() validator { return new(commontypes.SignalsUpdateRequest) },
	"common/types/signed_amount.json":                                                   func() validator { return new(commontypes.SignedAmount) },
	"common/types/signed_amount_create_request.json":                                    func() validator { return new(commontypes.SignedAmountCreateRequest) },
	"common/types/signed_amount_update_request.json":                                    func() validator { return new(commontypes.SignedAmountUpdateRequest) },
	"common/types/time_interval.json":                                                   func() validator { return new(commontypes.TimeInterval) },
	"common/types/time_interval_create_request.json":                                    func() validator { return new(commontypes.TimeIntervalCreateRequest) },
	"common/types/time_interval_update_request.json":                                    func() validator { return new(commontypes.TimeIntervalUpdateRequest) },
	"common/types/token_credential.json":                                                func() validator { return new(commontypes.TokenCredential) },
	"common/types/total.json":                                                           func() validator { return new(commontypes.Total) },
	"common/types/total_create_request.json":                                            func() validator { return new(commontypes.TotalCreateRequest) },
	"common/types/total_update_request.json":                                            func() validator { return new(commontypes.TotalUpdateRequest) },
	"common/types/totals.json":                                                          func() validator { return new(commontypes.Totals) },
	"common/types/totals_create_request.json":                                           func() validator { return new(commontypes.TotalsCreateRequest) },
	"common/types/totals_update_request.json":                                           func() validator { return new(commontypes.TotalsUpdateRequest) },
	"common/types/unit.json":                                                            func() validator { return new(commontypes.Unit) },
	"common/types/unit_create_request.json":                                             func() validator { return new(commontypes.UnitCreateRequest) },
	"common/types/unit_update_request.json":                                             func() validator { return new(commontypes.UnitUpdateRequest) },
	"common/types/warning_code.json":                                                    func() validator { return new(commontypes.WarningCode) },
	"common/types/warning_code_create_request.json":                                     func() validator { return new(commontypes.WarningCodeCreateRequest) },
	"common/types/warning_code_update_request.json":                                     func() validator { return new(commontypes.WarningCodeUpdateRequest) },
	"payment_handler.json#base":                                                         func() validator { return new(ucp.PaymentHandlerBase) },
	"payment_handler.json#business_schema":                                              func() validator { return new(ucp.PaymentHandlerBusinessSchema) },
	"payment_handler.json#platform_schema":                                              func() validator { return new(ucp.PaymentHandlerPlatformSchema) },
	"payment_handler.json#response_schema":                                              func() validator { return new(ucp.PaymentHandlerResponseSchema) },
	"profile.json":                                                                      func() validator { return new(ucp.UCPProfileDocument) },
	"profile.json#base":                                                                 func() validator { return new(ucp.ProfileBase) },
	"profile.json#business_schema":                                                      func() validator { return new(ucp.ProfileBusinessSchema) },
	"profile.json#jwk_public_key":                                                       func() validator { return new(ucp.ProfileJWKPublicKey) },
	"profile.json#platform_schema":                                                      func() validator { return new(ucp.ProfilePlatformSchema) },
	"service.json#base":                                                                 func() validator { return new(ucp.ServiceBase) },
	"service.json#business_schema":                                                      func() validator { return new(ucp.ServiceBusinessSchema) },
	"service.json#platform_schema":                                                      func() validator { return new(ucp.ServicePlatformSchema) },
	"service.json#response_schema":                                                      func() validator { return new(ucp.ServiceResponseSchema) },
	"shopping/buyer_consent.json#buyer":                                                 func() validator { return new(shopping.BuyerConsentBuyer) },
	"shopping/buyer_consent.json#cart":                                                  func() validator { return new(shopping.BuyerConsentCart) },
	"shopping/buyer_consent.json#checkout":                                              func() validator { return new(shopping.BuyerConsentCheckout) },
	"shopping/buyer_consent.json#consent":                                               func() validator { return new(shopping.BuyerConsentConsent) },
	"shopping/buyer_consent.json#consent_purpose":                                       func() validator { return new(shopping.BuyerConsentConsentPurpose) },
	"shopping/buyer_consent.json#consent_segment":                                       func() validator { return new(shopping.BuyerConsentConsentSegment) },
	"shopping/cart.json":                                                                func() validator { return new(shopping.Cart) },
	"shopping/cart.json#checkout":                                                       func() validator { return new(shopping.CartCheckout) },
	"shopping/cart_create_request.json":                                                 func() validator { return new(shopping.CartCreateRequest) },
	"shopping/cart_create_request.json#checkout":                                        func() validator { return new(shopping.CartCreateRequestCheckout) },
	"shopping/cart_update_request.json":                                                 func() validator { return new(shopping.CartUpdateRequest) },
	"shopping/cart_update_request.json#checkout":                                        func() validator { return new(shopping.CartUpdateRequestCheckout) },
	"shopping/catalog_lookup.json":                                                      func() validator { return new(shopping.CatalogLookup) },
	"shopping/catalog_lookup.json#detail_product":                                       func() validator { return new(shopping.CatalogLookupDetailProduct) },
	"shopping/catalog_lookup.json#get_product_request":                                  func() validator { return new(shopping.CatalogLookupGetProductRequest) },
	"shopping/catalog_lookup.json#get_product_response":                                 func() validator { return new(shopping.CatalogLookupGetProductResponse) },
	"shopping/catalog_lookup.json#lookup_request":                                       func() validator { return new(shopping.CatalogLookupLookupRequest) },
	"shopping/catalog_lookup.json#lookup_response":                                      func() validator { return new(shopping.CatalogLookupLookupResponse) },
	"shopping/catalog_lookup.json#lookup_variant":                                       func() validator { return new(shopping.CatalogLookupLookupVariant) },
	"shopping/catalog_search.json":                                                      func() validator { return new(shopping.CatalogSearch) },
	"shopping/catalog_search.json#search_request":                                       func() validator { return new(shopping.CatalogSearchSearchRequest) },
	"shopping/catalog_search.json#search_response":                                      func() validator { return new(shopping.CatalogSearchSearchResponse) },
	"shopping/checkout.json":                                                            func() validator { return new(shopping.Checkout) },
	"shopping/checkout_complete_request.json":                                           func() validator { return new(shopping.CheckoutCompleteRequest) },
	"shopping/checkout_create_request.json":                                             func() validator { return new(shopping.CheckoutCreateRequest) },
	"shopping/checkout_update_request.json":                                             func() validator { return new(shopping.CheckoutUpdateRequest) },
	"shopping/discount.json#allocation":                                                 func() validator { return new(shopping.DiscountAllocation) },
	"shopping/discount.json#applied_discount":                                           func() validator { return new(shopping.DiscountAppliedDiscount) },
	"shopping/discount.json#cart":                                                       func() validator { return new(shopping.DiscountCart) },
	"shopping/discount.json#checkout":                                                   func() validator { return new(shopping.DiscountCheckout) },
	"shopping/discount.json#discounts_object":                                           func() validator { return new(shopping.DiscountDiscountsObject) },
	"shopping/fulfillment.json#catalog_fulfillment":                                     func() validator { return new(shopping.FulfillmentCatalogFulfillment) },
	"shopping/fulfillment.json#catalog_fulfillment_method":                              func() validator { return new(shopping.FulfillmentCatalogFulfillmentMethod) },
	"shopping/fulfillment.json#checkout":                                                func() validator { return new(shopping.FulfillmentCheckout) },
	"shopping/fulfillment.json#fulfillment":                                             func() validator { return new(shopping.FulfillmentFulfillment) },
	"shopping/fulfillment.json#fulfillment_available_method":                            func() validator { return new(shopping.FulfillmentFulfillmentAvailableMethod) },
	"shopping/fulfillment.json#fulfillment_detail_product":                              func() validator { return new(shopping.FulfillmentFulfillmentDetailProduct) },
	"shopping/fulfillment.json#fulfillment_get_product_request":                         func() validator { return new(shopping.FulfillmentFulfillmentGetProductRequest) },
	"shopping/fulfillment.json#fulfillment_get_product_response":                        func() validator { return new(shopping.FulfillmentFulfillmentGetProductResponse) },
	"shopping/fulfillment.json#fulfillment_group":                                       func() validator { return new(shopping.FulfillmentFulfillmentGroup) },
	"shopping/fulfillment.json#fulfillment_lookup_product":                              func() validator { return new(shopping.FulfillmentFulfillmentLookupProduct) },
	"shopping/fulfillment.json#fulfillment_lookup_request":                              func() validator { return new(shopping.FulfillmentFulfillmentLookupRequest) },
	"shopping/fulfillment.json#fulfillment_lookup_response":                             func() validator { return new(shopping.FulfillmentFulfillmentLookupResponse) },
	"shopping/fulfillment.json#fulfillment_lookup_variant":                              func() validator { return new(shopping.FulfillmentFulfillmentLookupVariant) },
	"shopping/fulfillment.json#fulfillment_method":                                      func() validator { return new(shopping.FulfillmentFulfillmentMethod) },
	"shopping/fulfillment.json#fulfillment_option":                                      func() validator { return new(shopping.FulfillmentFulfillmentOption) },
	"shopping/fulfillment.json#fulfillment_product":                                     func() validator { return new(shopping.FulfillmentFulfillmentProduct) },
	"shopping/fulfillment.json#fulfillment_search_filters":                              func() validator { return new(shopping.FulfillmentFulfillmentSearchFilters) },
	"shopping/fulfillment.json#fulfillment_search_request":                              func() validator { return new(shopping.FulfillmentFulfillmentSearchRequest) },
	"shopping/fulfillment.json#fulfillment_search_response":                             func() validator { return new(shopping.FulfillmentFulfillmentSearchResponse) },
	"shopping/fulfillment.json#fulfillment_variant":                                     func() validator { return new(shopping.FulfillmentFulfillmentVariant) },
	"shopping/order.json":                                                               func() validator { return new(shopping.Order) },
	"shopping/order.json#platform_schema":                                               func() validator { return new(shopping.OrderPlatformSchema) },
	"shopping/order_create_request.json":                                                func() validator { return new(shopping.OrderCreateRequest) },
	"shopping/order_create_request.json#platform_schema":                                func() validator { return new(shopping.OrderCreateRequestPlatformSchema) },
	"shopping/order_update_request.json":                                                func() validator { return new(shopping.OrderUpdateRequest) },
	"shopping/order_update_request.json#platform_schema":                                func() validator { return new(shopping.OrderUpdateRequestPlatformSchema) },
	"shopping/permalink.json#config":                                                    func() validator { return new(shopping.PermalinkConfig) },
	"shopping/permalink.json#endpoint":                                                  func() validator { return new(shopping.PermalinkEndpoint) },
	"shopping/types/adjustment.json":                                                    func() validator { return new(shoppingtypes.Adjustment) },
	"shopping/types/adjustment_create_request.json":                                     func() validator { return new(shoppingtypes.AdjustmentCreateRequest) },
	"shopping/types/adjustment_update_request.json":                                     func() validator { return new(shoppingtypes.AdjustmentUpdateRequest) },
	"shopping/types/attribution.json":                                                   func() validator { return new(shoppingtypes.Attribution) },
	"shopping/types/attribution_complete_request.json":                                  func() validator { return new(shoppingtypes.AttributionCompleteRequest) },
	"shopping/types/attribution_create_request.json":                                    func() validator { return new(shoppingtypes.AttributionCreateRequest) },
	"shopping/types/attribution_update_request.json":                                    func() validator { return new(shoppingtypes.AttributionUpdateRequest) },
	"shopping/types/availability.json":                                                  func() validator { return new(shoppingtypes.Availability) },
	"shopping/types/business_fulfillment_config.json":                                   func() validator { return new(shoppingtypes.BusinessFulfillmentConfig) },
	"shopping/types/buyer.json":                                                         func() validator { return new(shoppingtypes.Buyer) },
	"shopping/types/buyer_create_request.json":                                          func() validator { return new(shoppingtypes.BuyerCreateRequest) },
	"shopping/types/buyer_update_request.json":                                          func() validator { return new(shoppingtypes.BuyerUpdateRequest) },
	"shopping/types/category.json":                                                      func() validator { return new(shoppingtypes.Category) },
	"shopping/types/detail_option_value.json":                                           func() validator { return new(shoppingtypes.DetailOptionValue) },
	"shopping/types/expectation.json":                                                   func() validator { return new(shoppingtypes.Expectation) },
	"shopping/types/expectation_create_request.json":                                    func() validator { return new(shoppingtypes.ExpectationCreateRequest) },
	"shopping/types/expectation_update_request.json":                                    func() validator { return new(shoppingtypes.ExpectationUpdateRequest) },
	"shopping/types/fulfillment.json":                                                   func() validator { return new(shoppingtypes.Fulfillment) },
	"shopping/types/fulfillment_available_method.json":                                  func() validator { return new(shoppingtypes.FulfillmentAvailableMethod) },
	"shopping/types/fulfillment_available_method_create_request.json":                   func() validator { return new(shoppingtypes.FulfillmentAvailableMethodCreateRequest) },
	"shopping/types/fulfillment_available_method_update_request.json":                   func() validator { return new(shoppingtypes.FulfillmentAvailableMethodUpdateRequest) },
	"shopping/types/fulfillment_create_request.json":                                    func() validator { return new(shoppingtypes.FulfillmentCreateRequest) },
	"shopping/types/fulfillment_destination.json":                                       func() validator { return new(shoppingtypes.FulfillmentDestination) },
	"shopping/types/fulfillment_destination_create_request.json":                        func() validator { return new(shoppingtypes.FulfillmentDestinationCreateRequest) },
	"shopping/types/fulfillment_destination_filter.json":                                func() validator { return new(shoppingtypes.FulfillmentDestinationFilter) },
	"shopping/types/fulfillment_destination_update_request.json":                        func() validator { return new(shoppingtypes.FulfillmentDestinationUpdateRequest) },
	"shopping/types/fulfillment_event.json":                                             func() validator { return new(shoppingtypes.FulfillmentEvent) },
	"shopping/types/fulfillment_event_create_request.json":                              func() validator { return new(shoppingtypes.FulfillmentEventCreateRequest) },
	"shopping/types/fulfillment_event_update_request.json":                              func() validator { return new(shoppingtypes.FulfillmentEventUpdateRequest) },
	"shopping/types/fulfillment_group.json":                                             func() validator { return new(shoppingtypes.FulfillmentGroup) },
	"shopping/types/fulfillment_group_create_request.json":                              func() validator { return new(shoppingtypes.FulfillmentGroupCreateRequest) },
	"shopping/types/fulfillment_group_update_request.json":                              func() validator { return new(shoppingtypes.FulfillmentGroupUpdateRequest) },
	"shopping/types/fulfillment_method.json":                                            func() validator { return new(shoppingtypes.FulfillmentMethod) },
	"shopping/types/fulfillment_method_create_request.json":                             func() validator { return new(shoppingtypes.FulfillmentMethodCreateRequest) },
	"shopping/types/fulfillment_method_update_request.json":                             func() validator { return new(shoppingtypes.FulfillmentMethodUpdateRequest) },
	"shopping/types/fulfillment_option.json":                                            func() validator { return new(shoppingtypes.FulfillmentOption) },
	"shopping/types/fulfillment_option_base.json":                                       func() validator { return new(shoppingtypes.FulfillmentOptionBase) },
	"shopping/types/fulfillment_option_base_create_request.json":                        func() validator { return new(shoppingtypes.FulfillmentOptionBaseCreateRequest) },
	"shopping/types/fulfillment_option_base_update_request.json":                        func() validator { return new(shoppingtypes.FulfillmentOptionBaseUpdateRequest) },
	"shopping/types/fulfillment_option_create_request.json":                             func() validator { return new(shoppingtypes.FulfillmentOptionCreateRequest) },
	"shopping/types/fulfillment_option_update_request.json":                             func() validator { return new(shoppingtypes.FulfillmentOptionUpdateRequest) },
	"shopping/types/fulfillment_update_request.json":                                    func() validator { return new(shoppingtypes.FulfillmentUpdateRequest) },
	"shopping/types/input_correlation.json":                                             func() validator { return new(shoppingtypes.InputCorrelation) },
	"shopping/types/item.json":                                                          func() validator { return new(shoppingtypes.Item) },
	"shopping/types/item_create_request.json":                                           func() validator { return new(shoppingtypes.ItemCreateRequest) },
	"shopping/types/item_update_request.json":                                           func() validator { return new(shoppingtypes.ItemUpdateRequest) },
	"shopping/types/line_item.json":                                                     func() validator { return new(shoppingtypes.LineItem) },
	"shopping/types/line_item_create_request.json":                                      func() validator { return new(shoppingtypes.LineItemCreateRequest) },
	"shopping/types/line_item_update_request.json":                                      func() validator { return new(shoppingtypes.LineItemUpdateRequest) },
	"shopping/types/location_destination.json":                                          func() validator { return new(shoppingtypes.BusinessLocationDestination) },
	"shopping/types/location_destination_create_request.json":                           func() validator { return new(shoppingtypes.BusinessLocationDestinationCreateRequest) },
	"shopping/types/location_destination_update_request.json":                           func() validator { return new(shoppingtypes.BusinessLocationDestinationUpdateRequest) },
	"shopping/types/option_value.json":                                                  func() validator { return new(shoppingtypes.OptionValue) },
	"shopping/types/order_confirmation.json":                                            func() validator { return new(shoppingtypes.OrderConfirmation) },
	"shopping/types/order_line_item.json":                                               func() validator { return new(shoppingtypes.OrderLineItem) },
	"shopping/types/order_line_item_create_request.json":                                func() validator { return new(shoppingtypes.OrderLineItemCreateRequest) },
	"shopping/types/order_line_item_update_request.json":                                func() validator { return new(shoppingtypes.OrderLineItemUpdateRequest) },
	"shopping/types/platform_fulfillment_config.json":                                   func() validator { return new(shoppingtypes.PlatformFulfillmentConfig) },
	"shopping/types/product.json":                                                       func() validator { return new(shoppingtypes.Product) },
	"shopping/types/product_option.json":                                                func() validator { return new(shoppingtypes.ProductOption) },
	"shopping/types/rating.json":                                                        func() validator { return new(shoppingtypes.Rating) },
	"shopping/types/search_filters.json":                                                func() validator { return new(shoppingtypes.SearchFilters) },
	"shopping/types/selected_option.json":                                               func() validator { return new(shoppingtypes.SelectedOption) },
	"shopping/types/shipping_destination.json":                                          func() validator { return new(shoppingtypes.ShippingDestination) },
	"shopping/types/shipping_destination_create_request.json":                           func() validator { return new(shoppingtypes.ShippingDestinationCreateRequest) },
	"shopping/types/shipping_destination_update_request.json":                           func() validator { return new(shoppingtypes.ShippingDestinationUpdateRequest) },
	"shopping/types/unit_price.json":                                                    func() validator { return new(shoppingtypes.UnitPrice) },
	"shopping/types/variant.json":                                                       func() validator { return new(shoppingtypes.Variant) },
	"transports/a2a_message.json":                                                       func() validator { return new(transports.A2AUCPMessageEnvelope) },
	"transports/a2a_message.json#agent_card":                                            func() validator { return new(transports.A2AMessageAgentCard) },
	"transports/a2a_message.json#extension":                                             func() validator { return new(transports.A2AMessageExtension) },
	"transports/a2a_message.json#message":                                               func() validator { return new(transports.A2AMessageMessage) },
	"transports/a2a_message.json#message_request":                                       func() validator { return new(transports.A2AMessageMessageRequest) },
	"transports/a2a_message.json#message_response":                                      func() validator { return new(transports.A2AMessageMessageResponse) },
	"transports/a2a_message.json#part":                                                  func() validator { return new(transports.A2AMessagePart) },
	"transports/embedded_config.json":                                                   func() validator { return new(transports.EmbeddedTransportConfig) },
	"transports/embedded_message.json":                                                  func() validator { return new(transports.EmbeddedProtocolMessageEnvelope) },
	"transports/embedded_message.json#error_response":                                   func() validator { return new(transports.EmbeddedMessageErrorResponse) },
	"transports/embedded_message.json#method":                                           func() validator { return new(transports.EmbeddedMessageMethod) },
	"transports/embedded_message.json#request":                                          func() validator { return new(transports.EmbeddedMessageRequest) },
	"transports/embedded_message.json#response":                                         func() validator { return new(transports.EmbeddedMessageResponse) },
	"transports/jsonrpc.json":                                                           func() validator { return new(transports.JSONRpc20Envelope) },
	"transports/jsonrpc.json#error":                                                     func() validator { return new(transports.JsonrpcError) },
	"transports/jsonrpc.json#error_response":                                            func() validator { return new(transports.JsonrpcErrorResponse) },
	"transports/jsonrpc.json#id":                                                        func() validator { return new(transports.JsonrpcID) },
	"transports/jsonrpc.json#request":                                                   func() validator { return new(transports.JsonrpcRequest) },
	"transports/jsonrpc.json#success_response":                                          func() validator { return new(transports.JsonrpcSuccessResponse) },
	"transports/mcp_tool_call.json":                                                     func() validator { return new(transports.MCPToolCallEnvelope) },
	"transports/mcp_tool_call.json#arguments":                                           func() validator { return new(transports.MCPToolCallArguments) },
	"transports/mcp_tool_call.json#content_part":                                        func() validator { return new(transports.MCPToolCallContentPart) },
	"transports/mcp_tool_call.json#meta":                                                func() validator { return new(transports.MCPToolCallMeta) },
	"transports/mcp_tool_call.json#request":                                             func() validator { return new(transports.MCPToolCallRequest) },
	"transports/mcp_tool_call.json#response":                                            func() validator { return new(transports.MCPToolCallResponse) },
	"transports/mcp_tool_call.json#ucp_agent":                                           func() validator { return new(transports.MCPToolCallUCPAgent) },
	"ucp.json":                                         func() validator { return new(ucp.UCPMetadata) },
	"ucp.json#base":                                    func() validator { return new(ucp.UCPBase) },
	"ucp.json#business_schema":                         func() validator { return new(ucp.UCPBusinessSchema) },
	"ucp.json#entity":                                  func() validator { return new(ucp.UCPEntity) },
	"ucp.json#error":                                   func() validator { return new(ucp.UCPError) },
	"ucp.json#map_order":                               func() validator { return new(ucp.UCPMapOrder) },
	"ucp.json#members":                                 func() validator { return new(ucp.UCPMembers) },
	"ucp.json#platform_schema":                         func() validator { return new(ucp.UCPPlatformSchema) },
	"ucp.json#requires":                                func() validator { return new(ucp.UCPRequires) },
	"ucp.json#response_cart_schema":                    func() validator { return new(ucp.UCPResponseCartSchema) },
	"ucp.json#response_catalog_schema":                 func() validator { return new(ucp.UCPResponseCatalogSchema) },
	"ucp.json#response_checkout_schema":                func() validator { return new(ucp.UCPResponseCheckoutSchema) },
	"ucp.json#response_location_schema":                func() validator { return new(ucp.UCPResponseLocationSchema) },
	"ucp.json#response_order_schema":                   func() validator { return new(ucp.UCPResponseOrderSchema) },
	"ucp.json#success":                                 func() validator { return new(ucp.UCPSuccess) },
	"ucp.json#version":                                 func() validator { return new(ucp.UCPVersion) },
	"ucp.json#version_constraint":                      func() validator { return new(ucp.UCPVersionConstraint) },
	"ucp_create_request.json":                          func() validator { return new(ucp.UCPMetadataCreateRequest) },
	"ucp_create_request.json#base":                     func() validator { return new(ucp.UCPCreateRequestBase) },
	"ucp_create_request.json#business_schema":          func() validator { return new(ucp.UCPCreateRequestBusinessSchema) },
	"ucp_create_request.json#entity":                   func() validator { return new(ucp.UCPCreateRequestEntity) },
	"ucp_create_request.json#error":                    func() validator { return new(ucp.UCPCreateRequestError) },
	"ucp_create_request.json#map_order":                func() validator { return new(ucp.UCPCreateRequestMapOrder) },
	"ucp_create_request.json#members":                  func() validator { return new(ucp.UCPCreateRequestMembers) },
	"ucp_create_request.json#platform_schema":          func() validator { return new(ucp.UCPCreateRequestPlatformSchema) },
	"ucp_create_request.json#requires":                 func() validator { return new(ucp.UCPCreateRequestRequires) },
	"ucp_create_request.json#response_cart_schema":     func() validator { return new(ucp.UCPCreateRequestResponseCartSchema) },
	"ucp_create_request.json#response_catalog_schema":  func() validator { return new(ucp.UCPCreateRequestResponseCatalogSchema) },
	"ucp_create_request.json#response_checkout_schema": func() validator { return new(ucp.UCPCreateRequestResponseCheckoutSchema) },
	"ucp_create_request.json#response_location_schema": func() validator { return new(ucp.UCPCreateRequestResponseLocationSchema) },
	"ucp_create_request.json#response_order_schema":    func() validator { return new(ucp.UCPCreateRequestResponseOrderSchema) },
	"ucp_create_request.json#success":                  func() validator { return new(ucp.UCPCreateRequestSuccess) },
	"ucp_create_request.json#version":                  func() validator { return new(ucp.UCPCreateRequestVersion) },
	"ucp_create_request.json#version_constraint":       func() validator { return new(ucp.UCPCreateRequestVersionConstraint) },
	"ucp_update_request.json":                          func() validator { return new(ucp.UCPMetadataUpdateRequest) },
	"ucp_update_request.json#base":                     func() validator { return new(ucp.UCPUpdateRequestBase) },
	"ucp_update_request.json#business_schema":          func() validator { return new(ucp.UCPUpdateRequestBusinessSchema) },
	"ucp_update_request.json#entity":                   func() validator { return new(ucp.UCPUpdateRequestEntity) },
	"ucp_update_request.json#error":                    func() validator { return new(ucp.UCPUpdateRequestError) },
	"ucp_update_request.json#map_order":                func() validator { return new(ucp.UCPUpdateRequestMapOrder) },
	"ucp_update_request.json#members":                  func() validator { return new(ucp.UCPUpdateRequestMembers) },
	"ucp_update_request.json#platform_schema":          func() validator { return new(ucp.UCPUpdateRequestPlatformSchema) },
	"ucp_update_request.json#requires":                 func() validator { return new(ucp.UCPUpdateRequestRequires) },
	"ucp_update_request.json#response_cart_schema":     func() validator { return new(ucp.UCPUpdateRequestResponseCartSchema) },
	"ucp_update_request.json#response_catalog_schema":  func() validator { return new(ucp.UCPUpdateRequestResponseCatalogSchema) },
	"ucp_update_request.json#response_checkout_schema": func() validator { return new(ucp.UCPUpdateRequestResponseCheckoutSchema) },
	"ucp_update_request.json#response_location_schema": func() validator { return new(ucp.UCPUpdateRequestResponseLocationSchema) },
	"ucp_update_request.json#response_order_schema":    func() validator { return new(ucp.UCPUpdateRequestResponseOrderSchema) },
	"ucp_update_request.json#success":                  func() validator { return new(ucp.UCPUpdateRequestSuccess) },
	"ucp_update_request.json#version":                  func() validator { return new(ucp.UCPUpdateRequestVersion) },
	"ucp_update_request.json#version_constraint":       func() validator { return new(ucp.UCPUpdateRequestVersionConstraint) },
}

// TestModelsCoverCorpus keeps the table honest. Without it a schema added
// upstream would simply be skipped by the differential harness, quietly
// shrinking coverage.
func TestModelsCoverCorpus(t *testing.T) {
	set := loadGoldens(t)
	idx := buildIndex(t, set)
	var missing []string
	for _, rel := range sortedKeys(set) {
		if _, ok := idx.Lookup(rel, ""); !ok {
			continue // no file-level type, nothing to construct
		}
		if _, ok := models[rel]; !ok {
			missing = append(missing, rel)
		}
	}
	if len(missing) > 0 {
		t.Errorf("models is missing %d schemas that emit a file-level type: %v", len(missing), missing)
	}
}

// TestModelsCoverDefs is the same guarantee for $defs-derived types, and it
// exists because iterating schema files was never the same thing as
// iterating emitted types. Eight files put all their content in $defs and so
// have no file-level type; the harness looked them up by file, missed, and
// skipped them whole, taking 34 emitted types — the entire capability model
// among them — out of the comparison without ever naming them as a gap.
//
// A $def with no emitted type is not a failure here. The two grouping
// objects in the corpus, identity_linking and dev_ucp_shopping_fulfillment,
// are namespaces whose values are themselves schemas; the emitter produces
// nothing for them by design, so there is nothing to register.
func TestModelsCoverDefs(t *testing.T) {
	set := loadGoldens(t)
	idx := buildIndex(t, set)
	var missing []string
	for _, rel := range sortedKeys(set) {
		defs, _ := set[rel]["$defs"].(map[string]any)
		names := make([]string, 0, len(defs))
		for name := range defs {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			if _, ok := idx.Lookup(rel, name); !ok {
				continue // a grouping object, no type emitted
			}
			if _, ok := models[rel+"#"+name]; !ok {
				missing = append(missing, rel+"#"+name)
			}
		}
	}
	if len(missing) > 0 {
		t.Errorf("models is missing %d $defs types: %v", len(missing), missing)
	}
}
