// Code generated by ucpgen. DO NOT EDIT.
// Source: common/identity_linking.json (spec release/2026-04-08@a2d8bf0)

package common

import (
	"encoding/json"
	"errors"
	"github.com/chaz8081/ucp-go/shopping/types"
	"regexp"
	"sync"
)

// $defs/identity_linking is an extension mount point (a namespace of schemas,
// not a schema); no type is emitted for it.

// IdentityLinkingScopePolicy Per-scope policy and metadata — auth constraints (e.g. min_acr, max_token_age), declarative metadata (e.g. claims produced, consent descriptions), or any other scope-specific configuration. An empty object means user authentication is required with no additional policy. Open for non-breaking extension.
type IdentityLinkingScopePolicy struct {
	// Optional human-readable description of the scope that platforms can use to present and explain context (requirement and value) to the user.
	Description *types.Description `json:"description,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *IdentityLinkingScopePolicy) UnmarshalJSON(data []byte) error {
	type IdentityLinkingScopePolicyAlias IdentityLinkingScopePolicy
	var named IdentityLinkingScopePolicyAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = IdentityLinkingScopePolicy(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "description")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v IdentityLinkingScopePolicy) MarshalJSON() ([]byte, error) {
	type IdentityLinkingScopePolicyAlias IdentityLinkingScopePolicy
	named, err := json.Marshal(IdentityLinkingScopePolicyAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *IdentityLinkingScopePolicy) Validate() error {
	if v.Description != nil {
		if err := v.Description.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// IdentityLinkingScopeToken OAuth scope string formed by joining a capability name and a scope name with a colon: '{capability}:{scope}', e.g. 'dev.ucp.shopping.order:read'. Capability names use reverse-DNS naming; scope names denote the permission granted, defined by each capability's spec (e.g. 'read', 'manage', 'create'). Platforms request these strings verbatim in OAuth 'scope' parameters; issued tokens carry them in the 'scope' claim.
type IdentityLinkingScopeToken string

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *IdentityLinkingScopeToken) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("IdentityLinkingScopeToken: null is not a valid string")
	}
	type IdentityLinkingScopeTokenAlias IdentityLinkingScopeToken
	var alias IdentityLinkingScopeTokenAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = IdentityLinkingScopeToken(alias)
	return nil
}

var pattern_IdentityLinkingScopeToken = sync.OnceValue(func() *regexp.Regexp {
	return regexp.MustCompile("^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+:[a-z][a-z0-9_]*$")
})

// Validate reports the first constraint violation, or nil.
func (v *IdentityLinkingScopeToken) Validate() error {
	if !pattern_IdentityLinkingScopeToken().MatchString(string(*v)) {
		return errors.New("IdentityLinkingScopeToken: does not match pattern")
	}
	return nil
}
