// Code generated by ucpgen. DO NOT EDIT.
// Source: common/location_search.json (spec release/2026-08-25@cd78fb3)

package common

import (
	"encoding/json"
	"errors"
	ucp "github.com/chaz8081/ucp-go"
	"github.com/chaz8081/ucp-go/common/types"
)

// LocationSearch Location search capability. Supports natural language queries, distance and serviceability relations, structured filtering including current item availability, and pagination.
type LocationSearch map[string]any

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *LocationSearch) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("LocationSearch: null is not a valid object")
	}
	type LocationSearchAlias LocationSearch
	var alias LocationSearchAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = LocationSearch(alias)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *LocationSearch) Validate() error {
	return nil
}

// LocationSearchSearchRequest Request body for location search. The `distance` and `serves` relations and every supplied `filters` predicate combine with AND; `query` does not relax them.
type LocationSearchSearchRequest struct {
	Context *types.Context `json:"context,omitzero"`
	// Optional explicit-center radius predicate. When present, it combines with `serves` and every supplied `filters` predicate using AND.
	Distance   *types.LocationDistance  `json:"distance,omitzero"`
	Filters    *types.LocationFilter    `json:"filters,omitzero"`
	Pagination *types.PaginationRequest `json:"pagination,omitzero"`
	// Free-text search query for natural language location search (e.g., 'restaurants near me that deliver', 'hotels with pool').
	Query *string `json:"query,omitzero"`
	// Optional authoritative service-target predicate. When present, it combines with `distance` and every supplied `filters` predicate using AND.
	Serves  *types.LocationServes `json:"serves,omitzero"`
	Signals *types.Signals        `json:"signals,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *LocationSearchSearchRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("LocationSearchSearchRequest: null is not a valid object")
	}
	type LocationSearchSearchRequestAlias LocationSearchSearchRequest
	var named LocationSearchSearchRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = LocationSearchSearchRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "context")
	delete(all, "distance")
	delete(all, "filters")
	delete(all, "pagination")
	delete(all, "query")
	delete(all, "serves")
	delete(all, "signals")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v LocationSearchSearchRequest) MarshalJSON() ([]byte, error) {
	type LocationSearchSearchRequestAlias LocationSearchSearchRequest
	named, err := json.Marshal(LocationSearchSearchRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *LocationSearchSearchRequest) Validate() error {
	if v.Context != nil {
		if err := v.Context.Validate(); err != nil {
			return err
		}
	}
	if v.Distance != nil {
		if err := v.Distance.Validate(); err != nil {
			return err
		}
	}
	if v.Filters != nil {
		if err := v.Filters.Validate(); err != nil {
			return err
		}
	}
	if v.Pagination != nil {
		if err := v.Pagination.Validate(); err != nil {
			return err
		}
	}
	if v.Serves != nil {
		if err := v.Serves.Validate(); err != nil {
			return err
		}
	}
	if v.Signals != nil {
		if err := v.Signals.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// LocationSearchSearchResponse is generated from common/location_search.json.
type LocationSearchSearchResponse struct {
	// Locations matching the search criteria.
	Locations []types.Location `json:"locations"`
	// Errors, warnings, or informational messages about the search results.
	Messages   []types.Message               `json:"messages,omitzero"`
	Pagination *types.PaginationResponse     `json:"pagination,omitzero"`
	UCP        ucp.UCPResponseLocationSchema `json:"ucp"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *LocationSearchSearchResponse) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("LocationSearchSearchResponse: null is not a valid object")
	}
	type LocationSearchSearchResponseAlias LocationSearchSearchResponse
	var named LocationSearchSearchResponseAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = LocationSearchSearchResponse(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"locations", "ucp"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "locations")
	delete(all, "messages")
	delete(all, "pagination")
	delete(all, "ucp")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v LocationSearchSearchResponse) MarshalJSON() ([]byte, error) {
	type LocationSearchSearchResponseAlias LocationSearchSearchResponse
	named, err := json.Marshal(LocationSearchSearchResponseAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *LocationSearchSearchResponse) Validate() error {
	if v.present != nil {
		if !v.present["locations"] {
			return errors.New("locations: required property is missing")
		}
		if !v.present["ucp"] {
			return errors.New("ucp: required property is missing")
		}
	}
	for i := range v.Locations {
		if err := v.Locations[i].Validate(); err != nil {
			return err
		}
	}
	for i := range v.Messages {
		if err := v.Messages[i].Validate(); err != nil {
			return err
		}
	}
	if v.Pagination != nil {
		if err := v.Pagination.Validate(); err != nil {
			return err
		}
	}
	if err := v.UCP.Validate(); err != nil {
		return err
	}
	return nil
}
