// Code generated by ucpgen. DO NOT EDIT.
// Source: common/location_lookup.json (spec release/2026-08-25@cd78fb3)

package common

import (
	"encoding/json"
	"errors"
	ucp "github.com/chaz8081/ucp-go"
	"github.com/chaz8081/ucp-go/common/types"
)

// LocationLookup Location lookup by identifiers. Supports batch retrieval and single-location detail.
type LocationLookup map[string]any

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *LocationLookup) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("LocationLookup: null is not a valid object")
	}
	type LocationLookupAlias LocationLookup
	var alias LocationLookupAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = LocationLookup(alias)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *LocationLookup) Validate() error {
	return nil
}

// LocationLookupLookupLocation Location with required correlation metadata for lookup responses.
//
// Not enforced yet on the object itself: if, then.
type LocationLookupLookupLocation struct {
	// Which request identifiers resolved to this Location. Each entry preserves one identifier exactly as supplied in the request.
	Inputs []LocationLookupLookupLocationInputsItem `json:"inputs"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *LocationLookupLookupLocation) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("LocationLookupLookupLocation: null is not a valid object")
	}
	type LocationLookupLookupLocationAlias LocationLookupLookupLocation
	var named LocationLookupLookupLocationAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = LocationLookupLookupLocation(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"inputs"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "inputs")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v LocationLookupLookupLocation) MarshalJSON() ([]byte, error) {
	type LocationLookupLookupLocationAlias LocationLookupLookupLocation
	named, err := json.Marshal(LocationLookupLookupLocationAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *LocationLookupLookupLocation) Validate() error {
	if v.present != nil {
		if !v.present["inputs"] {
			return errors.New("inputs: required property is missing")
		}
	}
	if len(v.Inputs) < 1 {
		return errors.New("inputs: has fewer than minItems 1")
	}
	for i := range v.Inputs {
		if err := v.Inputs[i].Validate(); err != nil {
			return err
		}
	}
	return nil
}

// LocationLookupLookupRequest Request body for batch location lookup. The Business resolves and deduplicates `ids` before applying `distance`, `serves`, and every supplied `filters` predicate; all structured predicates combine with AND.
type LocationLookupLookupRequest struct {
	Context *types.Context `json:"context,omitzero"`
	// Optional explicit-center radius predicate applied after ID resolution. It combines with `serves` and every supplied `filters` predicate using AND.
	Distance *types.LocationDistance `json:"distance,omitzero"`
	Filters  *types.LocationFilter   `json:"filters,omitzero"`
	// Identifiers of the Locations to look up. The Business MUST support canonical `Location.id` values and MAY support secondary or alias identifiers.
	Ids []string `json:"ids"`
	// Optional authoritative service-target predicate applied after ID resolution. It combines with `distance` and every supplied `filters` predicate using AND.
	Serves  *types.LocationServes `json:"serves,omitzero"`
	Signals *types.Signals        `json:"signals,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *LocationLookupLookupRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("LocationLookupLookupRequest: null is not a valid object")
	}
	type LocationLookupLookupRequestAlias LocationLookupLookupRequest
	var named LocationLookupLookupRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = LocationLookupLookupRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"ids"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "context")
	delete(all, "distance")
	delete(all, "filters")
	delete(all, "ids")
	delete(all, "serves")
	delete(all, "signals")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v LocationLookupLookupRequest) MarshalJSON() ([]byte, error) {
	type LocationLookupLookupRequestAlias LocationLookupLookupRequest
	named, err := json.Marshal(LocationLookupLookupRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *LocationLookupLookupRequest) Validate() error {
	if v.present != nil {
		if !v.present["ids"] {
			return errors.New("ids: required property is missing")
		}
	}
	if len(v.Ids) < 1 {
		return errors.New("ids: has fewer than minItems 1")
	}
	if v.Context != nil {
		if err := v.Context.Validate(); err != nil {
			return err
		}
	}
	if v.Distance != nil {
		if err := v.Distance.Validate(); err != nil {
			return err
		}
	}
	if v.Filters != nil {
		if err := v.Filters.Validate(); err != nil {
			return err
		}
	}
	if v.Serves != nil {
		if err := v.Serves.Validate(); err != nil {
			return err
		}
	}
	if v.Signals != nil {
		if err := v.Signals.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// LocationLookupLookupResponse is generated from common/location_lookup.json.
type LocationLookupLookupResponse struct {
	// Locations matching the requested identifiers and refinements. May contain fewer Locations if some identifiers do not resolve or their resolved Locations are filtered out, or more if one identifier resolves to multiple Locations. When multiple identifiers resolve to the same Location, one returned Location carries all corresponding `inputs` entries.
	Locations []LocationLookupLookupLocation `json:"locations"`
	// Errors, warnings, or informational messages about the requested Locations, including `batch_limit_applied` when the Business processes only its configured maximum number of identifiers.
	Messages []types.Message               `json:"messages,omitzero"`
	UCP      ucp.UCPResponseLocationSchema `json:"ucp"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *LocationLookupLookupResponse) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("LocationLookupLookupResponse: null is not a valid object")
	}
	type LocationLookupLookupResponseAlias LocationLookupLookupResponse
	var named LocationLookupLookupResponseAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = LocationLookupLookupResponse(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"locations", "ucp"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "locations")
	delete(all, "messages")
	delete(all, "ucp")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v LocationLookupLookupResponse) MarshalJSON() ([]byte, error) {
	type LocationLookupLookupResponseAlias LocationLookupLookupResponse
	named, err := json.Marshal(LocationLookupLookupResponseAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *LocationLookupLookupResponse) Validate() error {
	if v.present != nil {
		if !v.present["locations"] {
			return errors.New("locations: required property is missing")
		}
		if !v.present["ucp"] {
			return errors.New("ucp: required property is missing")
		}
	}
	for i := range v.Locations {
		if err := v.Locations[i].Validate(); err != nil {
			return err
		}
	}
	for i := range v.Messages {
		if err := v.Messages[i].Validate(); err != nil {
			return err
		}
	}
	if err := v.UCP.Validate(); err != nil {
		return err
	}
	return nil
}

// LocationLookupLookupLocationInputsItem is generated from common/location_lookup.json.
type LocationLookupLookupLocationInputsItem struct {
	// The identifier exactly as supplied in the lookup request.
	ID string `json:"id"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *LocationLookupLookupLocationInputsItem) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("LocationLookupLookupLocationInputsItem: null is not a valid object")
	}
	type LocationLookupLookupLocationInputsItemAlias LocationLookupLookupLocationInputsItem
	var named LocationLookupLookupLocationInputsItemAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = LocationLookupLookupLocationInputsItem(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"id"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "id")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v LocationLookupLookupLocationInputsItem) MarshalJSON() ([]byte, error) {
	type LocationLookupLookupLocationInputsItemAlias LocationLookupLookupLocationInputsItem
	named, err := json.Marshal(LocationLookupLookupLocationInputsItemAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *LocationLookupLookupLocationInputsItem) Validate() error {
	if v.present != nil {
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
	}
	return nil
}
