// Code generated by ucpgen. DO NOT EDIT.
// Source: common/payment_ap2_mandate.json (spec release/2026-08-25@cd78fb3)

package common

import (
	"encoding/json"
	"errors"
	ucp "github.com/chaz8081/ucp-go"
	"github.com/chaz8081/ucp-go/common/types"
	shoppingtypes "github.com/chaz8081/ucp-go/shopping/types"
	"regexp"
	"sync"
)

// PaymentAP2MandateAP2WithCheckoutMandate AP2 extension data including checkout mandate.
type PaymentAP2MandateAP2WithCheckoutMandate struct {
	// SD-JWT+kb proving user authorized this checkout.
	CheckoutMandate *PaymentAP2MandateCheckoutMandate `json:"checkout_mandate,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *PaymentAP2MandateAP2WithCheckoutMandate) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("PaymentAP2MandateAP2WithCheckoutMandate: null is not a valid object")
	}
	type PaymentAP2MandateAP2WithCheckoutMandateAlias PaymentAP2MandateAP2WithCheckoutMandate
	var named PaymentAP2MandateAP2WithCheckoutMandateAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = PaymentAP2MandateAP2WithCheckoutMandate(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "checkout_mandate")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v PaymentAP2MandateAP2WithCheckoutMandate) MarshalJSON() ([]byte, error) {
	type PaymentAP2MandateAP2WithCheckoutMandateAlias PaymentAP2MandateAP2WithCheckoutMandate
	named, err := json.Marshal(PaymentAP2MandateAP2WithCheckoutMandateAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *PaymentAP2MandateAP2WithCheckoutMandate) Validate() error {
	if v.CheckoutMandate != nil {
		if err := v.CheckoutMandate.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// PaymentAP2MandateAP2WithMerchantAuthorization AP2 extension data including merchant authorization.
type PaymentAP2MandateAP2WithMerchantAuthorization struct {
	// Merchant's signature proving checkout terms are authentic.
	MerchantAuthorization *PaymentAP2MandateMerchantAuthorization `json:"merchant_authorization,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *PaymentAP2MandateAP2WithMerchantAuthorization) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("PaymentAP2MandateAP2WithMerchantAuthorization: null is not a valid object")
	}
	type PaymentAP2MandateAP2WithMerchantAuthorizationAlias PaymentAP2MandateAP2WithMerchantAuthorization
	var named PaymentAP2MandateAP2WithMerchantAuthorizationAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = PaymentAP2MandateAP2WithMerchantAuthorization(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "merchant_authorization")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v PaymentAP2MandateAP2WithMerchantAuthorization) MarshalJSON() ([]byte, error) {
	type PaymentAP2MandateAP2WithMerchantAuthorizationAlias PaymentAP2MandateAP2WithMerchantAuthorization
	named, err := json.Marshal(PaymentAP2MandateAP2WithMerchantAuthorizationAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *PaymentAP2MandateAP2WithMerchantAuthorization) Validate() error {
	if v.MerchantAuthorization != nil {
		if err := v.MerchantAuthorization.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// PaymentAP2MandateCheckout Checkout extended with AP2 mandate support.
type PaymentAP2MandateCheckout struct {
	// Outstanding extension-defined Actions for this checkout.
	Actions *types.Actions `json:"actions,omitzero"`
	// AP2 extension data including merchant authorization.
	AP2         *PaymentAP2MandateCheckoutAP2 `json:"ap2,omitzero"`
	Attribution *shoppingtypes.Attribution    `json:"attribution,omitzero"`
	// Representation of the buyer.
	Buyer   *shoppingtypes.Buyer `json:"buyer,omitzero"`
	Context *types.Context       `json:"context,omitzero"`
	// URL for checkout handoff and session recovery. MUST be provided when status is requires_escalation. See specification for format and availability requirements.
	//
	// Annotation only in draft 2020-12, so not asserted: format.
	ContinueURL *string `json:"continue_url,omitzero"`
	// ISO 4217 currency code reflecting the merchant's market determination. Derived from address, context, and geo IP—buyers provide signals, merchants determine currency.
	Currency string `json:"currency"`
	// RFC 3339 expiry timestamp. Default TTL is 6 hours from creation if not sent.
	//
	// Annotation only in draft 2020-12, so not asserted: format.
	ExpiresAt *string `json:"expires_at,omitzero"`
	// Unique identifier of the checkout session.
	ID string `json:"id"`
	// List of line items being checked out.
	LineItems []shoppingtypes.LineItem `json:"line_items"`
	// Links to be displayed by the platform (Privacy Policy, TOS). Mandatory for legal compliance.
	Links []types.Link `json:"links"`
	// List of messages with error and info about the checkout session state.
	Messages []types.Message `json:"messages,omitzero"`
	// Details about an order created for this checkout session.
	Order   *shoppingtypes.OrderConfirmation `json:"order,omitzero"`
	Payment *types.Payment                   `json:"payment,omitzero"`
	// Policies (e.g., return/refund terms) that apply to the items in this checkout. `applies_to` targets are relative to the response root; when absent or empty, refer to the URLs in `links[]`.
	Policies []types.Policy `json:"policies,omitzero"`
	Signals  *types.Signals `json:"signals,omitzero"`
	// Checkout state indicating the current phase and required processing. See Checkout Status lifecycle documentation for state transition details.
	Status string `json:"status"`
	// Different cart totals.
	Totals types.Totals    `json:"totals"`
	UCP    ucp.UCPMetadata `json:"ucp"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *PaymentAP2MandateCheckout) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("PaymentAP2MandateCheckout: null is not a valid object")
	}
	type PaymentAP2MandateCheckoutAlias PaymentAP2MandateCheckout
	var named PaymentAP2MandateCheckoutAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = PaymentAP2MandateCheckout(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 7)
	for _, name := range []string{"currency", "id", "line_items", "links", "status", "totals", "ucp"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "actions")
	delete(all, "ap2")
	delete(all, "attribution")
	delete(all, "buyer")
	delete(all, "context")
	delete(all, "continue_url")
	delete(all, "currency")
	delete(all, "expires_at")
	delete(all, "id")
	delete(all, "line_items")
	delete(all, "links")
	delete(all, "messages")
	delete(all, "order")
	delete(all, "payment")
	delete(all, "policies")
	delete(all, "signals")
	delete(all, "status")
	delete(all, "totals")
	delete(all, "ucp")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v PaymentAP2MandateCheckout) MarshalJSON() ([]byte, error) {
	type PaymentAP2MandateCheckoutAlias PaymentAP2MandateCheckout
	named, err := json.Marshal(PaymentAP2MandateCheckoutAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *PaymentAP2MandateCheckout) Validate() error {
	if v.present != nil {
		if !v.present["currency"] {
			return errors.New("currency: required property is missing")
		}
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
		if !v.present["line_items"] {
			return errors.New("line_items: required property is missing")
		}
		if !v.present["links"] {
			return errors.New("links: required property is missing")
		}
		if !v.present["status"] {
			return errors.New("status: required property is missing")
		}
		if !v.present["totals"] {
			return errors.New("totals: required property is missing")
		}
		if !v.present["ucp"] {
			return errors.New("ucp: required property is missing")
		}
	}
	if v.Status != "incomplete" && v.Status != "requires_escalation" && v.Status != "ready_for_complete" && v.Status != "complete_in_progress" && v.Status != "completed" && v.Status != "canceled" {
		return errors.New("status: not one of the permitted values")
	}
	if v.Actions != nil {
		if err := v.Actions.Validate(); err != nil {
			return err
		}
	}
	if v.AP2 != nil {
		if err := v.AP2.Validate(); err != nil {
			return err
		}
	}
	if v.Attribution != nil {
		if err := v.Attribution.Validate(); err != nil {
			return err
		}
	}
	if v.Buyer != nil {
		if err := v.Buyer.Validate(); err != nil {
			return err
		}
	}
	if v.Context != nil {
		if err := v.Context.Validate(); err != nil {
			return err
		}
	}
	for i := range v.LineItems {
		if err := v.LineItems[i].Validate(); err != nil {
			return err
		}
	}
	for i := range v.Links {
		if err := v.Links[i].Validate(); err != nil {
			return err
		}
	}
	for i := range v.Messages {
		if err := v.Messages[i].Validate(); err != nil {
			return err
		}
	}
	if v.Order != nil {
		if err := v.Order.Validate(); err != nil {
			return err
		}
	}
	if v.Payment != nil {
		if err := v.Payment.Validate(); err != nil {
			return err
		}
	}
	for i := range v.Policies {
		if err := v.Policies[i].Validate(); err != nil {
			return err
		}
	}
	if v.Signals != nil {
		if err := v.Signals.Validate(); err != nil {
			return err
		}
	}
	if err := v.Totals.Validate(); err != nil {
		return err
	}
	if err := v.UCP.Validate(); err != nil {
		return err
	}
	return nil
}

// PaymentAP2MandateCheckoutMandate SD-JWT+kb credential in `ap2.checkout_mandate`. Proving user authorization for the checkout. Contains the full checkout including `ap2.merchant_authorization`.
type PaymentAP2MandateCheckoutMandate string

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *PaymentAP2MandateCheckoutMandate) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("PaymentAP2MandateCheckoutMandate: null is not a valid string")
	}
	type PaymentAP2MandateCheckoutMandateAlias PaymentAP2MandateCheckoutMandate
	var alias PaymentAP2MandateCheckoutMandateAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = PaymentAP2MandateCheckoutMandate(alias)
	return nil
}

var pattern_PaymentAP2MandateCheckoutMandate = sync.OnceValue(func() *regexp.Regexp {
	return regexp.MustCompile("^[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]*\\.[A-Za-z0-9_-]+(~[A-Za-z0-9_-]+)*$")
})

// Validate reports the first constraint violation, or nil.
func (v *PaymentAP2MandateCheckoutMandate) Validate() error {
	if !pattern_PaymentAP2MandateCheckoutMandate().MatchString(string(string(*v))) {
		return errors.New("PaymentAP2MandateCheckoutMandate: does not match pattern")
	}
	return nil
}

// PaymentAP2MandateErrorCode Error codes specific to AP2 mandate verification.
type PaymentAP2MandateErrorCode string

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *PaymentAP2MandateErrorCode) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("PaymentAP2MandateErrorCode: null is not a valid string")
	}
	type PaymentAP2MandateErrorCodeAlias PaymentAP2MandateErrorCode
	var alias PaymentAP2MandateErrorCodeAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = PaymentAP2MandateErrorCode(alias)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *PaymentAP2MandateErrorCode) Validate() error {
	if string(*v) != "mandate_required" && string(*v) != "agent_missing_key" && string(*v) != "mandate_invalid_signature" && string(*v) != "mandate_expired" && string(*v) != "mandate_scope_mismatch" && string(*v) != "merchant_authorization_invalid" && string(*v) != "merchant_authorization_missing" {
		return errors.New("PaymentAP2MandateErrorCode: not one of the permitted values")
	}
	return nil
}

// PaymentAP2MandateMerchantAuthorization JWS Detached Content signature (RFC 7515 Appendix F) over the checkout response body (excluding ap2 field). Format: `<base64url-header>..<base64url-signature>`. The header MUST contain 'alg' (ES256/ES384/ES512) and 'kid' claims. The signature covers both the header and JCS-canonicalized checkout payload.
type PaymentAP2MandateMerchantAuthorization string

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *PaymentAP2MandateMerchantAuthorization) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("PaymentAP2MandateMerchantAuthorization: null is not a valid string")
	}
	type PaymentAP2MandateMerchantAuthorizationAlias PaymentAP2MandateMerchantAuthorization
	var alias PaymentAP2MandateMerchantAuthorizationAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = PaymentAP2MandateMerchantAuthorization(alias)
	return nil
}

var pattern_PaymentAP2MandateMerchantAuthorization = sync.OnceValue(func() *regexp.Regexp { return regexp.MustCompile("^[A-Za-z0-9_-]+\\.\\.[A-Za-z0-9_-]+$") })

// Validate reports the first constraint violation, or nil.
func (v *PaymentAP2MandateMerchantAuthorization) Validate() error {
	if !pattern_PaymentAP2MandateMerchantAuthorization().MatchString(string(string(*v))) {
		return errors.New("PaymentAP2MandateMerchantAuthorization: does not match pattern")
	}
	return nil
}

// PaymentAP2MandateCheckoutAP2 AP2 extension data including merchant authorization.
type PaymentAP2MandateCheckoutAP2 struct {
	// SD-JWT+kb proving user authorized this checkout.
	CheckoutMandate *PaymentAP2MandateCheckoutMandate `json:"checkout_mandate,omitzero"`
	// Merchant's signature proving checkout terms are authentic.
	MerchantAuthorization *PaymentAP2MandateMerchantAuthorization `json:"merchant_authorization,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *PaymentAP2MandateCheckoutAP2) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("PaymentAP2MandateCheckoutAP2: null is not a valid object")
	}
	type PaymentAP2MandateCheckoutAP2Alias PaymentAP2MandateCheckoutAP2
	var named PaymentAP2MandateCheckoutAP2Alias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = PaymentAP2MandateCheckoutAP2(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "checkout_mandate")
	delete(all, "merchant_authorization")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v PaymentAP2MandateCheckoutAP2) MarshalJSON() ([]byte, error) {
	type PaymentAP2MandateCheckoutAP2Alias PaymentAP2MandateCheckoutAP2
	named, err := json.Marshal(PaymentAP2MandateCheckoutAP2Alias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *PaymentAP2MandateCheckoutAP2) Validate() error {
	if v.CheckoutMandate != nil {
		if err := v.CheckoutMandate.Validate(); err != nil {
			return err
		}
	}
	if v.MerchantAuthorization != nil {
		if err := v.MerchantAuthorization.Validate(); err != nil {
			return err
		}
	}
	return nil
}
