// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/buyer_consent.json (spec release/2026-04-08@a2d8bf0)

package shopping

import (
	"encoding/json"
	"errors"
	"github.com/chaz8081/ucp-go"
	"github.com/chaz8081/ucp-go/shopping/types"
)

// BuyerConsentBuyer Buyer object extended with consent tracking.
type BuyerConsentBuyer struct {
	// Consent tracking fields.
	Consent *BuyerConsentConsent `json:"consent,omitzero"`
	// Email of the buyer.
	Email *string `json:"email,omitzero"`
	// First name of the buyer.
	FirstName *string `json:"first_name,omitzero"`
	// Last name of the buyer.
	LastName *string `json:"last_name,omitzero"`
	// E.164 standard.
	PhoneNumber *string `json:"phone_number,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *BuyerConsentBuyer) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("BuyerConsentBuyer: null is not a valid object")
	}
	type BuyerConsentBuyerAlias BuyerConsentBuyer
	var named BuyerConsentBuyerAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = BuyerConsentBuyer(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "consent")
	delete(all, "email")
	delete(all, "first_name")
	delete(all, "last_name")
	delete(all, "phone_number")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v BuyerConsentBuyer) MarshalJSON() ([]byte, error) {
	type BuyerConsentBuyerAlias BuyerConsentBuyer
	named, err := json.Marshal(BuyerConsentBuyerAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *BuyerConsentBuyer) Validate() error {
	if v.Consent != nil {
		if err := v.Consent.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// BuyerConsentCheckout Checkout extended with consent tracking via buyer object.
type BuyerConsentCheckout struct {
	Attribution *types.Attribution `json:"attribution,omitzero"`
	// Buyer with consent tracking.
	Buyer   *BuyerConsentBuyer `json:"buyer,omitzero"`
	Context *types.Context     `json:"context,omitzero"`
	// URL for checkout handoff and session recovery. MUST be provided when status is requires_escalation. See specification for format and availability requirements.
	//
	// Not enforced yet (phase 4): format.
	ContinueURL *string `json:"continue_url,omitzero"`
	// ISO 4217 currency code reflecting the merchant's market determination. Derived from address, context, and geo IP—buyers provide signals, merchants determine currency.
	Currency string `json:"currency"`
	// RFC 3339 expiry timestamp. Default TTL is 6 hours from creation if not sent.
	//
	// Not enforced yet (phase 4): format.
	ExpiresAt *string `json:"expires_at,omitzero"`
	// Unique identifier of the checkout session.
	ID string `json:"id"`
	// List of line items being checked out.
	LineItems []types.LineItem `json:"line_items"`
	// Links to be displayed by the platform (Privacy Policy, TOS). Mandatory for legal compliance.
	Links []types.Link `json:"links"`
	// List of messages with error and info about the checkout session state.
	Messages []types.Message `json:"messages,omitzero"`
	// Details about an order created for this checkout session.
	Order   *types.OrderConfirmation `json:"order,omitzero"`
	Payment *Payment                 `json:"payment,omitzero"`
	Signals *types.Signals           `json:"signals,omitzero"`
	// Checkout state indicating the current phase and required action. See Checkout Status lifecycle documentation for state transition details.
	Status string `json:"status"`
	// Different cart totals.
	Totals types.Totals    `json:"totals"`
	UCP    ucp.UCPMetadata `json:"ucp"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *BuyerConsentCheckout) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("BuyerConsentCheckout: null is not a valid object")
	}
	type BuyerConsentCheckoutAlias BuyerConsentCheckout
	var named BuyerConsentCheckoutAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = BuyerConsentCheckout(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 7)
	for _, name := range []string{"currency", "id", "line_items", "links", "status", "totals", "ucp"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "attribution")
	delete(all, "buyer")
	delete(all, "context")
	delete(all, "continue_url")
	delete(all, "currency")
	delete(all, "expires_at")
	delete(all, "id")
	delete(all, "line_items")
	delete(all, "links")
	delete(all, "messages")
	delete(all, "order")
	delete(all, "payment")
	delete(all, "signals")
	delete(all, "status")
	delete(all, "totals")
	delete(all, "ucp")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v BuyerConsentCheckout) MarshalJSON() ([]byte, error) {
	type BuyerConsentCheckoutAlias BuyerConsentCheckout
	named, err := json.Marshal(BuyerConsentCheckoutAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *BuyerConsentCheckout) Validate() error {
	if v.present != nil {
		if !v.present["currency"] {
			return errors.New("currency: required property is missing")
		}
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
		if !v.present["line_items"] {
			return errors.New("line_items: required property is missing")
		}
		if !v.present["links"] {
			return errors.New("links: required property is missing")
		}
		if !v.present["status"] {
			return errors.New("status: required property is missing")
		}
		if !v.present["totals"] {
			return errors.New("totals: required property is missing")
		}
		if !v.present["ucp"] {
			return errors.New("ucp: required property is missing")
		}
	}
	if v.Status != "incomplete" && v.Status != "requires_escalation" && v.Status != "ready_for_complete" && v.Status != "complete_in_progress" && v.Status != "completed" && v.Status != "canceled" {
		return errors.New("status: not one of the permitted values")
	}
	if v.Attribution != nil {
		if err := v.Attribution.Validate(); err != nil {
			return err
		}
	}
	if v.Buyer != nil {
		if err := v.Buyer.Validate(); err != nil {
			return err
		}
	}
	if v.Context != nil {
		if err := v.Context.Validate(); err != nil {
			return err
		}
	}
	for i := range v.LineItems {
		if err := v.LineItems[i].Validate(); err != nil {
			return err
		}
	}
	for i := range v.Links {
		if err := v.Links[i].Validate(); err != nil {
			return err
		}
	}
	for i := range v.Messages {
		if err := v.Messages[i].Validate(); err != nil {
			return err
		}
	}
	if v.Order != nil {
		if err := v.Order.Validate(); err != nil {
			return err
		}
	}
	if v.Payment != nil {
		if err := v.Payment.Validate(); err != nil {
			return err
		}
	}
	if v.Signals != nil {
		if err := v.Signals.Validate(); err != nil {
			return err
		}
	}
	if err := v.Totals.Validate(); err != nil {
		return err
	}
	if err := v.UCP.Validate(); err != nil {
		return err
	}
	return nil
}

// BuyerConsentConsent User consent states for data processing
type BuyerConsentConsent struct {
	// Consent for analytics and performance tracking.
	Analytics *bool `json:"analytics,omitzero"`
	// Consent for marketing communications.
	Marketing *bool `json:"marketing,omitzero"`
	// Consent for storing user preferences.
	Preferences *bool `json:"preferences,omitzero"`
	// Consent for selling data to third parties (CCPA).
	SaleOfData *bool `json:"sale_of_data,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *BuyerConsentConsent) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("BuyerConsentConsent: null is not a valid object")
	}
	type BuyerConsentConsentAlias BuyerConsentConsent
	var named BuyerConsentConsentAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = BuyerConsentConsent(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "analytics")
	delete(all, "marketing")
	delete(all, "preferences")
	delete(all, "sale_of_data")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v BuyerConsentConsent) MarshalJSON() ([]byte, error) {
	type BuyerConsentConsentAlias BuyerConsentConsent
	named, err := json.Marshal(BuyerConsentConsentAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *BuyerConsentConsent) Validate() error {
	return nil
}
