// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/catalog_search.json (spec release/2026-08-25@cd78fb3)

package shopping

import (
	"encoding/json"
	"errors"
	ucp "github.com/chaz8081/ucp-go"
	commontypes "github.com/chaz8081/ucp-go/common/types"
	"github.com/chaz8081/ucp-go/shopping/types"
)

// CatalogSearch Product catalog search capability.
type CatalogSearch map[string]any

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *CatalogSearch) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("CatalogSearch: null is not a valid object")
	}
	type CatalogSearchAlias CatalogSearch
	var alias CatalogSearchAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CatalogSearch(alias)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *CatalogSearch) Validate() error {
	return nil
}

// CatalogSearchSearchRequest is generated from shopping/catalog_search.json.
type CatalogSearchSearchRequest struct {
	Attribution *types.Attribution             `json:"attribution,omitzero"`
	Context     *commontypes.Context           `json:"context,omitzero"`
	Filters     *types.SearchFilters           `json:"filters,omitzero"`
	Pagination  *commontypes.PaginationRequest `json:"pagination,omitzero"`
	// Free-text search query.
	Query   *string              `json:"query,omitzero"`
	Signals *commontypes.Signals `json:"signals,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *CatalogSearchSearchRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("CatalogSearchSearchRequest: null is not a valid object")
	}
	type CatalogSearchSearchRequestAlias CatalogSearchSearchRequest
	var named CatalogSearchSearchRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = CatalogSearchSearchRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "attribution")
	delete(all, "context")
	delete(all, "filters")
	delete(all, "pagination")
	delete(all, "query")
	delete(all, "signals")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v CatalogSearchSearchRequest) MarshalJSON() ([]byte, error) {
	type CatalogSearchSearchRequestAlias CatalogSearchSearchRequest
	named, err := json.Marshal(CatalogSearchSearchRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *CatalogSearchSearchRequest) Validate() error {
	if v.Attribution != nil {
		if err := v.Attribution.Validate(); err != nil {
			return err
		}
	}
	if v.Context != nil {
		if err := v.Context.Validate(); err != nil {
			return err
		}
	}
	if v.Filters != nil {
		if err := v.Filters.Validate(); err != nil {
			return err
		}
	}
	if v.Pagination != nil {
		if err := v.Pagination.Validate(); err != nil {
			return err
		}
	}
	if v.Signals != nil {
		if err := v.Signals.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// CatalogSearchSearchResponse is generated from shopping/catalog_search.json.
type CatalogSearchSearchResponse struct {
	// Outstanding extension-defined Actions for this catalog search response.
	Actions *commontypes.Actions `json:"actions,omitzero"`
	// Errors, warnings, or informational messages about the search results.
	Messages   []commontypes.Message           `json:"messages,omitzero"`
	Pagination *commontypes.PaginationResponse `json:"pagination,omitzero"`
	// Policies (e.g., return/refund terms) that apply to the products in these search results. `applies_to` targets are relative to the response root; when absent or empty, refer to the URLs in `links[]`.
	Policies []commontypes.Policy `json:"policies,omitzero"`
	// Products matching the search criteria.
	Products []types.Product              `json:"products"`
	UCP      ucp.UCPResponseCatalogSchema `json:"ucp"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *CatalogSearchSearchResponse) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("CatalogSearchSearchResponse: null is not a valid object")
	}
	type CatalogSearchSearchResponseAlias CatalogSearchSearchResponse
	var named CatalogSearchSearchResponseAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = CatalogSearchSearchResponse(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"products", "ucp"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "actions")
	delete(all, "messages")
	delete(all, "pagination")
	delete(all, "policies")
	delete(all, "products")
	delete(all, "ucp")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v CatalogSearchSearchResponse) MarshalJSON() ([]byte, error) {
	type CatalogSearchSearchResponseAlias CatalogSearchSearchResponse
	named, err := json.Marshal(CatalogSearchSearchResponseAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *CatalogSearchSearchResponse) Validate() error {
	if v.present != nil {
		if !v.present["products"] {
			return errors.New("products: required property is missing")
		}
		if !v.present["ucp"] {
			return errors.New("ucp: required property is missing")
		}
	}
	if v.Actions != nil {
		if err := v.Actions.Validate(); err != nil {
			return err
		}
	}
	for i := range v.Messages {
		if err := v.Messages[i].Validate(); err != nil {
			return err
		}
	}
	if v.Pagination != nil {
		if err := v.Pagination.Validate(); err != nil {
			return err
		}
	}
	for i := range v.Policies {
		if err := v.Policies[i].Validate(); err != nil {
			return err
		}
	}
	for i := range v.Products {
		if err := v.Products[i].Validate(); err != nil {
			return err
		}
	}
	if err := v.UCP.Validate(); err != nil {
		return err
	}
	return nil
}
