// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/discount.json (spec release/2026-04-08@a2d8bf0)

package shopping

import (
	"encoding/json"
	"errors"
	"github.com/chaz8081/ucp-go"
	"github.com/chaz8081/ucp-go/shopping/types"
)

// DiscountAllocation Breakdown of how a discount amount was allocated to a specific target.
type DiscountAllocation struct {
	// Amount allocated to this target in ISO 4217 minor units.
	Amount types.Amount `json:"amount"`
	// JSONPath to the allocation target (e.g., '$.line_items[0]', '$.totals.shipping').
	Path string `json:"path"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *DiscountAllocation) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("DiscountAllocation: null is not a valid object")
	}
	type DiscountAllocationAlias DiscountAllocation
	var named DiscountAllocationAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = DiscountAllocation(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"amount", "path"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "amount")
	delete(all, "path")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v DiscountAllocation) MarshalJSON() ([]byte, error) {
	type DiscountAllocationAlias DiscountAllocation
	named, err := json.Marshal(DiscountAllocationAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *DiscountAllocation) Validate() error {
	if v.present != nil {
		if !v.present["amount"] {
			return errors.New("amount: required property is missing")
		}
		if !v.present["path"] {
			return errors.New("path: required property is missing")
		}
	}
	if err := v.Amount.Validate(); err != nil {
		return err
	}
	return nil
}

// DiscountAppliedDiscount A discount that was successfully applied.
type DiscountAppliedDiscount struct {
	// Breakdown of where this discount was allocated. Sum of allocation amounts equals total amount.
	Allocations []DiscountAllocation `json:"allocations,omitzero"`
	// Total discount amount in ISO 4217 minor units.
	Amount types.Amount `json:"amount"`
	// True if applied automatically by merchant rules (no code required).
	Automatic *bool `json:"automatic,omitzero"`
	// The discount code. Omitted for automatic discounts.
	Code *string `json:"code,omitzero"`
	// The eligibility claim accepted by the Business for this discount. Corresponds to a value from context.eligibility. Omitted for code-based and non-eligibility automatic discounts.
	Eligibility *types.ReverseDomainName `json:"eligibility,omitzero"`
	// Allocation method. 'each' = applied independently per item. 'across' = split proportionally by value.
	Method *string `json:"method,omitzero"`
	// Stacking order for discount calculation. Lower numbers applied first (1 = first).
	Priority *int64 `json:"priority,omitzero"`
	// True if this discount requires additional verification.
	Provisional *bool `json:"provisional,omitzero"`
	// Human-readable discount name (e.g., 'Summer Sale 20% Off').
	Title string `json:"title"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *DiscountAppliedDiscount) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("DiscountAppliedDiscount: null is not a valid object")
	}
	type DiscountAppliedDiscountAlias DiscountAppliedDiscount
	var named DiscountAppliedDiscountAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = DiscountAppliedDiscount(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"amount", "title"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "allocations")
	delete(all, "amount")
	delete(all, "automatic")
	delete(all, "code")
	delete(all, "eligibility")
	delete(all, "method")
	delete(all, "priority")
	delete(all, "provisional")
	delete(all, "title")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v DiscountAppliedDiscount) MarshalJSON() ([]byte, error) {
	type DiscountAppliedDiscountAlias DiscountAppliedDiscount
	named, err := json.Marshal(DiscountAppliedDiscountAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *DiscountAppliedDiscount) Validate() error {
	if v.present != nil {
		if !v.present["amount"] {
			return errors.New("amount: required property is missing")
		}
		if !v.present["title"] {
			return errors.New("title: required property is missing")
		}
	}
	if v.Method != nil && *v.Method != "each" && *v.Method != "across" {
		return errors.New("method: not one of the permitted values")
	}
	if v.Priority != nil && *v.Priority < 1 {
		return errors.New("priority: below minimum 1")
	}
	for i := range v.Allocations {
		if err := v.Allocations[i].Validate(); err != nil {
			return err
		}
	}
	if err := v.Amount.Validate(); err != nil {
		return err
	}
	if v.Eligibility != nil {
		if err := v.Eligibility.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// DiscountCart Cart extended with discount capability.
type DiscountCart struct {
	Attribution *types.Attribution `json:"attribution,omitzero"`
	// Optional buyer information for personalized estimates.
	Buyer *types.Buyer `json:"buyer,omitzero"`
	// Buyer signals for localization (country, region, postal_code). Merchant uses for pricing, availability, currency. Falls back to geo-IP if omitted.
	Context *types.Context `json:"context,omitzero"`
	// URL for cart handoff and session recovery. Enables sharing and human-in-the-loop flows.
	//
	// Not enforced yet (phase 4): format.
	ContinueURL *string `json:"continue_url,omitzero"`
	// ISO 4217 currency code. Determined by merchant based on context or geo-IP.
	Currency  string                   `json:"currency"`
	Discounts *DiscountDiscountsObject `json:"discounts,omitzero"`
	// Cart expiry timestamp (RFC 3339). Optional.
	//
	// Not enforced yet (phase 4): format.
	ExpiresAt *string `json:"expires_at,omitzero"`
	// Unique cart identifier.
	ID string `json:"id"`
	// Cart line items. Same structure as checkout. Full replacement on update.
	LineItems []types.LineItem `json:"line_items"`
	// Optional merchant links (policies, FAQs).
	Links []types.Link `json:"links,omitzero"`
	// Validation messages, warnings, or informational notices.
	Messages []types.Message `json:"messages,omitzero"`
	Signals  *types.Signals  `json:"signals,omitzero"`
	// Estimated cost breakdown. May be partial if shipping/tax not yet calculable.
	Totals types.Totals    `json:"totals"`
	UCP    ucp.UCPMetadata `json:"ucp"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *DiscountCart) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("DiscountCart: null is not a valid object")
	}
	type DiscountCartAlias DiscountCart
	var named DiscountCartAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = DiscountCart(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 5)
	for _, name := range []string{"currency", "id", "line_items", "totals", "ucp"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "attribution")
	delete(all, "buyer")
	delete(all, "context")
	delete(all, "continue_url")
	delete(all, "currency")
	delete(all, "discounts")
	delete(all, "expires_at")
	delete(all, "id")
	delete(all, "line_items")
	delete(all, "links")
	delete(all, "messages")
	delete(all, "signals")
	delete(all, "totals")
	delete(all, "ucp")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v DiscountCart) MarshalJSON() ([]byte, error) {
	type DiscountCartAlias DiscountCart
	named, err := json.Marshal(DiscountCartAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *DiscountCart) Validate() error {
	if v.present != nil {
		if !v.present["currency"] {
			return errors.New("currency: required property is missing")
		}
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
		if !v.present["line_items"] {
			return errors.New("line_items: required property is missing")
		}
		if !v.present["totals"] {
			return errors.New("totals: required property is missing")
		}
		if !v.present["ucp"] {
			return errors.New("ucp: required property is missing")
		}
	}
	if v.Attribution != nil {
		if err := v.Attribution.Validate(); err != nil {
			return err
		}
	}
	if v.Buyer != nil {
		if err := v.Buyer.Validate(); err != nil {
			return err
		}
	}
	if v.Context != nil {
		if err := v.Context.Validate(); err != nil {
			return err
		}
	}
	if v.Discounts != nil {
		if err := v.Discounts.Validate(); err != nil {
			return err
		}
	}
	for i := range v.LineItems {
		if err := v.LineItems[i].Validate(); err != nil {
			return err
		}
	}
	for i := range v.Links {
		if err := v.Links[i].Validate(); err != nil {
			return err
		}
	}
	for i := range v.Messages {
		if err := v.Messages[i].Validate(); err != nil {
			return err
		}
	}
	if v.Signals != nil {
		if err := v.Signals.Validate(); err != nil {
			return err
		}
	}
	if err := v.Totals.Validate(); err != nil {
		return err
	}
	if err := v.UCP.Validate(); err != nil {
		return err
	}
	return nil
}

// DiscountCheckout Checkout extended with discount capability.
type DiscountCheckout struct {
	Attribution *types.Attribution `json:"attribution,omitzero"`
	// Representation of the buyer.
	Buyer   *types.Buyer   `json:"buyer,omitzero"`
	Context *types.Context `json:"context,omitzero"`
	// URL for checkout handoff and session recovery. MUST be provided when status is requires_escalation. See specification for format and availability requirements.
	//
	// Not enforced yet (phase 4): format.
	ContinueURL *string `json:"continue_url,omitzero"`
	// ISO 4217 currency code reflecting the merchant's market determination. Derived from address, context, and geo IP—buyers provide signals, merchants determine currency.
	Currency  string                   `json:"currency"`
	Discounts *DiscountDiscountsObject `json:"discounts,omitzero"`
	// RFC 3339 expiry timestamp. Default TTL is 6 hours from creation if not sent.
	//
	// Not enforced yet (phase 4): format.
	ExpiresAt *string `json:"expires_at,omitzero"`
	// Unique identifier of the checkout session.
	ID string `json:"id"`
	// List of line items being checked out.
	LineItems []types.LineItem `json:"line_items"`
	// Links to be displayed by the platform (Privacy Policy, TOS). Mandatory for legal compliance.
	Links []types.Link `json:"links"`
	// List of messages with error and info about the checkout session state.
	Messages []types.Message `json:"messages,omitzero"`
	// Details about an order created for this checkout session.
	Order   *types.OrderConfirmation `json:"order,omitzero"`
	Payment *Payment                 `json:"payment,omitzero"`
	Signals *types.Signals           `json:"signals,omitzero"`
	// Checkout state indicating the current phase and required action. See Checkout Status lifecycle documentation for state transition details.
	Status string `json:"status"`
	// Different cart totals.
	Totals types.Totals    `json:"totals"`
	UCP    ucp.UCPMetadata `json:"ucp"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *DiscountCheckout) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("DiscountCheckout: null is not a valid object")
	}
	type DiscountCheckoutAlias DiscountCheckout
	var named DiscountCheckoutAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = DiscountCheckout(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 7)
	for _, name := range []string{"currency", "id", "line_items", "links", "status", "totals", "ucp"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "attribution")
	delete(all, "buyer")
	delete(all, "context")
	delete(all, "continue_url")
	delete(all, "currency")
	delete(all, "discounts")
	delete(all, "expires_at")
	delete(all, "id")
	delete(all, "line_items")
	delete(all, "links")
	delete(all, "messages")
	delete(all, "order")
	delete(all, "payment")
	delete(all, "signals")
	delete(all, "status")
	delete(all, "totals")
	delete(all, "ucp")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v DiscountCheckout) MarshalJSON() ([]byte, error) {
	type DiscountCheckoutAlias DiscountCheckout
	named, err := json.Marshal(DiscountCheckoutAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *DiscountCheckout) Validate() error {
	if v.present != nil {
		if !v.present["currency"] {
			return errors.New("currency: required property is missing")
		}
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
		if !v.present["line_items"] {
			return errors.New("line_items: required property is missing")
		}
		if !v.present["links"] {
			return errors.New("links: required property is missing")
		}
		if !v.present["status"] {
			return errors.New("status: required property is missing")
		}
		if !v.present["totals"] {
			return errors.New("totals: required property is missing")
		}
		if !v.present["ucp"] {
			return errors.New("ucp: required property is missing")
		}
	}
	if v.Status != "incomplete" && v.Status != "requires_escalation" && v.Status != "ready_for_complete" && v.Status != "complete_in_progress" && v.Status != "completed" && v.Status != "canceled" {
		return errors.New("status: not one of the permitted values")
	}
	if v.Attribution != nil {
		if err := v.Attribution.Validate(); err != nil {
			return err
		}
	}
	if v.Buyer != nil {
		if err := v.Buyer.Validate(); err != nil {
			return err
		}
	}
	if v.Context != nil {
		if err := v.Context.Validate(); err != nil {
			return err
		}
	}
	if v.Discounts != nil {
		if err := v.Discounts.Validate(); err != nil {
			return err
		}
	}
	for i := range v.LineItems {
		if err := v.LineItems[i].Validate(); err != nil {
			return err
		}
	}
	for i := range v.Links {
		if err := v.Links[i].Validate(); err != nil {
			return err
		}
	}
	for i := range v.Messages {
		if err := v.Messages[i].Validate(); err != nil {
			return err
		}
	}
	if v.Order != nil {
		if err := v.Order.Validate(); err != nil {
			return err
		}
	}
	if v.Payment != nil {
		if err := v.Payment.Validate(); err != nil {
			return err
		}
	}
	if v.Signals != nil {
		if err := v.Signals.Validate(); err != nil {
			return err
		}
	}
	if err := v.Totals.Validate(); err != nil {
		return err
	}
	if err := v.UCP.Validate(); err != nil {
		return err
	}
	return nil
}

// DiscountDiscountsObject Discount codes input and applied discounts output.
type DiscountDiscountsObject struct {
	// Discounts successfully applied (code-based and automatic).
	Applied []DiscountAppliedDiscount `json:"applied,omitzero"`
	// Discount codes to apply. Case-insensitive. Replaces previously submitted codes. Send empty array to clear.
	Codes []string `json:"codes,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *DiscountDiscountsObject) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("DiscountDiscountsObject: null is not a valid object")
	}
	type DiscountDiscountsObjectAlias DiscountDiscountsObject
	var named DiscountDiscountsObjectAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = DiscountDiscountsObject(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "applied")
	delete(all, "codes")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v DiscountDiscountsObject) MarshalJSON() ([]byte, error) {
	type DiscountDiscountsObjectAlias DiscountDiscountsObject
	named, err := json.Marshal(DiscountDiscountsObjectAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *DiscountDiscountsObject) Validate() error {
	for i := range v.Applied {
		if err := v.Applied[i].Validate(); err != nil {
			return err
		}
	}
	return nil
}
