// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/order_update_request.json (spec release/2026-04-08@a2d8bf0)

package shopping

import (
	"encoding/json"
	"errors"
	"github.com/chaz8081/ucp-go"
	"github.com/chaz8081/ucp-go/shopping/types"
)

// OrderUpdateRequest Order schema with line items, buyer-facing fulfillment expectations, and event logs.
type OrderUpdateRequest struct {
	// Post-order events (refunds, returns, credits, disputes, cancellations, etc.) that exist independently of fulfillment.
	Adjustments []types.AdjustmentUpdateRequest `json:"adjustments,omitzero"`
	// Associated checkout ID for reconciliation.
	CheckoutID string `json:"checkout_id"`
	// Fulfillment data: buyer expectations and what actually happened.
	Fulfillment OrderUpdateRequestFulfillment `json:"fulfillment"`
	// Unique order identifier.
	ID string `json:"id"`
	// Human-readable label for identifying the order. MUST only be provided by the business.
	Label *string `json:"label,omitzero"`
	// Line items representing what was purchased — can change post-order via edits or exchanges.
	LineItems []types.OrderLineItemUpdateRequest `json:"line_items"`
	// Business outcome messages (errors, warnings, informational). Present when the business needs to communicate status or issues to the platform.
	Messages []types.MessageUpdateRequest `json:"messages,omitzero"`
	// Permalink to access the order on merchant site.
	//
	// Not enforced yet (phase 4): format.
	PermalinkURL string `json:"permalink_url"`
	// Different totals for the order.
	Totals types.TotalsUpdateRequest    `json:"totals"`
	UCP    ucp.UCPMetadataUpdateRequest `json:"ucp"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *OrderUpdateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("OrderUpdateRequest: null is not a valid object")
	}
	type OrderUpdateRequestAlias OrderUpdateRequest
	var named OrderUpdateRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = OrderUpdateRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 7)
	for _, name := range []string{"checkout_id", "fulfillment", "id", "line_items", "permalink_url", "totals", "ucp"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "adjustments")
	delete(all, "checkout_id")
	delete(all, "fulfillment")
	delete(all, "id")
	delete(all, "label")
	delete(all, "line_items")
	delete(all, "messages")
	delete(all, "permalink_url")
	delete(all, "totals")
	delete(all, "ucp")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v OrderUpdateRequest) MarshalJSON() ([]byte, error) {
	type OrderUpdateRequestAlias OrderUpdateRequest
	named, err := json.Marshal(OrderUpdateRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *OrderUpdateRequest) Validate() error {
	if v.present != nil {
		if !v.present["checkout_id"] {
			return errors.New("checkout_id: required property is missing")
		}
		if !v.present["fulfillment"] {
			return errors.New("fulfillment: required property is missing")
		}
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
		if !v.present["line_items"] {
			return errors.New("line_items: required property is missing")
		}
		if !v.present["permalink_url"] {
			return errors.New("permalink_url: required property is missing")
		}
		if !v.present["totals"] {
			return errors.New("totals: required property is missing")
		}
		if !v.present["ucp"] {
			return errors.New("ucp: required property is missing")
		}
	}
	for i := range v.Adjustments {
		if err := v.Adjustments[i].Validate(); err != nil {
			return err
		}
	}
	if err := v.Fulfillment.Validate(); err != nil {
		return err
	}
	for i := range v.LineItems {
		if err := v.LineItems[i].Validate(); err != nil {
			return err
		}
	}
	for i := range v.Messages {
		if err := v.Messages[i].Validate(); err != nil {
			return err
		}
	}
	if err := v.Totals.Validate(); err != nil {
		return err
	}
	if err := v.UCP.Validate(); err != nil {
		return err
	}
	return nil
}

// OrderUpdateRequestPlatformSchema Platform's order capability configuration.
type OrderUpdateRequestPlatformSchema struct {
	// URL where merchant sends order lifecycle events (webhooks).
	//
	// Not enforced yet (phase 4): format.
	WebhookURL string `json:"webhook_url"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *OrderUpdateRequestPlatformSchema) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("OrderUpdateRequestPlatformSchema: null is not a valid object")
	}
	type OrderUpdateRequestPlatformSchemaAlias OrderUpdateRequestPlatformSchema
	var named OrderUpdateRequestPlatformSchemaAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = OrderUpdateRequestPlatformSchema(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"webhook_url"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "webhook_url")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v OrderUpdateRequestPlatformSchema) MarshalJSON() ([]byte, error) {
	type OrderUpdateRequestPlatformSchemaAlias OrderUpdateRequestPlatformSchema
	named, err := json.Marshal(OrderUpdateRequestPlatformSchemaAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *OrderUpdateRequestPlatformSchema) Validate() error {
	if v.present != nil {
		if !v.present["webhook_url"] {
			return errors.New("webhook_url: required property is missing")
		}
	}
	return nil
}

// OrderUpdateRequestFulfillment Fulfillment data: buyer expectations and what actually happened.
type OrderUpdateRequestFulfillment struct {
	// Append-only event log of actual shipments. Each event references line items by ID.
	Events []types.FulfillmentEventUpdateRequest `json:"events,omitzero"`
	// Buyer-facing groups representing when/how items will be delivered. Can be split, merged, or adjusted post-order.
	Expectations []types.ExpectationUpdateRequest `json:"expectations,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *OrderUpdateRequestFulfillment) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("OrderUpdateRequestFulfillment: null is not a valid object")
	}
	type OrderUpdateRequestFulfillmentAlias OrderUpdateRequestFulfillment
	var named OrderUpdateRequestFulfillmentAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = OrderUpdateRequestFulfillment(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "events")
	delete(all, "expectations")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v OrderUpdateRequestFulfillment) MarshalJSON() ([]byte, error) {
	type OrderUpdateRequestFulfillmentAlias OrderUpdateRequestFulfillment
	named, err := json.Marshal(OrderUpdateRequestFulfillmentAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *OrderUpdateRequestFulfillment) Validate() error {
	for i := range v.Events {
		if err := v.Events[i].Validate(); err != nil {
			return err
		}
	}
	for i := range v.Expectations {
		if err := v.Expectations[i].Validate(); err != nil {
			return err
		}
	}
	return nil
}
