// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/permalink.json (spec release/2026-08-25@cd78fb3)

package shopping

import (
	"encoding/json"
	"errors"
	"regexp"
	"sync"
)

// PermalinkConfig Business browser endpoint configuration for shopping permalinks.
type PermalinkConfig struct {
	Endpoint PermalinkEndpoint `json:"endpoint"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *PermalinkConfig) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("PermalinkConfig: null is not a valid object")
	}
	type PermalinkConfigAlias PermalinkConfig
	var named PermalinkConfigAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = PermalinkConfig(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"endpoint"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "endpoint")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v PermalinkConfig) MarshalJSON() ([]byte, error) {
	type PermalinkConfigAlias PermalinkConfig
	named, err := json.Marshal(PermalinkConfigAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *PermalinkConfig) Validate() error {
	if v.present != nil {
		if !v.present["endpoint"] {
			return errors.New("endpoint: required property is missing")
		}
	}
	if err := v.Endpoint.Validate(); err != nil {
		return err
	}
	return nil
}

// PermalinkEndpoint Absolute HTTPS browser endpoint with a non-empty authority and without userinfo, query, fragment, whitespace, backslashes, or trailing slash. Optional compact item path and query parameters are appended to this endpoint.
//
// Annotation only in draft 2020-12, so not asserted: format.
type PermalinkEndpoint string

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *PermalinkEndpoint) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("PermalinkEndpoint: null is not a valid string")
	}
	type PermalinkEndpointAlias PermalinkEndpoint
	var alias PermalinkEndpointAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = PermalinkEndpoint(alias)
	return nil
}

var pattern_PermalinkEndpoint = sync.OnceValue(func() *regexp.Regexp {
	return regexp.MustCompile("^https://[^/?#\\s\\\\@]+(?:/[^?#\\s\\\\]*[^/?#\\s\\\\])?$")
})

// Validate reports the first constraint violation, or nil.
func (v *PermalinkEndpoint) Validate() error {
	if !pattern_PermalinkEndpoint().MatchString(string(string(*v))) {
		return errors.New("PermalinkEndpoint: does not match pattern")
	}
	return nil
}

// $defs/permalink is an extension mount point (a namespace of schemas,
// not a schema); no type is emitted for it.
