// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/adjustment_create_request.json (spec release/2026-04-08@a2d8bf0)

package types

import (
	"encoding/json"
	"errors"
)

// AdjustmentCreateRequest Post-order event that exists independently of fulfillment. Typically represents money movements but can be any post-order change. Polymorphic type that can optionally reference line items.
type AdjustmentCreateRequest struct {
	// Human-readable reason or description (e.g., 'Defective item', 'Customer requested').
	Description *string `json:"description,omitzero"`
	// Adjustment event identifier.
	ID string `json:"id"`
	// Which line items and quantities are affected (optional).
	LineItems []AdjustmentCreateRequestLineItemsItem `json:"line_items,omitzero"`
	// RFC 3339 timestamp when this adjustment occurred.
	//
	// Annotation only in draft 2020-12, so not asserted: format.
	OccurredAt string `json:"occurred_at"`
	// Adjustment status.
	Status string `json:"status"`
	// Adjustment totals breakdown. Signed values - negative for money returned to buyer (refunds, credits), positive for additional charges (exchanges).
	Totals []TotalCreateRequest `json:"totals,omitzero"`
	// Type of adjustment (open string). Typically money-related like: refund, return, credit, price_adjustment, dispute, cancellation. Can be any value that makes sense for the merchant's business.
	Type string `json:"type"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *AdjustmentCreateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("AdjustmentCreateRequest: null is not a valid object")
	}
	type AdjustmentCreateRequestAlias AdjustmentCreateRequest
	var named AdjustmentCreateRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = AdjustmentCreateRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 4)
	for _, name := range []string{"id", "occurred_at", "status", "type"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "description")
	delete(all, "id")
	delete(all, "line_items")
	delete(all, "occurred_at")
	delete(all, "status")
	delete(all, "totals")
	delete(all, "type")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v AdjustmentCreateRequest) MarshalJSON() ([]byte, error) {
	type AdjustmentCreateRequestAlias AdjustmentCreateRequest
	named, err := json.Marshal(AdjustmentCreateRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *AdjustmentCreateRequest) Validate() error {
	if v.present != nil {
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
		if !v.present["occurred_at"] {
			return errors.New("occurred_at: required property is missing")
		}
		if !v.present["status"] {
			return errors.New("status: required property is missing")
		}
		if !v.present["type"] {
			return errors.New("type: required property is missing")
		}
	}
	if v.Status != "pending" && v.Status != "completed" && v.Status != "failed" {
		return errors.New("status: not one of the permitted values")
	}
	for i := range v.LineItems {
		if err := v.LineItems[i].Validate(); err != nil {
			return err
		}
	}
	for i := range v.Totals {
		if err := v.Totals[i].Validate(); err != nil {
			return err
		}
	}
	return nil
}

// AdjustmentCreateRequestLineItemsItem is generated from shopping/types/adjustment_create_request.json.
type AdjustmentCreateRequestLineItemsItem struct {
	// Line item ID reference.
	ID string `json:"id"`
	// Signed quantity affected by this adjustment. Negative values represent reductions (e.g. returns); positive values represent additions (e.g. exchanges).
	Quantity int64 `json:"quantity"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *AdjustmentCreateRequestLineItemsItem) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("AdjustmentCreateRequestLineItemsItem: null is not a valid object")
	}
	type AdjustmentCreateRequestLineItemsItemAlias AdjustmentCreateRequestLineItemsItem
	var named AdjustmentCreateRequestLineItemsItemAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = AdjustmentCreateRequestLineItemsItem(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"id", "quantity"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "id")
	delete(all, "quantity")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v AdjustmentCreateRequestLineItemsItem) MarshalJSON() ([]byte, error) {
	type AdjustmentCreateRequestLineItemsItemAlias AdjustmentCreateRequestLineItemsItem
	named, err := json.Marshal(AdjustmentCreateRequestLineItemsItemAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *AdjustmentCreateRequestLineItemsItem) Validate() error {
	if v.present != nil {
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
		if !v.present["quantity"] {
			return errors.New("quantity: required property is missing")
		}
	}
	return nil
}
