// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/amount.json (spec release/2026-04-08@a2d8bf0)

package types

import "errors"

// Amount Monetary amount in the currency's minor unit as defined by ISO 4217. Refer to the currency's exponent to determine minor-to-major ratio (e.g., 2 for USD, 0 for JPY, 3 for KWD).
type Amount int64

// Validate reports the first constraint violation, or nil.
func (v *Amount) Validate() error {
	if int64(*v) < 0 {
		return errors.New("Amount: below minimum 0")
	}
	return nil
}
