// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/attribution_create_request.json (spec release/2026-04-08@a2d8bf0)

package types

// AttributionCreateRequest Platform-emitted referral and conversion-event context — campaign identifiers, click IDs, source/medium markers, etc. The same parameters platforms communicate via URL query parameters in browser-based flows.
type AttributionCreateRequest map[string]string

// Validate reports the first constraint violation, or nil.
func (v *AttributionCreateRequest) Validate() error {
	return nil
}
