// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/attribution.json (spec release/2026-04-08@a2d8bf0)

package types

// Attribution Platform-emitted referral and conversion-event context — campaign identifiers, click IDs, source/medium markers, etc. The same parameters platforms communicate via URL query parameters in browser-based flows.
type Attribution map[string]string

// Validate reports the first constraint violation, or nil.
func (v *Attribution) Validate() error {
	return nil
}
