// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/business_fulfillment_config.json (spec release/2026-04-08@a2d8bf0)

package types

import "encoding/json"

// BusinessFulfillmentConfig Business's fulfillment configuration.
type BusinessFulfillmentConfig struct {
	// Allowed method type combinations.
	AllowsMethodCombinations [][]string `json:"allows_method_combinations,omitzero"`
	// Permits multiple destinations per method type.
	AllowsMultiDestination *BusinessFulfillmentConfigAllowsMultiDestination `json:"allows_multi_destination,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *BusinessFulfillmentConfig) UnmarshalJSON(data []byte) error {
	type BusinessFulfillmentConfigAlias BusinessFulfillmentConfig
	var named BusinessFulfillmentConfigAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = BusinessFulfillmentConfig(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "allows_method_combinations")
	delete(all, "allows_multi_destination")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v BusinessFulfillmentConfig) MarshalJSON() ([]byte, error) {
	type BusinessFulfillmentConfigAlias BusinessFulfillmentConfig
	named, err := json.Marshal(BusinessFulfillmentConfigAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *BusinessFulfillmentConfig) Validate() error {
	if v.AllowsMultiDestination != nil {
		if err := v.AllowsMultiDestination.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// BusinessFulfillmentConfigAllowsMultiDestination Permits multiple destinations per method type.
type BusinessFulfillmentConfigAllowsMultiDestination struct {
	// Multiple pickup locations allowed.
	Pickup *bool `json:"pickup,omitzero"`
	// Multiple shipping destinations allowed.
	Shipping *bool `json:"shipping,omitzero"`
}

// Validate reports the first constraint violation, or nil.
func (v *BusinessFulfillmentConfigAllowsMultiDestination) Validate() error {
	return nil
}
