// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/buyer.json (spec release/2026-04-08@a2d8bf0)

package types

import (
	"encoding/json"
	"errors"
)

// Buyer is generated from shopping/types/buyer.json.
type Buyer struct {
	// Email of the buyer.
	Email *string `json:"email,omitzero"`
	// First name of the buyer.
	FirstName *string `json:"first_name,omitzero"`
	// Last name of the buyer.
	LastName *string `json:"last_name,omitzero"`
	// E.164 standard.
	PhoneNumber *string `json:"phone_number,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *Buyer) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("Buyer: null is not a valid object")
	}
	type BuyerAlias Buyer
	var named BuyerAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = Buyer(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "email")
	delete(all, "first_name")
	delete(all, "last_name")
	delete(all, "phone_number")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v Buyer) MarshalJSON() ([]byte, error) {
	type BuyerAlias Buyer
	named, err := json.Marshal(BuyerAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *Buyer) Validate() error {
	return nil
}
