// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/card_payment_instrument.json (spec release/2026-04-08@a2d8bf0)

package types

import (
	"encoding/json"
	"errors"
)

// CardPaymentInstrument A basic card payment instrument with visible card details. Can be inherited by a handler's instrument schema to define handler-specific display details or more complex credential structures.
type CardPaymentInstrument struct {
	// The billing address associated with this payment method.
	BillingAddress *PostalAddress     `json:"billing_address,omitzero"`
	Credential     *PaymentCredential `json:"credential,omitzero"`
	// Display information for this payment instrument. Each payment instrument schema defines its specific display properties, as outlined by the payment handler.
	Display map[string]any `json:"display,omitzero"`
	// The unique identifier for the handler instance that produced this instrument. This corresponds to the 'id' field in the Payment Handler definition.
	HandlerID string `json:"handler_id"`
	// A unique identifier for this instrument instance, assigned by the platform.
	ID string `json:"id"`
	// The broad category of the instrument (e.g., 'card', 'tokenized_card'). Specific schemas will constrain this to a constant value.
	Type string `json:"type"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *CardPaymentInstrument) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("CardPaymentInstrument: null is not a valid object")
	}
	type CardPaymentInstrumentAlias CardPaymentInstrument
	var named CardPaymentInstrumentAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = CardPaymentInstrument(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 3)
	for _, name := range []string{"handler_id", "id", "type"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "billing_address")
	delete(all, "credential")
	delete(all, "display")
	delete(all, "handler_id")
	delete(all, "id")
	delete(all, "type")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v CardPaymentInstrument) MarshalJSON() ([]byte, error) {
	type CardPaymentInstrumentAlias CardPaymentInstrument
	named, err := json.Marshal(CardPaymentInstrumentAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *CardPaymentInstrument) Validate() error {
	if v.present != nil {
		if !v.present["handler_id"] {
			return errors.New("handler_id: required property is missing")
		}
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
		if !v.present["type"] {
			return errors.New("type: required property is missing")
		}
	}
	if v.BillingAddress != nil {
		if err := v.BillingAddress.Validate(); err != nil {
			return err
		}
	}
	if v.Credential != nil {
		if err := v.Credential.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// CardPaymentInstrumentAvailableCardPaymentInstrument Declares card instrument availability with card-specific constraints.
type CardPaymentInstrumentAvailableCardPaymentInstrument struct {
	// Constraints on this instrument type. Structure depends on instrument type and active capabilities.
	Constraints map[string]any `json:"constraints,omitzero"`
	// The instrument type identifier (e.g., 'card', 'gift_card'). References an instrument schema's type constant.
	Type string `json:"type"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *CardPaymentInstrumentAvailableCardPaymentInstrument) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("CardPaymentInstrumentAvailableCardPaymentInstrument: null is not a valid object")
	}
	type CardPaymentInstrumentAvailableCardPaymentInstrumentAlias CardPaymentInstrumentAvailableCardPaymentInstrument
	var named CardPaymentInstrumentAvailableCardPaymentInstrumentAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = CardPaymentInstrumentAvailableCardPaymentInstrument(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"type"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "constraints")
	delete(all, "type")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v CardPaymentInstrumentAvailableCardPaymentInstrument) MarshalJSON() ([]byte, error) {
	type CardPaymentInstrumentAvailableCardPaymentInstrumentAlias CardPaymentInstrumentAvailableCardPaymentInstrument
	named, err := json.Marshal(CardPaymentInstrumentAvailableCardPaymentInstrumentAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *CardPaymentInstrumentAvailableCardPaymentInstrument) Validate() error {
	if v.present != nil {
		if !v.present["type"] {
			return errors.New("type: required property is missing")
		}
	}
	if v.Constraints != nil && len(v.Constraints) < 1 {
		return errors.New("constraints: has fewer than minProperties 1")
	}
	return nil
}
