// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/card_credential.json (spec release/2026-04-08@a2d8bf0)

package types

import (
	"encoding/json"
	"errors"
	"unicode/utf8"
)

// CardCredential A card credential containing sensitive payment card details including raw Primary Account Numbers (PANs). This credential type MUST NOT be used for checkout, only with payment handlers that tokenize or encrypt credentials. CRITICAL: Both parties handling CardCredential (sender and receiver) MUST be PCI DSS compliant. Transmission MUST use HTTPS/TLS with strong cipher suites.
type CardCredential struct {
	// The type of card number. Network tokens are preferred with fallback to FPAN. See PCI Scope for more details.
	CardNumberType string `json:"card_number_type"`
	// Cryptogram provided with network tokens.
	Cryptogram *string `json:"cryptogram,omitzero"`
	// Card CVC number.
	Cvc *string `json:"cvc,omitzero"`
	// Electronic Commerce Indicator / Security Level Indicator provided with network tokens.
	EciValue *string `json:"eci_value,omitzero"`
	// The month of the card's expiration date (1-12).
	ExpiryMonth *int64 `json:"expiry_month,omitzero"`
	// The year of the card's expiration date.
	ExpiryYear *int64 `json:"expiry_year,omitzero"`
	// Cardholder name.
	Name *string `json:"name,omitzero"`
	// Card number.
	Number *string `json:"number,omitzero"`
	// The credential type identifier for card credentials.
	Type string `json:"type"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *CardCredential) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("CardCredential: null is not a valid object")
	}
	type CardCredentialAlias CardCredential
	var named CardCredentialAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = CardCredential(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"card_number_type", "type"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "card_number_type")
	delete(all, "cryptogram")
	delete(all, "cvc")
	delete(all, "eci_value")
	delete(all, "expiry_month")
	delete(all, "expiry_year")
	delete(all, "name")
	delete(all, "number")
	delete(all, "type")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v CardCredential) MarshalJSON() ([]byte, error) {
	type CardCredentialAlias CardCredential
	named, err := json.Marshal(CardCredentialAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *CardCredential) Validate() error {
	if v.present != nil {
		if !v.present["card_number_type"] {
			return errors.New("card_number_type: required property is missing")
		}
		if !v.present["type"] {
			return errors.New("type: required property is missing")
		}
	}
	if v.CardNumberType != "fpan" && v.CardNumberType != "network_token" && v.CardNumberType != "dpan" {
		return errors.New("card_number_type: not one of the permitted values")
	}
	if v.Cvc != nil && utf8.RuneCountInString(*v.Cvc) > 4 {
		return errors.New("cvc: exceeds maxLength 4")
	}
	if v.Type != "card" {
		return errors.New("type: must be \"card\"")
	}
	return nil
}
