// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/error_code.json (spec release/2026-04-08@a2d8bf0)

package types

import (
	"encoding/json"
	"errors"
)

// ErrorCode Error code identifying the type of error. Standard errors are defined in specification (see examples), and have standardized semantics; freeform codes are permitted.
type ErrorCode string

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *ErrorCode) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("ErrorCode: null is not a valid string")
	}
	type ErrorCodeAlias ErrorCode
	var alias ErrorCodeAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = ErrorCode(alias)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *ErrorCode) Validate() error {
	return nil
}
