// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/fulfillment_destination_create_request.json (spec release/2026-04-08@a2d8bf0)

package types

import "encoding/json"

// FulfillmentDestinationCreateRequest A destination for fulfillment.
//
// The schema also declares 2 oneOf variants that narrow or replace
// these fields; they are not modeled as distinct types yet (phase 4),
// so this type reflects only the shared base.
type FulfillmentDestinationCreateRequest struct {

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *FulfillmentDestinationCreateRequest) UnmarshalJSON(data []byte) error {
	type FulfillmentDestinationCreateRequestAlias FulfillmentDestinationCreateRequest
	var named FulfillmentDestinationCreateRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = FulfillmentDestinationCreateRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v FulfillmentDestinationCreateRequest) MarshalJSON() ([]byte, error) {
	type FulfillmentDestinationCreateRequestAlias FulfillmentDestinationCreateRequest
	named, err := json.Marshal(FulfillmentDestinationCreateRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *FulfillmentDestinationCreateRequest) Validate() error {
	return nil
}
