// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/fulfillment_available_method_update_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// FulfillmentAvailableMethodUpdateRequest Inventory availability hint for a fulfillment method type.
type FulfillmentAvailableMethodUpdateRequest map[string]any

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *FulfillmentAvailableMethodUpdateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("FulfillmentAvailableMethodUpdateRequest: null is not a valid object")
	}
	type FulfillmentAvailableMethodUpdateRequestAlias FulfillmentAvailableMethodUpdateRequest
	var alias FulfillmentAvailableMethodUpdateRequestAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = FulfillmentAvailableMethodUpdateRequest(alias)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *FulfillmentAvailableMethodUpdateRequest) Validate() error {
	return nil
}
