// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/fulfillment_event_create_request.json (spec release/2026-04-08@a2d8bf0)

package types

import (
	"encoding/json"
	"errors"
)

// FulfillmentEventCreateRequest Append-only fulfillment event representing an actual shipment. References line items by ID.
type FulfillmentEventCreateRequest struct {
	// Carrier name (e.g., 'FedEx', 'USPS').
	Carrier *string `json:"carrier,omitzero"`
	// Human-readable description of the shipment status or delivery information (e.g., 'Delivered to front door', 'Out for delivery').
	Description *string `json:"description,omitzero"`
	// Fulfillment event identifier.
	ID string `json:"id"`
	// Which line items and quantities are fulfilled in this event.
	LineItems []FulfillmentEventCreateRequestLineItemsItem `json:"line_items"`
	// RFC 3339 timestamp when this fulfillment event occurred.
	//
	// Not enforced yet (phase 4): format.
	OccurredAt string `json:"occurred_at"`
	// Carrier tracking number (required if type != processing).
	TrackingNumber *string `json:"tracking_number,omitzero"`
	// URL to track this shipment (required if type != processing).
	//
	// Not enforced yet (phase 4): format.
	TrackingURL *string `json:"tracking_url,omitzero"`
	// Fulfillment event type. Common values include: processing (preparing to ship), shipped (handed to carrier), in_transit (in delivery network), delivered (received by buyer), failed_attempt (delivery attempt failed), canceled (fulfillment canceled), undeliverable (cannot be delivered), returned_to_sender (returned to merchant).
	Type string `json:"type"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *FulfillmentEventCreateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("FulfillmentEventCreateRequest: null is not a valid object")
	}
	type FulfillmentEventCreateRequestAlias FulfillmentEventCreateRequest
	var named FulfillmentEventCreateRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = FulfillmentEventCreateRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 4)
	for _, name := range []string{"id", "line_items", "occurred_at", "type"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "carrier")
	delete(all, "description")
	delete(all, "id")
	delete(all, "line_items")
	delete(all, "occurred_at")
	delete(all, "tracking_number")
	delete(all, "tracking_url")
	delete(all, "type")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v FulfillmentEventCreateRequest) MarshalJSON() ([]byte, error) {
	type FulfillmentEventCreateRequestAlias FulfillmentEventCreateRequest
	named, err := json.Marshal(FulfillmentEventCreateRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *FulfillmentEventCreateRequest) Validate() error {
	if v.present != nil {
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
		if !v.present["line_items"] {
			return errors.New("line_items: required property is missing")
		}
		if !v.present["occurred_at"] {
			return errors.New("occurred_at: required property is missing")
		}
		if !v.present["type"] {
			return errors.New("type: required property is missing")
		}
	}
	for i := range v.LineItems {
		if err := v.LineItems[i].Validate(); err != nil {
			return err
		}
	}
	return nil
}

// FulfillmentEventCreateRequestLineItemsItem is generated from shopping/types/fulfillment_event_create_request.json.
type FulfillmentEventCreateRequestLineItemsItem struct {
	// Line item ID reference.
	ID string `json:"id"`
	// Quantity fulfilled in this event.
	Quantity int64 `json:"quantity"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *FulfillmentEventCreateRequestLineItemsItem) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("FulfillmentEventCreateRequestLineItemsItem: null is not a valid object")
	}
	type FulfillmentEventCreateRequestLineItemsItemAlias FulfillmentEventCreateRequestLineItemsItem
	var named FulfillmentEventCreateRequestLineItemsItemAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = FulfillmentEventCreateRequestLineItemsItem(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"id", "quantity"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "id")
	delete(all, "quantity")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v FulfillmentEventCreateRequestLineItemsItem) MarshalJSON() ([]byte, error) {
	type FulfillmentEventCreateRequestLineItemsItemAlias FulfillmentEventCreateRequestLineItemsItem
	named, err := json.Marshal(FulfillmentEventCreateRequestLineItemsItemAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *FulfillmentEventCreateRequestLineItemsItem) Validate() error {
	if v.present != nil {
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
		if !v.present["quantity"] {
			return errors.New("quantity: required property is missing")
		}
	}
	if v.Quantity < 1 {
		return errors.New("quantity: below minimum 1")
	}
	return nil
}
