// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/fulfillment_option_base_create_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// FulfillmentOptionBaseCreateRequest Common base for a fulfillment option: an addressable, renderable choice (e.g. Standard, Express). Catalog uses this base directly; checkout composes it with cost and timing.
type FulfillmentOptionBaseCreateRequest map[string]any

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *FulfillmentOptionBaseCreateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("FulfillmentOptionBaseCreateRequest: null is not a valid object")
	}
	type FulfillmentOptionBaseCreateRequestAlias FulfillmentOptionBaseCreateRequest
	var alias FulfillmentOptionBaseCreateRequestAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = FulfillmentOptionBaseCreateRequest(alias)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *FulfillmentOptionBaseCreateRequest) Validate() error {
	return nil
}
