// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/fulfillment_destination.json (spec release/2026-04-08@a2d8bf0)

package types

import (
	"encoding/json"
	"errors"
)

// FulfillmentDestination A destination for fulfillment.
//
// FulfillmentDestination is a closed oneOf union: exactly one field is set.
type FulfillmentDestination struct {
	RetailLocation      *RetailLocation      `json:"-"`
	ShippingDestination *ShippingDestination `json:"-"`

	// matched counts the alternatives the decoded input satisfied.
	// oneOf permits exactly one, so more than one is a violation that
	// only decoding can observe. Zero means this value was never
	// decoded from JSON.
	matched int
}

// UnmarshalJSON decodes the union member that accepts the input,
// preferring one that also validates.
func (v *FulfillmentDestination) UnmarshalJSON(data []byte) error {
	var matched, fallback FulfillmentDestination
	matches := 0
	parsed := false
	var asRetailLocation RetailLocation
	if err := json.Unmarshal(data, &asRetailLocation); err == nil {
		if asRetailLocation.Validate() == nil {
			if matches == 0 {
				matched = FulfillmentDestination{RetailLocation: &asRetailLocation}
			}
			matches++
		}
		if !parsed {
			fallback, parsed = FulfillmentDestination{RetailLocation: &asRetailLocation}, true
		}
	}
	var asShippingDestination ShippingDestination
	if err := json.Unmarshal(data, &asShippingDestination); err == nil {
		if asShippingDestination.Validate() == nil {
			if matches == 0 {
				matched = FulfillmentDestination{ShippingDestination: &asShippingDestination}
			}
			matches++
		}
		if !parsed {
			fallback, parsed = FulfillmentDestination{ShippingDestination: &asShippingDestination}, true
		}
	}
	if matches > 0 {
		*v = matched
		v.matched = matches
		return nil
	}
	if parsed {
		*v = fallback
		v.matched = 1
		return nil
	}
	return errors.New("FulfillmentDestination: no union member accepted the input")
}

// MarshalJSON encodes whichever union member is set.
func (v FulfillmentDestination) MarshalJSON() ([]byte, error) {
	if v.RetailLocation != nil {
		return json.Marshal(v.RetailLocation)
	}
	if v.ShippingDestination != nil {
		return json.Marshal(v.ShippingDestination)
	}
	return nil, errors.New("FulfillmentDestination: no union member is set")
}

// Validate reports the first constraint violation, or nil.
func (v *FulfillmentDestination) Validate() error {
	if v.matched > 1 {
		return errors.New("FulfillmentDestination: input satisfies more than one alternative, and oneOf permits exactly one")
	}
	if v.RetailLocation != nil {
		return v.RetailLocation.Validate()
	}
	if v.ShippingDestination != nil {
		return v.ShippingDestination.Validate()
	}
	return nil
}
