// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/fulfillment_update_request.json (spec release/2026-04-08@a2d8bf0)

package types

import "encoding/json"

// FulfillmentUpdateRequest Container for fulfillment methods and availability.
type FulfillmentUpdateRequest struct {
	// Fulfillment methods for cart items.
	Methods []FulfillmentMethodUpdateRequest `json:"methods,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *FulfillmentUpdateRequest) UnmarshalJSON(data []byte) error {
	type FulfillmentUpdateRequestAlias FulfillmentUpdateRequest
	var named FulfillmentUpdateRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = FulfillmentUpdateRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "methods")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v FulfillmentUpdateRequest) MarshalJSON() ([]byte, error) {
	type FulfillmentUpdateRequestAlias FulfillmentUpdateRequest
	named, err := json.Marshal(FulfillmentUpdateRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *FulfillmentUpdateRequest) Validate() error {
	for i := range v.Methods {
		if err := v.Methods[i].Validate(); err != nil {
			return err
		}
	}
	return nil
}
