// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/fulfillment_destination_update_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// FulfillmentDestinationUpdateRequest A destination for fulfillment.
//
// Not enforced yet on the object itself: if, then.
type FulfillmentDestinationUpdateRequest struct {
	// Fulfillment destination identifier.
	ID *string `json:"id,omitzero"`
	// Destination contract discriminator. Required in Business responses and optional in Platform requests. Well-known values: `shipping_address`, `business_location`. The enclosing method contract defines request defaults and which fields the Platform may write; negotiated extensions define additional values.
	Type *string `json:"type,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *FulfillmentDestinationUpdateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("FulfillmentDestinationUpdateRequest: null is not a valid object")
	}
	type FulfillmentDestinationUpdateRequestAlias FulfillmentDestinationUpdateRequest
	var named FulfillmentDestinationUpdateRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = FulfillmentDestinationUpdateRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "id")
	delete(all, "type")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v FulfillmentDestinationUpdateRequest) MarshalJSON() ([]byte, error) {
	type FulfillmentDestinationUpdateRequestAlias FulfillmentDestinationUpdateRequest
	named, err := json.Marshal(FulfillmentDestinationUpdateRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *FulfillmentDestinationUpdateRequest) Validate() error {
	return nil
}
