// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/info_code.json (spec release/2026-04-08@a2d8bf0)

package types

// InfoCode Info code identifying the type of informational message. Standard codes are defined in capability specs (see examples), and have standardized semantics; freeform codes are permitted.
type InfoCode string

// Validate reports the first constraint violation, or nil.
func (v *InfoCode) Validate() error {
	return nil
}
