// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/item.json (spec release/2026-04-08@a2d8bf0)

package types

import (
	"encoding/json"
	"errors"
)

// Item is generated from shopping/types/item.json.
type Item struct {
	// The product identifier, often the SKU, required to resolve the product details associated with this line item. Should be recognized by both the Platform, and the Business.
	ID string `json:"id"`
	// Product image URI.
	//
	// Annotation only in draft 2020-12, so not asserted: format.
	ImageURL *string `json:"image_url,omitzero"`
	// Unit price in ISO 4217 minor units.
	Price Amount `json:"price"`
	// Product title.
	Title string `json:"title"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *Item) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("Item: null is not a valid object")
	}
	type ItemAlias Item
	var named ItemAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = Item(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 3)
	for _, name := range []string{"id", "price", "title"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "id")
	delete(all, "image_url")
	delete(all, "price")
	delete(all, "title")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v Item) MarshalJSON() ([]byte, error) {
	type ItemAlias Item
	named, err := json.Marshal(ItemAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *Item) Validate() error {
	if v.present != nil {
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
		if !v.present["price"] {
			return errors.New("price: required property is missing")
		}
		if !v.present["title"] {
			return errors.New("title: required property is missing")
		}
	}
	if err := v.Price.Validate(); err != nil {
		return err
	}
	return nil
}
