// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/item_create_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
	commontypes "github.com/chaz8081/ucp-go/common/types"
)

// ItemCreateRequest is generated from shopping/types/item_create_request.json.
type ItemCreateRequest struct {
	// The product identifier, often the SKU, required to resolve the product details associated with this line item. Should be recognized by both the Platform, and the Business.
	ID string `json:"id"`
	// Sale basis this item's `quantity` is denominated in. On an authoritative Business response, absence encodes the default `each` machine identity (`C62`, 0); the Business MUST include this descriptor for every non-`each` response. On Platform requests, omission makes no assertion: the Business interprets `quantity` using the item's authoritative sale basis. If the Platform includes this descriptor, it asserts the unit-descriptor machine identity. The Business MUST compare that machine identity (`unit`, effective `scale`), ignore `display_text` and `increment`, and resolve a mismatch by conversion surfaced as a visible line revision with a warning, or by rejection with a recoverable business outcome; silent reinterpretation is forbidden. An explicit `C62` descriptor at effective scale 0 matches an authoritative basis represented by an absent descriptor.
	QuantityUnit *commontypes.QuantityUnitCreateRequest `json:"quantity_unit,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *ItemCreateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("ItemCreateRequest: null is not a valid object")
	}
	type ItemCreateRequestAlias ItemCreateRequest
	var named ItemCreateRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = ItemCreateRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"id"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "id")
	delete(all, "quantity_unit")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v ItemCreateRequest) MarshalJSON() ([]byte, error) {
	type ItemCreateRequestAlias ItemCreateRequest
	named, err := json.Marshal(ItemCreateRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *ItemCreateRequest) Validate() error {
	if v.present != nil {
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
	}
	if v.QuantityUnit != nil {
		if err := v.QuantityUnit.Validate(); err != nil {
			return err
		}
	}
	return nil
}
