// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/option_value.json (spec release/2026-04-08@a2d8bf0)

package types

import (
	"encoding/json"
	"errors"
)

// OptionValue A selectable value for a product option.
type OptionValue struct {
	// Optional server-assigned identifier for this option value. When present in a selected_option, the server SHOULD use it for matching instead of label.
	ID *string `json:"id,omitzero"`
	// Display text for this option value (e.g., 'Small', 'Blue').
	Label string `json:"label"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *OptionValue) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("OptionValue: null is not a valid object")
	}
	type OptionValueAlias OptionValue
	var named OptionValueAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = OptionValue(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"label"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "id")
	delete(all, "label")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v OptionValue) MarshalJSON() ([]byte, error) {
	type OptionValueAlias OptionValue
	named, err := json.Marshal(OptionValueAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *OptionValue) Validate() error {
	if v.present != nil {
		if !v.present["label"] {
			return errors.New("label: required property is missing")
		}
	}
	return nil
}
