// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/payment_identity.json (spec release/2026-04-08@a2d8bf0)

package types

import (
	"encoding/json"
	"errors"
)

// PaymentIdentity Identity of a participant for token binding. The access_token uniquely identifies the participant who tokens should be bound to.
type PaymentIdentity struct {
	// Unique identifier for this participant, obtained during onboarding with the tokenizer.
	AccessToken string `json:"access_token"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *PaymentIdentity) UnmarshalJSON(data []byte) error {
	type PaymentIdentityAlias PaymentIdentity
	var named PaymentIdentityAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = PaymentIdentity(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"access_token"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "access_token")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v PaymentIdentity) MarshalJSON() ([]byte, error) {
	type PaymentIdentityAlias PaymentIdentity
	named, err := json.Marshal(PaymentIdentityAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *PaymentIdentity) Validate() error {
	if v.present != nil {
		if !v.present["access_token"] {
			return errors.New("access_token: required property is missing")
		}
	}
	return nil
}
