// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/payment_instrument_update_request.json (spec release/2026-04-08@a2d8bf0)

package types

import (
	"encoding/json"
	"errors"
)

// PaymentInstrumentUpdateRequest The base definition for any payment instrument. It links the instrument to a specific payment handler.
type PaymentInstrumentUpdateRequest struct {
	// The billing address associated with this payment method.
	BillingAddress *PostalAddressUpdateRequest     `json:"billing_address,omitzero"`
	Credential     *PaymentCredentialUpdateRequest `json:"credential,omitzero"`
	// Display information for this payment instrument. Each payment instrument schema defines its specific display properties, as outlined by the payment handler.
	Display map[string]any `json:"display,omitzero"`
	// The unique identifier for the handler instance that produced this instrument. This corresponds to the 'id' field in the Payment Handler definition.
	HandlerID string `json:"handler_id"`
	// A unique identifier for this instrument instance, assigned by the platform.
	ID string `json:"id"`
	// The broad category of the instrument (e.g., 'card', 'tokenized_card'). Specific schemas will constrain this to a constant value.
	Type string `json:"type"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *PaymentInstrumentUpdateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("PaymentInstrumentUpdateRequest: null is not a valid object")
	}
	type PaymentInstrumentUpdateRequestAlias PaymentInstrumentUpdateRequest
	var named PaymentInstrumentUpdateRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = PaymentInstrumentUpdateRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 3)
	for _, name := range []string{"handler_id", "id", "type"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "billing_address")
	delete(all, "credential")
	delete(all, "display")
	delete(all, "handler_id")
	delete(all, "id")
	delete(all, "type")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v PaymentInstrumentUpdateRequest) MarshalJSON() ([]byte, error) {
	type PaymentInstrumentUpdateRequestAlias PaymentInstrumentUpdateRequest
	named, err := json.Marshal(PaymentInstrumentUpdateRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *PaymentInstrumentUpdateRequest) Validate() error {
	if v.present != nil {
		if !v.present["handler_id"] {
			return errors.New("handler_id: required property is missing")
		}
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
		if !v.present["type"] {
			return errors.New("type: required property is missing")
		}
	}
	if v.BillingAddress != nil {
		if err := v.BillingAddress.Validate(); err != nil {
			return err
		}
	}
	if v.Credential != nil {
		if err := v.Credential.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// PaymentInstrumentUpdateRequestSelectedPaymentInstrument A payment instrument with selection state.
type PaymentInstrumentUpdateRequestSelectedPaymentInstrument struct {
	// The billing address associated with this payment method.
	BillingAddress *PostalAddressUpdateRequest     `json:"billing_address,omitzero"`
	Credential     *PaymentCredentialUpdateRequest `json:"credential,omitzero"`
	// Display information for this payment instrument. Each payment instrument schema defines its specific display properties, as outlined by the payment handler.
	Display map[string]any `json:"display,omitzero"`
	// The unique identifier for the handler instance that produced this instrument. This corresponds to the 'id' field in the Payment Handler definition.
	HandlerID string `json:"handler_id"`
	// A unique identifier for this instrument instance, assigned by the platform.
	ID string `json:"id"`
	// Whether this instrument is selected by the user.
	Selected *bool `json:"selected,omitzero"`
	// The broad category of the instrument (e.g., 'card', 'tokenized_card'). Specific schemas will constrain this to a constant value.
	Type string `json:"type"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *PaymentInstrumentUpdateRequestSelectedPaymentInstrument) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("PaymentInstrumentUpdateRequestSelectedPaymentInstrument: null is not a valid object")
	}
	type PaymentInstrumentUpdateRequestSelectedPaymentInstrumentAlias PaymentInstrumentUpdateRequestSelectedPaymentInstrument
	var named PaymentInstrumentUpdateRequestSelectedPaymentInstrumentAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = PaymentInstrumentUpdateRequestSelectedPaymentInstrument(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 3)
	for _, name := range []string{"handler_id", "id", "type"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "billing_address")
	delete(all, "credential")
	delete(all, "display")
	delete(all, "handler_id")
	delete(all, "id")
	delete(all, "selected")
	delete(all, "type")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v PaymentInstrumentUpdateRequestSelectedPaymentInstrument) MarshalJSON() ([]byte, error) {
	type PaymentInstrumentUpdateRequestSelectedPaymentInstrumentAlias PaymentInstrumentUpdateRequestSelectedPaymentInstrument
	named, err := json.Marshal(PaymentInstrumentUpdateRequestSelectedPaymentInstrumentAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *PaymentInstrumentUpdateRequestSelectedPaymentInstrument) Validate() error {
	if v.present != nil {
		if !v.present["handler_id"] {
			return errors.New("handler_id: required property is missing")
		}
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
		if !v.present["type"] {
			return errors.New("type: required property is missing")
		}
	}
	if v.BillingAddress != nil {
		if err := v.BillingAddress.Validate(); err != nil {
			return err
		}
	}
	if v.Credential != nil {
		if err := v.Credential.Validate(); err != nil {
			return err
		}
	}
	return nil
}
