// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/rating.json (spec release/2026-04-08@a2d8bf0)

package types

import (
	"encoding/json"
	"errors"
)

// Rating Product rating aggregate.
type Rating struct {
	// Number of reviews contributing to the rating.
	Count *int64 `json:"count,omitzero"`
	// Maximum value on the rating scale (e.g., 5 for 5-star).
	ScaleMax float64 `json:"scale_max"`
	// Minimum value on the rating scale (e.g., 1 for 1-5 stars).
	ScaleMin *float64 `json:"scale_min,omitzero"`
	// Average rating value.
	Value float64 `json:"value"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *Rating) UnmarshalJSON(data []byte) error {
	type RatingAlias Rating
	var named RatingAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = Rating(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"scale_max", "value"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "count")
	delete(all, "scale_max")
	delete(all, "scale_min")
	delete(all, "value")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v Rating) MarshalJSON() ([]byte, error) {
	type RatingAlias Rating
	named, err := json.Marshal(RatingAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *Rating) Validate() error {
	if v.present != nil {
		if !v.present["scale_max"] {
			return errors.New("scale_max: required property is missing")
		}
		if !v.present["value"] {
			return errors.New("value: required property is missing")
		}
	}
	if v.Count != nil && *v.Count < 0 {
		return errors.New("count: below minimum 0")
	}
	if v.ScaleMax < 1 {
		return errors.New("scale_max: below minimum 1")
	}
	if v.ScaleMin != nil && *v.ScaleMin < 0 {
		return errors.New("scale_min: below minimum 0")
	}
	if v.Value < 0 {
		return errors.New("value: below minimum 0")
	}
	return nil
}
