// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/reverse_domain_name.json (spec release/2026-04-08@a2d8bf0)

package types

import (
	"errors"
	"regexp"
	"sync"
)

// ReverseDomainName Reverse-domain identifier used for collision-safe namespacing of capabilities, services, handlers, eligibility claims, and extension-contributed keys. Must contain at least two dot-separated segments (e.g., 'dev.ucp.shopping.checkout', 'com.example.loyalty_gold').
type ReverseDomainName string

var pattern_ReverseDomainName = sync.OnceValue(func() *regexp.Regexp { return regexp.MustCompile("^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$") })

// Validate reports the first constraint violation, or nil.
func (v *ReverseDomainName) Validate() error {
	if !pattern_ReverseDomainName().MatchString(string(*v)) {
		return errors.New("ReverseDomainName: does not match pattern")
	}
	return nil
}
