// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/selected_option.json (spec release/2026-04-08@a2d8bf0)

package types

import (
	"encoding/json"
	"errors"
)

// SelectedOption A specific option selection on a variant (e.g., Size: Large).
type SelectedOption struct {
	// Optional option value identifier from option_value.id. When present, the server SHOULD use it for matching; name and label remain required for display.
	ID *string `json:"id,omitzero"`
	// Selected option label (e.g., 'Large').
	Label string `json:"label"`
	// Option name (e.g., 'Size').
	Name string `json:"name"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *SelectedOption) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("SelectedOption: null is not a valid object")
	}
	type SelectedOptionAlias SelectedOption
	var named SelectedOptionAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = SelectedOption(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"label", "name"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "id")
	delete(all, "label")
	delete(all, "name")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v SelectedOption) MarshalJSON() ([]byte, error) {
	type SelectedOptionAlias SelectedOption
	named, err := json.Marshal(SelectedOptionAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *SelectedOption) Validate() error {
	if v.present != nil {
		if !v.present["label"] {
			return errors.New("label: required property is missing")
		}
		if !v.present["name"] {
			return errors.New("name: required property is missing")
		}
	}
	return nil
}
