// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/shipping_destination_create_request.json (spec release/2026-04-08@a2d8bf0)

package types

import "encoding/json"

// ShippingDestinationCreateRequest Shipping destination.
type ShippingDestinationCreateRequest struct {
	// The country. Recommended to be in 2-letter ISO 3166-1 alpha-2 format, for example "US". For backward compatibility, a 3-letter ISO 3166-1 alpha-3 country code such as "SGP" or a full country name such as "Singapore" can also be used.
	AddressCountry *string `json:"address_country,omitzero"`
	// The locality in which the street address is, and which is in the region. For example, Mountain View.
	AddressLocality *string `json:"address_locality,omitzero"`
	// The region in which the locality is, and which is in the country. Required for applicable countries (i.e. state in US, province in CA). For example, California or another appropriate first-level Administrative division.
	AddressRegion *string `json:"address_region,omitzero"`
	// An address extension such as an apartment number, C/O or alternative name.
	ExtendedAddress *string `json:"extended_address,omitzero"`
	// Optional. First name of the contact associated with the address.
	FirstName *string `json:"first_name,omitzero"`
	// ID specific to this shipping destination.
	ID *string `json:"id,omitzero"`
	// Optional. Last name of the contact associated with the address.
	LastName *string `json:"last_name,omitzero"`
	// Optional. Phone number of the contact associated with the address.
	PhoneNumber *string `json:"phone_number,omitzero"`
	// The postal code. For example, 94043.
	PostalCode *string `json:"postal_code,omitzero"`
	// The street address.
	StreetAddress *string `json:"street_address,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *ShippingDestinationCreateRequest) UnmarshalJSON(data []byte) error {
	type ShippingDestinationCreateRequestAlias ShippingDestinationCreateRequest
	var named ShippingDestinationCreateRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = ShippingDestinationCreateRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "address_country")
	delete(all, "address_locality")
	delete(all, "address_region")
	delete(all, "extended_address")
	delete(all, "first_name")
	delete(all, "id")
	delete(all, "last_name")
	delete(all, "phone_number")
	delete(all, "postal_code")
	delete(all, "street_address")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v ShippingDestinationCreateRequest) MarshalJSON() ([]byte, error) {
	type ShippingDestinationCreateRequestAlias ShippingDestinationCreateRequest
	named, err := json.Marshal(ShippingDestinationCreateRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *ShippingDestinationCreateRequest) Validate() error {
	return nil
}
