// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/signed_amount.json (spec release/2026-04-08@a2d8bf0)

package types

// SignedAmount Monetary amount in the currency's minor unit as defined by ISO 4217. Refer to the currency's exponent to determine minor-to-major ratio (e.g., 2 for USD, 0 for JPY, 3 for KWD). May be negative — the sign is intrinsic to the value (e.g., discounts are negative, charges are positive).
type SignedAmount int64

// Validate reports the first constraint violation, or nil.
func (v *SignedAmount) Validate() error {
	return nil
}
