// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/totals_create_request.json (spec release/2026-04-08@a2d8bf0)

package types

import (
	"encoding/json"
	"errors"
)

// TotalsCreateRequest Pricing breakdown provided by the business. MUST contain exactly one subtotal and one total entry. Detail types (tax, fee, discount, fulfillment) may appear multiple times for itemization. Platforms MUST render all entries in order using display_text and amount.
//
// Not enforced yet: contains, maxContains, minContains.
type TotalsCreateRequest []map[string]any

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *TotalsCreateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("TotalsCreateRequest: null is not a valid array")
	}
	type TotalsCreateRequestAlias TotalsCreateRequest
	var alias TotalsCreateRequestAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = TotalsCreateRequest(alias)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *TotalsCreateRequest) Validate() error {
	return nil
}
