// Code generated by ucpgen. DO NOT EDIT.
// Source: shopping/types/total_create_request.json (spec release/2026-04-08@a2d8bf0)

package types

import "encoding/json"

// TotalCreateRequest A cost breakdown entry with a category, amount, and optional display text.
//
// Not enforced yet (phase 4) on the object itself: if, then.
type TotalCreateRequest struct {

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *TotalCreateRequest) UnmarshalJSON(data []byte) error {
	type TotalCreateRequestAlias TotalCreateRequest
	var named TotalCreateRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = TotalCreateRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v TotalCreateRequest) MarshalJSON() ([]byte, error) {
	type TotalCreateRequestAlias TotalCreateRequest
	named, err := json.Marshal(TotalCreateRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *TotalCreateRequest) Validate() error {
	return nil
}
