// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/actions.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
	"regexp"
	"sync"
	"unicode/utf8"
)

// Actions Outstanding extension-defined Action instances, keyed by reverse-domain Action type, not extension name.
type Actions map[string][]ActionsInstance

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *Actions) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("Actions: null is not a valid object")
	}
	type ActionsAlias Actions
	var alias ActionsAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = Actions(alias)
	return nil
}

var pattern_Actions_Key = sync.OnceValue(func() *regexp.Regexp {
	return regexp.MustCompile("^[a-z](?:[a-z0-9-]*[a-z0-9])?(?:\\.[a-z0-9](?:[a-z0-9_-]*[a-z0-9_])?)+$")
})

// Validate reports the first constraint violation, or nil.
func (v *Actions) Validate() error {
	for k := range *v {
		if !pattern_Actions_Key().MatchString(string(k)) {
			return errors.New("Actions property name: does not match pattern")
		}
	}
	for _, m := range *v {
		for i1 := range m {
			if err := m[i1].Validate(); err != nil {
				return err
			}
		}
	}
	return nil
}

// ActionsInstance Common fields for one outstanding Action instance are id and optional config. The extension declaring the Action type defines type-specific processing data under config. Additional properties are permitted for forward compatibility.
type ActionsInstance struct {
	// Configuration defined by the extension that declares this Action type.
	Config map[string]any `json:"config,omitzero"`
	// Identifier for this Action instance.
	ID string `json:"id"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *ActionsInstance) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("ActionsInstance: null is not a valid object")
	}
	type ActionsInstanceAlias ActionsInstance
	var named ActionsInstanceAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = ActionsInstance(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"id"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "config")
	delete(all, "id")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v ActionsInstance) MarshalJSON() ([]byte, error) {
	type ActionsInstanceAlias ActionsInstance
	named, err := json.Marshal(ActionsInstanceAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *ActionsInstance) Validate() error {
	if v.present != nil {
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
	}
	if utf8.RuneCountInString(string(v.ID)) < 1 {
		return errors.New("id: is shorter than minLength 1")
	}
	return nil
}
