// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/constraint_expression.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// ConstraintExpression A closed JSON Schema Draft 2020-12 constraint expression with Object and Value Constraint positions.
type ConstraintExpression struct {
	// Alternative Object Constraints. The constrained object must satisfy at least one. A branch must be non-empty: an empty branch is satisfied by every object and neutralizes the alternation.
	Anyof []ConstraintExpression `json:"anyOf,omitzero"`
	// Constraints keyed by property name. Must be non-empty: an empty object applies no constraint.
	Properties map[string]json.RawMessage `json:"properties,omitzero"`
	// Property names required by the constrained object. Must be non-empty: an empty array applies no constraint.
	Required []string `json:"required,omitzero"`
}

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this a null document would decode
// to the zero value and validate as though it were a real object.
func (v *ConstraintExpression) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("ConstraintExpression: null is not a valid object")
	}
	type ConstraintExpressionAlias ConstraintExpression
	var named ConstraintExpressionAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = ConstraintExpression(named)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *ConstraintExpression) Validate() error {
	if v.Anyof != nil && len(v.Anyof) < 1 {
		return errors.New("anyOf: has fewer than minItems 1")
	}
	if v.Properties != nil && len(v.Properties) < 1 {
		return errors.New("properties: has fewer than minProperties 1")
	}
	if v.Required != nil && len(v.Required) < 1 {
		return errors.New("required: has fewer than minItems 1")
	}
	if v.Required != nil {
		{
			k2 := make(map[string]bool, len(v.Required))
			for _, k := range v.Required {
				if k2[k] {
					return errors.New("required: contains duplicate items")
				}
				k2[k] = true
			}
		}
	}
	for i := range v.Anyof {
		if err := v.Anyof[i].Validate(); err != nil {
			return err
		}
	}
	return nil
}

// ConstraintExpressionValueConstraint A Value Constraint containing `enum`, `const`, or both.
//
// The schema also declares 2 anyOf variants that narrow or replace
// these fields; they are not modeled as distinct types yet (phase 4),
// so this type reflects only the shared base.
type ConstraintExpressionValueConstraint struct {
	Const any `json:"const,omitzero"`
	// A non-empty array of unique JSON values.
	Enum []any `json:"enum,omitzero"`
}

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this a null document would decode
// to the zero value and validate as though it were a real object.
func (v *ConstraintExpressionValueConstraint) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("ConstraintExpressionValueConstraint: null is not a valid object")
	}
	type ConstraintExpressionValueConstraintAlias ConstraintExpressionValueConstraint
	var named ConstraintExpressionValueConstraintAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = ConstraintExpressionValueConstraint(named)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *ConstraintExpressionValueConstraint) Validate() error {
	if v.Enum != nil && len(v.Enum) < 1 {
		return errors.New("enum: has fewer than minItems 1")
	}
	if v.Enum != nil {
		{
			k2 := make(map[string]bool, len(v.Enum))
			for _, k := range v.Enum {
				k3, err := json.Marshal(k)
				if err != nil {
					return err
				}
				if k2[string(k3)] {
					return errors.New("enum: contains duplicate items")
				}
				k2[string(k3)] = true
			}
		}
	}
	return nil
}
