// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/daily_hour.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
	"regexp"
	"sync"
)

// DailyHour A regular weekly operating interval. Its `day`, `opens`, and `closes` are recurring local civil values interpreted in the containing Location's `timezone`. Multiple entries for the same day support split shifts.
//
// Not enforced yet on the object itself: dependentRequired.
type DailyHour struct {
	// Closing time in 24-hour HH:MM format.
	Closes string `json:"closes"`
	// A stable UCP day-of-week identifier for the day on which this recurring local civil-time interval begins in the containing Location's `timezone`. It is not localized display text.
	Day string `json:"day"`
	// Opening time in 24-hour HH:MM format.
	Opens string `json:"opens"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *DailyHour) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("DailyHour: null is not a valid object")
	}
	type DailyHourAlias DailyHour
	var named DailyHourAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = DailyHour(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 3)
	for _, name := range []string{"closes", "day", "opens"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "closes")
	delete(all, "day")
	delete(all, "opens")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v DailyHour) MarshalJSON() ([]byte, error) {
	type DailyHourAlias DailyHour
	named, err := json.Marshal(DailyHourAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

var pattern_DailyHour_Closes = sync.OnceValue(func() *regexp.Regexp { return regexp.MustCompile("^([01][0-9]|2[0-3]):[0-5][0-9]$") })

var pattern_DailyHour_Opens = sync.OnceValue(func() *regexp.Regexp { return regexp.MustCompile("^([01][0-9]|2[0-3]):[0-5][0-9]$") })

// Validate reports the first constraint violation, or nil.
func (v *DailyHour) Validate() error {
	if v.present != nil {
		if !v.present["closes"] {
			return errors.New("closes: required property is missing")
		}
		if !v.present["day"] {
			return errors.New("day: required property is missing")
		}
		if !v.present["opens"] {
			return errors.New("opens: required property is missing")
		}
	}
	if !pattern_DailyHour_Closes().MatchString(string(v.Closes)) {
		return errors.New("closes: does not match pattern")
	}
	if v.Day != "monday" && v.Day != "tuesday" && v.Day != "wednesday" && v.Day != "thursday" && v.Day != "friday" && v.Day != "saturday" && v.Day != "sunday" {
		return errors.New("day: not one of the permitted values")
	}
	if !pattern_DailyHour_Opens().MatchString(string(v.Opens)) {
		return errors.New("opens: does not match pattern")
	}
	return nil
}
