// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/daily_hour_create_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// DailyHourCreateRequest A regular weekly operating interval. Its `day`, `opens`, and `closes` are recurring local civil values interpreted in the containing Location's `timezone`. Multiple entries for the same day support split shifts.
//
// Not enforced yet: dependentRequired.
type DailyHourCreateRequest map[string]any

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *DailyHourCreateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("DailyHourCreateRequest: null is not a valid object")
	}
	type DailyHourCreateRequestAlias DailyHourCreateRequest
	var alias DailyHourCreateRequestAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = DailyHourCreateRequest(alias)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *DailyHourCreateRequest) Validate() error {
	return nil
}
