// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/error_code_create_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// ErrorCodeCreateRequest Error code identifying the type of error. Standard errors are defined in capability specifications (see examples) and have standardized semantics; freeform codes are permitted.
type ErrorCodeCreateRequest string

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *ErrorCodeCreateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("ErrorCodeCreateRequest: null is not a valid string")
	}
	type ErrorCodeCreateRequestAlias ErrorCodeCreateRequest
	var alias ErrorCodeCreateRequestAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = ErrorCodeCreateRequest(alias)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *ErrorCodeCreateRequest) Validate() error {
	return nil
}
