// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/error_response.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// ErrorResponse Generic error response when business logic prevents resource creation or failed to retrieve resource. Used when no valid resource can be established.
type ErrorResponse struct {
	// URL for buyer handoff or session recovery.
	//
	// Annotation only in draft 2020-12, so not asserted: format.
	ContinueURL *string `json:"continue_url,omitzero"`
	// Array of messages describing why the operation failed.
	Messages []Message `json:"messages"`
	// UCP protocol metadata. Status MUST be 'error' for error response.
	//
	// Carried as raw JSON rather than ucp.UCPMetadata: typing it would make
	// this package import the root package, which already imports
	// this one (Go forbids import cycles).
	UCP json.RawMessage `json:"ucp"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and records which of the
// required ones were present.
func (v *ErrorResponse) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("ErrorResponse: null is not a valid object")
	}
	type ErrorResponseAlias ErrorResponse
	var named ErrorResponseAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = ErrorResponse(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"messages", "ucp"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *ErrorResponse) Validate() error {
	if v.present != nil {
		if !v.present["messages"] {
			return errors.New("messages: required property is missing")
		}
		if !v.present["ucp"] {
			return errors.New("ucp: required property is missing")
		}
	}
	if len(v.Messages) < 1 {
		return errors.New("messages: has fewer than minItems 1")
	}
	for i := range v.Messages {
		if err := v.Messages[i].Validate(); err != nil {
			return err
		}
	}
	return nil
}
