// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/exception_hour_create_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// ExceptionHourCreateRequest A date-specific operating interval or full closure. Its `valid_from`, `valid_through`, `opens`, and `closes` are local civil values interpreted in the containing Location's `timezone`. Date bounds are inclusive.
//
// Not enforced yet: dependentRequired.
type ExceptionHourCreateRequest map[string]any

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *ExceptionHourCreateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("ExceptionHourCreateRequest: null is not a valid object")
	}
	type ExceptionHourCreateRequestAlias ExceptionHourCreateRequest
	var alias ExceptionHourCreateRequestAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = ExceptionHourCreateRequest(alias)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *ExceptionHourCreateRequest) Validate() error {
	return nil
}
