// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/geo_update_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// GeoUpdateRequest WGS 84 geographic coordinates in decimal degrees.
type GeoUpdateRequest struct {
	// WGS 84 latitude in decimal degrees.
	Latitude float64 `json:"latitude"`
	// WGS 84 longitude in decimal degrees.
	Longitude float64 `json:"longitude"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *GeoUpdateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("GeoUpdateRequest: null is not a valid object")
	}
	type GeoUpdateRequestAlias GeoUpdateRequest
	var named GeoUpdateRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = GeoUpdateRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"latitude", "longitude"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "latitude")
	delete(all, "longitude")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v GeoUpdateRequest) MarshalJSON() ([]byte, error) {
	type GeoUpdateRequestAlias GeoUpdateRequest
	named, err := json.Marshal(GeoUpdateRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *GeoUpdateRequest) Validate() error {
	if v.present != nil {
		if !v.present["latitude"] {
			return errors.New("latitude: required property is missing")
		}
		if !v.present["longitude"] {
			return errors.New("longitude: required property is missing")
		}
	}
	if v.Latitude > 90 {
		return errors.New("latitude: above maximum 90")
	}
	if v.Latitude < -90 {
		return errors.New("latitude: below minimum -90")
	}
	if v.Longitude > 180 {
		return errors.New("longitude: above maximum 180")
	}
	if v.Longitude < -180 {
		return errors.New("longitude: below minimum -180")
	}
	return nil
}
