// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/instrument_group.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// InstrumentGroup A constraint within an allowed combination that defines which instrument types can fill this group and how many are permitted.
type InstrumentGroup struct {
	// Maximum number of instruments allowed from this group. Defaults to 1. MUST be greater than or equal to `min`.
	Max *int64 `json:"max,omitzero"`
	// Minimum number of instruments required from this group. Defaults to 0 (optional).
	Min *int64 `json:"min,omitzero"`
	// Instrument types accepted by this group (OR logic). Any listed type qualifies.
	Types []string `json:"types"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *InstrumentGroup) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("InstrumentGroup: null is not a valid object")
	}
	type InstrumentGroupAlias InstrumentGroup
	var named InstrumentGroupAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = InstrumentGroup(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"types"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "max")
	delete(all, "min")
	delete(all, "types")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v InstrumentGroup) MarshalJSON() ([]byte, error) {
	type InstrumentGroupAlias InstrumentGroup
	named, err := json.Marshal(InstrumentGroupAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *InstrumentGroup) Validate() error {
	if v.present != nil {
		if !v.present["types"] {
			return errors.New("types: required property is missing")
		}
	}
	if v.Max != nil && *v.Max < 1 {
		return errors.New("max: below minimum 1")
	}
	if v.Min != nil && *v.Min < 0 {
		return errors.New("min: below minimum 0")
	}
	if len(v.Types) < 1 {
		return errors.New("types: has fewer than minItems 1")
	}
	return nil
}
