// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/location_filter.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
	"regexp"
	"sync"
	"unicode/utf8"
)

// LocationFilter Filter criteria to narrow Location Search and Lookup results. All supplied filters combine with AND.
type LocationFilter struct {
	// Filter by amenity identifier. A Location matches only when its `amenities` map contains every supplied identifier as an exact key; descriptions and namespace prefixes do not participate in matching.
	Amenities []AmenityType `json:"amenities,omitzero"`
	// Filter by operating hours, evaluated at the one supplied instant.
	Hours *LocationFilterHours `json:"hours,omitzero"`
	// Current item-availability filter. A candidate Location matches only when the Business can currently provide every referenced item at that Location; all references combine with AND.
	Items []string `json:"items,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *LocationFilter) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("LocationFilter: null is not a valid object")
	}
	type LocationFilterAlias LocationFilter
	var named LocationFilterAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = LocationFilter(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "amenities")
	delete(all, "hours")
	delete(all, "items")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v LocationFilter) MarshalJSON() ([]byte, error) {
	type LocationFilterAlias LocationFilter
	named, err := json.Marshal(LocationFilterAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *LocationFilter) Validate() error {
	if v.Items != nil && len(v.Items) < 1 {
		return errors.New("items: has fewer than minItems 1")
	}
	if v.Items != nil {
		{
			k2 := make(map[string]bool, len(v.Items))
			for _, k := range v.Items {
				if k2[k] {
					return errors.New("items: contains duplicate items")
				}
				k2[k] = true
			}
		}
	}
	if v.Items != nil {
		for _, k3 := range v.Items {
			if utf8.RuneCountInString(string(k3)) < 1 {
				return errors.New("items item: is shorter than minLength 1")
			}
		}
	}
	for i := range v.Amenities {
		if err := v.Amenities[i].Validate(); err != nil {
			return err
		}
	}
	if v.Hours != nil {
		if err := v.Hours.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// LocationFilterHours Filter by operating hours, evaluated at the one supplied instant.
type LocationFilterHours struct {
	// The RFC 3339 instant at which matching Locations must be open, expressed with `Z` or a numeric offset. The Platform selects the instant that represents the Buyer's intent. The Business evaluates it exactly as supplied using each Location's authoritative `timezone`; the supplied offset does not identify that timezone.
	//
	// Annotation only in draft 2020-12, so not asserted: format.
	OpenAt string `json:"open_at"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *LocationFilterHours) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("LocationFilterHours: null is not a valid object")
	}
	type LocationFilterHoursAlias LocationFilterHours
	var named LocationFilterHoursAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = LocationFilterHours(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"open_at"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "open_at")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v LocationFilterHours) MarshalJSON() ([]byte, error) {
	type LocationFilterHoursAlias LocationFilterHours
	named, err := json.Marshal(LocationFilterHoursAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

var pattern_LocationFilterHours_OpenAt = sync.OnceValue(func() *regexp.Regexp { return regexp.MustCompile("(?:[Zz]|[+-](?:[01][0-9]|2[0-3]):[0-5][0-9])$") })

// Validate reports the first constraint violation, or nil.
func (v *LocationFilterHours) Validate() error {
	if v.present != nil {
		if !v.present["open_at"] {
			return errors.New("open_at: required property is missing")
		}
	}
	if !pattern_LocationFilterHours_OpenAt().MatchString(string(v.OpenAt)) {
		return errors.New("open_at: does not match pattern")
	}
	return nil
}
