// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/location_update_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
	"unicode/utf8"
)

// LocationUpdateRequest The full, rich representation of a physical business location. Builds on the Location Summary schema with discovery-centric details such as geographic coordinates, operating hours, timezone, and amenities.
//
// Not enforced yet on the object itself: if, then.
type LocationUpdateRequest struct {
	// Stable, opaque, Business-scoped Location identifier.
	ID string `json:"id"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *LocationUpdateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("LocationUpdateRequest: null is not a valid object")
	}
	type LocationUpdateRequestAlias LocationUpdateRequest
	var named LocationUpdateRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = LocationUpdateRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"id"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "id")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v LocationUpdateRequest) MarshalJSON() ([]byte, error) {
	type LocationUpdateRequestAlias LocationUpdateRequest
	named, err := json.Marshal(LocationUpdateRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *LocationUpdateRequest) Validate() error {
	if v.present != nil {
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
	}
	return nil
}

// LocationUpdateRequestAmenity Buyer-facing presentation metadata for one amenity identifier. The containing map key, not this metadata, defines amenity identity and filter matching.
type LocationUpdateRequestAmenity struct {
	// Short, plain-text, buyer-facing label or phrase for the amenity, suitable for direct use in a compact list (e.g., 'Curbside pickup'). The Business SHOULD localize it for the request when possible. This content does not participate in amenity identity or filter matching.
	Description string `json:"description"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *LocationUpdateRequestAmenity) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("LocationUpdateRequestAmenity: null is not a valid object")
	}
	type LocationUpdateRequestAmenityAlias LocationUpdateRequestAmenity
	var named LocationUpdateRequestAmenityAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = LocationUpdateRequestAmenity(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"description"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "description")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v LocationUpdateRequestAmenity) MarshalJSON() ([]byte, error) {
	type LocationUpdateRequestAmenityAlias LocationUpdateRequestAmenity
	named, err := json.Marshal(LocationUpdateRequestAmenityAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *LocationUpdateRequestAmenity) Validate() error {
	if v.present != nil {
		if !v.present["description"] {
			return errors.New("description: required property is missing")
		}
	}
	if utf8.RuneCountInString(string(v.Description)) < 1 {
		return errors.New("description: is shorter than minLength 1")
	}
	return nil
}
