// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/location_summary_update_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// LocationSummaryUpdateRequest A summary of a physical business location.
type LocationSummaryUpdateRequest struct {
	// Stable, opaque, Business-scoped Location identifier.
	ID string `json:"id"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *LocationSummaryUpdateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("LocationSummaryUpdateRequest: null is not a valid object")
	}
	type LocationSummaryUpdateRequestAlias LocationSummaryUpdateRequest
	var named LocationSummaryUpdateRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = LocationSummaryUpdateRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"id"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "id")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v LocationSummaryUpdateRequest) MarshalJSON() ([]byte, error) {
	type LocationSummaryUpdateRequestAlias LocationSummaryUpdateRequest
	named, err := json.Marshal(LocationSummaryUpdateRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *LocationSummaryUpdateRequest) Validate() error {
	if v.present != nil {
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
	}
	return nil
}
