// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/locality_update_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// LocalityUpdateRequest A coarse geographic location — country, region, and postal code. A lightweight alternative to a full postal address.
type LocalityUpdateRequest struct {
	// The country, as a 2-letter ISO 3166-1 alpha-2 code (e.g. "US"). A 3-letter alpha-3 code or full country name MAY also be used.
	AddressCountry *string `json:"address_country,omitzero"`
	// The first-level administrative region within the country (e.g. a state or province such as California).
	AddressRegion *string `json:"address_region,omitzero"`
	// The postal code (e.g. "94043").
	PostalCode *string `json:"postal_code,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *LocalityUpdateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("LocalityUpdateRequest: null is not a valid object")
	}
	type LocalityUpdateRequestAlias LocalityUpdateRequest
	var named LocalityUpdateRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = LocalityUpdateRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "address_country")
	delete(all, "address_region")
	delete(all, "postal_code")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v LocalityUpdateRequest) MarshalJSON() ([]byte, error) {
	type LocalityUpdateRequestAlias LocalityUpdateRequest
	named, err := json.Marshal(LocalityUpdateRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *LocalityUpdateRequest) Validate() error {
	return nil
}
