// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/message.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// Message Container for error, warning, or info messages.
//
// Message is a closed oneOf union: one field is set, holding the
// alternative the input matched. The schema requires that exactly one
// alternative match.
type Message struct {
	MessageError   *MessageError   `json:"-"`
	MessageInfo    *MessageInfo    `json:"-"`
	MessageWarning *MessageWarning `json:"-"`

	// matched counts the alternatives the decoded input satisfied.
	// oneOf permits exactly one, so more than one is a violation that
	// only decoding can observe. Zero means this value was never
	// decoded from JSON.
	matched int
}

// UnmarshalJSON decodes the union member that accepts the input,
// preferring one that also validates.
func (v *Message) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("Message: null is not a valid object")
	}
	var matched, fallback Message
	matches := 0
	parsed := false
	var asMessageError MessageError
	if err := json.Unmarshal(data, &asMessageError); err == nil {
		if asMessageError.Validate() == nil {
			if matches == 0 {
				matched = Message{MessageError: &asMessageError}
			}
			matches++
		}
		if !parsed {
			fallback, parsed = Message{MessageError: &asMessageError}, true
		}
	}
	var asMessageInfo MessageInfo
	if err := json.Unmarshal(data, &asMessageInfo); err == nil {
		if asMessageInfo.Validate() == nil {
			if matches == 0 {
				matched = Message{MessageInfo: &asMessageInfo}
			}
			matches++
		}
		if !parsed {
			fallback, parsed = Message{MessageInfo: &asMessageInfo}, true
		}
	}
	var asMessageWarning MessageWarning
	if err := json.Unmarshal(data, &asMessageWarning); err == nil {
		if asMessageWarning.Validate() == nil {
			if matches == 0 {
				matched = Message{MessageWarning: &asMessageWarning}
			}
			matches++
		}
		if !parsed {
			fallback, parsed = Message{MessageWarning: &asMessageWarning}, true
		}
	}
	if matches > 0 {
		*v = matched
		v.matched = matches
		return nil
	}
	if parsed {
		*v = fallback
		v.matched = 1
		return nil
	}
	return errors.New("Message: no union member accepted the input")
}

// MarshalJSON encodes whichever union member is set.
func (v Message) MarshalJSON() ([]byte, error) {
	if v.MessageError != nil {
		return json.Marshal(v.MessageError)
	}
	if v.MessageInfo != nil {
		return json.Marshal(v.MessageInfo)
	}
	if v.MessageWarning != nil {
		return json.Marshal(v.MessageWarning)
	}
	return nil, errors.New("Message: no union member is set")
}

// Validate reports the first constraint violation, or nil.
func (v *Message) Validate() error {
	if v.matched > 1 {
		return errors.New("Message: input satisfies more than one alternative, and oneOf permits exactly one")
	}
	if v.MessageError != nil {
		return v.MessageError.Validate()
	}
	if v.MessageInfo != nil {
		return v.MessageInfo.Validate()
	}
	if v.MessageWarning != nil {
		return v.MessageWarning.Validate()
	}
	return nil
}
