// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/message_info_create_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// MessageInfoCreateRequest is generated from common/types/message_info_create_request.json.
type MessageInfoCreateRequest struct {
	Code *InfoCodeCreateRequest `json:"code,omitzero"`
	// Human-readable message.
	Content string `json:"content"`
	// Content format, default = plain.
	ContentType *string `json:"content_type,omitzero"`
	// RFC 9535 JSONPath to the component the message refers to (e.g., $.line_items[0]).
	Path *string `json:"path,omitzero"`
	// Message type discriminator.
	Type string `json:"type"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *MessageInfoCreateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("MessageInfoCreateRequest: null is not a valid object")
	}
	type MessageInfoCreateRequestAlias MessageInfoCreateRequest
	var named MessageInfoCreateRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = MessageInfoCreateRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"content", "type"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "code")
	delete(all, "content")
	delete(all, "content_type")
	delete(all, "path")
	delete(all, "type")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v MessageInfoCreateRequest) MarshalJSON() ([]byte, error) {
	type MessageInfoCreateRequestAlias MessageInfoCreateRequest
	named, err := json.Marshal(MessageInfoCreateRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *MessageInfoCreateRequest) Validate() error {
	if v.present != nil {
		if !v.present["content"] {
			return errors.New("content: required property is missing")
		}
		if !v.present["type"] {
			return errors.New("type: required property is missing")
		}
	}
	if v.ContentType != nil && *v.ContentType != "plain" && *v.ContentType != "markdown" {
		return errors.New("content_type: not one of the permitted values")
	}
	if v.Type != "info" {
		return errors.New("type: must be \"info\"")
	}
	if v.Code != nil {
		if err := v.Code.Validate(); err != nil {
			return err
		}
	}
	return nil
}
