// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/pagination.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// Pagination Cursor-based pagination for list operations.
type Pagination map[string]any

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *Pagination) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("Pagination: null is not a valid object")
	}
	type PaginationAlias Pagination
	var alias PaginationAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = Pagination(alias)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *Pagination) Validate() error {
	return nil
}

// PaginationRequest Pagination parameters for requests.
type PaginationRequest struct {
	// Opaque cursor from previous response.
	Cursor *string `json:"cursor,omitzero"`
	// Requested page size, not a guaranteed result count. When omitted, the Business MUST apply a default page size. A default of 10 is RECOMMENDED, but the Business MAY choose another value. The Business MAY return fewer results than the requested or default page size, including when enforcing its maximum page size. A Platform MUST NOT assume that the response count equals either value.
	Limit *int64 `json:"limit,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *PaginationRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("PaginationRequest: null is not a valid object")
	}
	type PaginationRequestAlias PaginationRequest
	var named PaginationRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = PaginationRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "cursor")
	delete(all, "limit")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v PaginationRequest) MarshalJSON() ([]byte, error) {
	type PaginationRequestAlias PaginationRequest
	named, err := json.Marshal(PaginationRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *PaginationRequest) Validate() error {
	if v.Limit != nil && *v.Limit < 1 {
		return errors.New("limit: below minimum 1")
	}
	return nil
}

// PaginationResponse Pagination information in responses.
type PaginationResponse struct {
	// Cursor to fetch the next page of results. MUST be present when has_next_page is true.
	Cursor *string `json:"cursor,omitzero"`
	// Whether more results are available.
	HasNextPage bool `json:"has_next_page"`
	// Total number of matching items, if available.
	TotalCount *int64 `json:"total_count,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *PaginationResponse) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("PaginationResponse: null is not a valid object")
	}
	type PaginationResponseAlias PaginationResponse
	var named PaginationResponseAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = PaginationResponse(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"has_next_page"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "cursor")
	delete(all, "has_next_page")
	delete(all, "total_count")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v PaginationResponse) MarshalJSON() ([]byte, error) {
	type PaginationResponseAlias PaginationResponse
	named, err := json.Marshal(PaginationResponseAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *PaginationResponse) Validate() error {
	if v.present != nil {
		if !v.present["has_next_page"] {
			return errors.New("has_next_page: required property is missing")
		}
	}
	if v.TotalCount != nil && *v.TotalCount < 0 {
		return errors.New("total_count: below minimum 0")
	}
	if v.HasNextPage == true {
		if v.Cursor == nil {
			return errors.New("cursor: required property is missing when has_next_page is true")
		}
	}
	return nil
}
