// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/pan_credential.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
	"unicode/utf8"
)

// PanCredential A card credential carrying a funding primary account number (FPAN). Credential selection follows the shape of the value on the wire rather than its provenance: a network token surfaced in PAN form and verified with a `cvc` - as with credentials where a dynamic verification code proxies the cryptogram - is carried here, while a token verified with a discrete `cryptogram` uses Network Token Credential. This credential type MUST NOT be used for checkout, only with payment handlers that tokenize or encrypt credentials. CRITICAL: Both parties handling a PAN credential (sender and receiver) MUST be PCI DSS compliant. Transmission MUST use HTTPS/TLS with strong cipher suites.
type PanCredential struct {
	// Card verification code.
	Cvc *string `json:"cvc,omitzero"`
	// The month of the card's expiration date (1-12).
	ExpiryMonth *int64 `json:"expiry_month,omitzero"`
	// The year of the card's expiration date.
	ExpiryYear *int64 `json:"expiry_year,omitzero"`
	// Cardholder name.
	Name *string `json:"name,omitzero"`
	// Funding primary account number (FPAN).
	Number string `json:"number"`
	// The credential type identifier for PAN credentials.
	Type string `json:"type"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *PanCredential) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("PanCredential: null is not a valid object")
	}
	type PanCredentialAlias PanCredential
	var named PanCredentialAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = PanCredential(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"number", "type"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "cvc")
	delete(all, "expiry_month")
	delete(all, "expiry_year")
	delete(all, "name")
	delete(all, "number")
	delete(all, "type")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v PanCredential) MarshalJSON() ([]byte, error) {
	type PanCredentialAlias PanCredential
	named, err := json.Marshal(PanCredentialAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *PanCredential) Validate() error {
	if v.present != nil {
		if !v.present["number"] {
			return errors.New("number: required property is missing")
		}
		if !v.present["type"] {
			return errors.New("type: required property is missing")
		}
	}
	if v.Cvc != nil && utf8.RuneCountInString(string(*v.Cvc)) > 4 {
		return errors.New("cvc: exceeds maxLength 4")
	}
	if v.Type != "pan" {
		return errors.New("type: must be \"pan\"")
	}
	return nil
}
