// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/payment_credential_complete_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// PaymentCredentialCompleteRequest The base definition for any payment credential. Handlers define specific credential types.
type PaymentCredentialCompleteRequest struct {
	// The credential type discriminator. Specific schemas will constrain this to a constant value.
	Type string `json:"type"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *PaymentCredentialCompleteRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("PaymentCredentialCompleteRequest: null is not a valid object")
	}
	type PaymentCredentialCompleteRequestAlias PaymentCredentialCompleteRequest
	var named PaymentCredentialCompleteRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = PaymentCredentialCompleteRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"type"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "type")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v PaymentCredentialCompleteRequest) MarshalJSON() ([]byte, error) {
	type PaymentCredentialCompleteRequestAlias PaymentCredentialCompleteRequest
	named, err := json.Marshal(PaymentCredentialCompleteRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *PaymentCredentialCompleteRequest) Validate() error {
	if v.present != nil {
		if !v.present["type"] {
			return errors.New("type: required property is missing")
		}
	}
	return nil
}
