// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/payment_term.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// PaymentTerm A way of paying for the checkout: one or more payment schedules that together cover its total.
type PaymentTerm struct {
	// Supplementary context for the title (e.g. 'Save 5% by paying today'). Directly renderable; MUST NOT repeat the title.
	Description *Description `json:"description,omitzero"`
	// Unique identifier for this payment term within the checkout. Referenced by `payment.selected_term_id`.
	ID string `json:"id"`
	// Payment schedules that settle this checkout under this term, in the order they come due.
	Schedules []PaymentSchedule `json:"schedules"`
	// Short label that distinguishes this term from its siblings (e.g. 'Pay now', 'Pay in 4', 'Deposit + balance at check-in').
	Title string `json:"title"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *PaymentTerm) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("PaymentTerm: null is not a valid object")
	}
	type PaymentTermAlias PaymentTerm
	var named PaymentTermAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = PaymentTerm(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 3)
	for _, name := range []string{"id", "schedules", "title"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "description")
	delete(all, "id")
	delete(all, "schedules")
	delete(all, "title")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v PaymentTerm) MarshalJSON() ([]byte, error) {
	type PaymentTermAlias PaymentTerm
	named, err := json.Marshal(PaymentTermAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *PaymentTerm) Validate() error {
	if v.present != nil {
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
		if !v.present["schedules"] {
			return errors.New("schedules: required property is missing")
		}
		if !v.present["title"] {
			return errors.New("title: required property is missing")
		}
	}
	if len(v.Schedules) < 1 {
		return errors.New("schedules: has fewer than minItems 1")
	}
	if v.Description != nil {
		if err := v.Description.Validate(); err != nil {
			return err
		}
	}
	for i := range v.Schedules {
		if err := v.Schedules[i].Validate(); err != nil {
			return err
		}
	}
	return nil
}
