// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/request_constraints.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// RequestConstraints Binds the shared Constraint Expression grammar to data in the next UCP request to the same resource.
type RequestConstraints struct {
	// Alternative Object Constraints. The constrained object must satisfy at least one. A branch must be non-empty: an empty branch is satisfied by every object and neutralizes the alternation.
	Anyof []ConstraintExpression `json:"anyOf,omitzero"`
	// A complete RFC 9535 JSONPath query evaluated against the next logical UCP request to the same resource.
	Path *string `json:"path,omitzero"`
	// Constraints keyed by property name. Must be non-empty: an empty object applies no constraint.
	Properties map[string]json.RawMessage `json:"properties,omitzero"`
	// Property names required by the constrained object. Must be non-empty: an empty array applies no constraint.
	Required []string `json:"required,omitzero"`
}

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this a null document would decode
// to the zero value and validate as though it were a real object.
func (v *RequestConstraints) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("RequestConstraints: null is not a valid object")
	}
	type RequestConstraintsAlias RequestConstraints
	var named RequestConstraintsAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = RequestConstraints(named)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *RequestConstraints) Validate() error {
	if v.Anyof != nil && len(v.Anyof) < 1 {
		return errors.New("anyOf: has fewer than minItems 1")
	}
	if v.Properties != nil && len(v.Properties) < 1 {
		return errors.New("properties: has fewer than minProperties 1")
	}
	if v.Required != nil && len(v.Required) < 1 {
		return errors.New("required: has fewer than minItems 1")
	}
	if v.Required != nil {
		{
			k2 := make(map[string]bool, len(v.Required))
			for _, k := range v.Required {
				if k2[k] {
					return errors.New("required: contains duplicate items")
				}
				k2[k] = true
			}
		}
	}
	for i := range v.Anyof {
		if err := v.Anyof[i].Validate(); err != nil {
			return err
		}
	}
	return nil
}
