// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/signed_amount_update_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// SignedAmountUpdateRequest Monetary amount in the currency's minor unit as defined by ISO 4217. Refer to the currency's exponent to determine minor-to-major ratio (e.g., 2 for USD, 0 for JPY, 3 for KWD). May be negative — the sign is intrinsic to the value (e.g., discounts are negative, charges are positive).
type SignedAmountUpdateRequest int64

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *SignedAmountUpdateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("SignedAmountUpdateRequest: null is not a valid integer")
	}
	type SignedAmountUpdateRequestAlias SignedAmountUpdateRequest
	var alias SignedAmountUpdateRequestAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = SignedAmountUpdateRequest(alias)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *SignedAmountUpdateRequest) Validate() error {
	if int64(*v) > 9007199254740991 {
		return errors.New("SignedAmountUpdateRequest: above maximum 9007199254740991")
	}
	if int64(*v) < -9007199254740991 {
		return errors.New("SignedAmountUpdateRequest: below minimum -9007199254740991")
	}
	return nil
}
