// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/signals_create_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// SignalsCreateRequest Environment data provided by the platform to support authorization and abuse prevention. Values MUST NOT be buyer-asserted claims — platforms provide signals based on direct observation or independently verifiable third-party attestations. All signal keys MUST use reverse-domain naming to ensure provenance and prevent collisions when multiple extensions contribute to the shared namespace.
type SignalsCreateRequest struct {
	// Client's IP address (IPv4 or IPv6).
	DevUCPBuyerIP *string `json:"dev.ucp.buyer_ip,omitzero"`
	// Client's HTTP User-Agent header or equivalent.
	DevUCPUserAgent *string `json:"dev.ucp.user_agent,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *SignalsCreateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("SignalsCreateRequest: null is not a valid object")
	}
	type SignalsCreateRequestAlias SignalsCreateRequest
	var named SignalsCreateRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = SignalsCreateRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "dev.ucp.buyer_ip")
	delete(all, "dev.ucp.user_agent")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v SignalsCreateRequest) MarshalJSON() ([]byte, error) {
	type SignalsCreateRequestAlias SignalsCreateRequest
	named, err := json.Marshal(SignalsCreateRequestAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *SignalsCreateRequest) Validate() error {
	return nil
}
