// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/time_interval_create_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// TimeIntervalCreateRequest Reusable opening and closing time fields for a containing schedule schema. Containing schemas determine whether the `opens` and `closes` pair is required; this fragment's standalone `{}` is not an interval.
//
// Not enforced yet: dependentRequired.
type TimeIntervalCreateRequest map[string]any

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *TimeIntervalCreateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("TimeIntervalCreateRequest: null is not a valid object")
	}
	type TimeIntervalCreateRequestAlias TimeIntervalCreateRequest
	var alias TimeIntervalCreateRequestAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = TimeIntervalCreateRequest(alias)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *TimeIntervalCreateRequest) Validate() error {
	return nil
}
