// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/total.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// Total A cost breakdown entry with a category, amount, and optional display text.
type Total struct {
	Amount SignedAmount `json:"amount"`
	// Text to display against the amount. Should reflect appropriate method (e.g., 'Shipping', 'Delivery').
	DisplayText *string `json:"display_text,omitzero"`
	// Cost category. Well-known values: subtotal, items_discount, discount, fulfillment, tax, fee, total. Businesses MAY use additional values.
	Type string `json:"type"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *Total) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("Total: null is not a valid object")
	}
	type TotalAlias Total
	var named TotalAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = Total(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"amount", "type"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "amount")
	delete(all, "display_text")
	delete(all, "type")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v Total) MarshalJSON() ([]byte, error) {
	type TotalAlias Total
	named, err := json.Marshal(TotalAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *Total) Validate() error {
	if v.present != nil {
		if !v.present["amount"] {
			return errors.New("amount: required property is missing")
		}
		if !v.present["type"] {
			return errors.New("type: required property is missing")
		}
	}
	if v.Type == "discount" || v.Type == "items_discount" {
		if v.Amount >= 0 {
			return errors.New("amount: not below exclusiveMaximum 0")
		}
	}
	if v.Type == "subtotal" || v.Type == "fulfillment" || v.Type == "tax" || v.Type == "fee" {
		if v.Amount < 0 {
			return errors.New("amount: below minimum 0")
		}
	}
	if err := v.Amount.Validate(); err != nil {
		return err
	}
	return nil
}
