// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/totals.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// Totals Pricing breakdown provided by the business. MUST contain exactly one subtotal and one total entry. Detail types (tax, fee, discount, fulfillment) may appear multiple times for itemization. Platforms MUST render all entries in order using display_text and amount.
type Totals []TotalsTotalsItem

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *Totals) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("Totals: null is not a valid array")
	}
	type TotalsAlias Totals
	var alias TotalsAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = Totals(alias)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *Totals) Validate() error {
	if *v != nil {
		k2 := 0
		for _, k := range *v {
			if k.Type == "subtotal" {
				k2++
			}
		}
		if k2 < 1 {
			return errors.New("Totals: has fewer than minContains 1 matching items")
		}
		if k2 > 1 {
			return errors.New("Totals: has more than maxContains 1 matching items")
		}
	}
	for i := range *v {
		if err := (*v)[i].Validate(); err != nil {
			return err
		}
	}
	return nil
}

// TotalsTotalsItem is generated from common/types/totals.json.
//
// This type carries a conditional rule that depends on which
// properties the decoder saw. It is enforced for values decoded from
// JSON and skipped for values built in Go, where presence is
// unknowable.
type TotalsTotalsItem struct {
	Amount SignedAmount `json:"amount"`
	// Text to display against the amount. Should reflect appropriate method (e.g., 'Shipping', 'Delivery').
	DisplayText *string `json:"display_text,omitzero"`
	// Optional itemized breakdown. The parent entry is always rendered; lines are supplementary. Sum of line amounts MUST equal the parent entry amount.
	Lines []TotalsTotalsItemLinesItem `json:"lines,omitzero"`
	// Cost category. Well-known values: subtotal, items_discount, discount, fulfillment, tax, fee, total. Businesses MAY use additional values.
	Type string `json:"type"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *TotalsTotalsItem) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("TotalsTotalsItem: null is not a valid object")
	}
	type TotalsTotalsItemAlias TotalsTotalsItem
	var named TotalsTotalsItemAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = TotalsTotalsItem(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"amount", "type"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "amount")
	delete(all, "display_text")
	delete(all, "lines")
	delete(all, "type")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v TotalsTotalsItem) MarshalJSON() ([]byte, error) {
	type TotalsTotalsItemAlias TotalsTotalsItem
	named, err := json.Marshal(TotalsTotalsItemAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *TotalsTotalsItem) Validate() error {
	if v.present != nil {
		if !v.present["amount"] {
			return errors.New("amount: required property is missing")
		}
		if !v.present["type"] {
			return errors.New("type: required property is missing")
		}
	}
	if v.present != nil && v.present["type"] && v.Type != "subtotal" && v.Type != "items_discount" && v.Type != "discount" && v.Type != "fulfillment" && v.Type != "tax" && v.Type != "fee" && v.Type != "total" {
		if v.DisplayText == nil {
			return errors.New("display_text: required property is missing when type is not one of \"subtotal\", \"items_discount\", \"discount\", \"fulfillment\", \"tax\", \"fee\", \"total\"")
		}
	}
	if v.Type == "discount" || v.Type == "items_discount" {
		if v.Amount >= 0 {
			return errors.New("amount: not below exclusiveMaximum 0")
		}
	}
	if v.Type == "subtotal" || v.Type == "fulfillment" || v.Type == "tax" || v.Type == "fee" {
		if v.Amount < 0 {
			return errors.New("amount: below minimum 0")
		}
	}
	if err := v.Amount.Validate(); err != nil {
		return err
	}
	for i := range v.Lines {
		if err := v.Lines[i].Validate(); err != nil {
			return err
		}
	}
	return nil
}

// TotalsTotalsItemLinesItem Sub-line entry. Additional metadata MAY be included.
type TotalsTotalsItemLinesItem struct {
	Amount SignedAmount `json:"amount"`
	// Human-readable label for this sub-line.
	DisplayText string `json:"display_text"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *TotalsTotalsItemLinesItem) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("TotalsTotalsItemLinesItem: null is not a valid object")
	}
	type TotalsTotalsItemLinesItemAlias TotalsTotalsItemLinesItem
	var named TotalsTotalsItemLinesItemAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = TotalsTotalsItemLinesItem(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 2)
	for _, name := range []string{"amount", "display_text"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "amount")
	delete(all, "display_text")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v TotalsTotalsItemLinesItem) MarshalJSON() ([]byte, error) {
	type TotalsTotalsItemLinesItemAlias TotalsTotalsItemLinesItem
	named, err := json.Marshal(TotalsTotalsItemLinesItemAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *TotalsTotalsItemLinesItem) Validate() error {
	if v.present != nil {
		if !v.present["amount"] {
			return errors.New("amount: required property is missing")
		}
		if !v.present["display_text"] {
			return errors.New("display_text: required property is missing")
		}
	}
	if err := v.Amount.Validate(); err != nil {
		return err
	}
	return nil
}
