// Code generated by ucpgen. DO NOT EDIT.
// Source: common/types/warning_code_create_request.json (spec release/2026-08-25@cd78fb3)

package types

import (
	"encoding/json"
	"errors"
)

// WarningCodeCreateRequest Warning code identifying the type of warning. Standard codes are defined in capability specifications (see examples) and have standardized semantics; freeform codes are permitted.
type WarningCodeCreateRequest string

// UnmarshalJSON rejects a bare null. encoding/json treats null as a
// no-op for every Go type, so without this the zero value would pass
// every check and a null document would validate as though it were a
// real value.
func (v *WarningCodeCreateRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("WarningCodeCreateRequest: null is not a valid string")
	}
	type WarningCodeCreateRequestAlias WarningCodeCreateRequest
	var alias WarningCodeCreateRequestAlias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = WarningCodeCreateRequest(alias)
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *WarningCodeCreateRequest) Validate() error {
	return nil
}
