// Code generated by ucpgen. DO NOT EDIT.
// Source: transports/a2a_message.json (spec release/2026-08-25@cd78fb3)

package transports

import (
	"encoding/json"
	"errors"
	"unicode/utf8"
)

// A2AUCPMessageEnvelope Minimal A2A envelope shapes used by UCP's A2A checkout binding. This schema validates UCP's transport mapping points — Agent Card extension advertisement, inbound A2A Message requests, and JSON-RPC responses carrying A2A Message results — without attempting to re-specify the full A2A protocol.
//
// A2AUCPMessageEnvelope is a closed oneOf union: one field is set, holding the
// alternative the input matched. The schema requires that exactly one
// alternative match.
type A2AUCPMessageEnvelope struct {
	A2AMessageAgentCard       *A2AMessageAgentCard       `json:"-"`
	A2AMessageMessageRequest  *A2AMessageMessageRequest  `json:"-"`
	A2AMessageMessageResponse *A2AMessageMessageResponse `json:"-"`

	// matched counts the alternatives the decoded input satisfied.
	// oneOf permits exactly one, so more than one is a violation that
	// only decoding can observe. Zero means this value was never
	// decoded from JSON.
	matched int
}

// UnmarshalJSON decodes the union member that accepts the input,
// preferring one that also validates.
func (v *A2AUCPMessageEnvelope) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("A2AUCPMessageEnvelope: null is not a valid object")
	}
	var matched, fallback A2AUCPMessageEnvelope
	matches := 0
	parsed := false
	var asA2AMessageAgentCard A2AMessageAgentCard
	if err := json.Unmarshal(data, &asA2AMessageAgentCard); err == nil {
		if asA2AMessageAgentCard.Validate() == nil {
			if matches == 0 {
				matched = A2AUCPMessageEnvelope{A2AMessageAgentCard: &asA2AMessageAgentCard}
			}
			matches++
		}
		if !parsed {
			fallback, parsed = A2AUCPMessageEnvelope{A2AMessageAgentCard: &asA2AMessageAgentCard}, true
		}
	}
	var asA2AMessageMessageRequest A2AMessageMessageRequest
	if err := json.Unmarshal(data, &asA2AMessageMessageRequest); err == nil {
		if asA2AMessageMessageRequest.Validate() == nil {
			if matches == 0 {
				matched = A2AUCPMessageEnvelope{A2AMessageMessageRequest: &asA2AMessageMessageRequest}
			}
			matches++
		}
		if !parsed {
			fallback, parsed = A2AUCPMessageEnvelope{A2AMessageMessageRequest: &asA2AMessageMessageRequest}, true
		}
	}
	var asA2AMessageMessageResponse A2AMessageMessageResponse
	if err := json.Unmarshal(data, &asA2AMessageMessageResponse); err == nil {
		if asA2AMessageMessageResponse.Validate() == nil {
			if matches == 0 {
				matched = A2AUCPMessageEnvelope{A2AMessageMessageResponse: &asA2AMessageMessageResponse}
			}
			matches++
		}
		if !parsed {
			fallback, parsed = A2AUCPMessageEnvelope{A2AMessageMessageResponse: &asA2AMessageMessageResponse}, true
		}
	}
	if matches > 0 {
		*v = matched
		v.matched = matches
		return nil
	}
	if parsed {
		*v = fallback
		v.matched = 1
		return nil
	}
	return errors.New("A2AUCPMessageEnvelope: no union member accepted the input")
}

// MarshalJSON encodes whichever union member is set.
func (v A2AUCPMessageEnvelope) MarshalJSON() ([]byte, error) {
	if v.A2AMessageAgentCard != nil {
		return json.Marshal(v.A2AMessageAgentCard)
	}
	if v.A2AMessageMessageRequest != nil {
		return json.Marshal(v.A2AMessageMessageRequest)
	}
	if v.A2AMessageMessageResponse != nil {
		return json.Marshal(v.A2AMessageMessageResponse)
	}
	return nil, errors.New("A2AUCPMessageEnvelope: no union member is set")
}

// Validate reports the first constraint violation, or nil.
func (v *A2AUCPMessageEnvelope) Validate() error {
	if v.matched > 1 {
		return errors.New("A2AUCPMessageEnvelope: input satisfies more than one alternative, and oneOf permits exactly one")
	}
	if v.A2AMessageAgentCard != nil {
		return v.A2AMessageAgentCard.Validate()
	}
	if v.A2AMessageMessageRequest != nil {
		return v.A2AMessageMessageRequest.Validate()
	}
	if v.A2AMessageMessageResponse != nil {
		return v.A2AMessageMessageResponse.Validate()
	}
	return nil
}

// A2AMessageAgentCard A2A Agent Card fragment advertising UCP support through extensions.
type A2AMessageAgentCard struct {
	Extensions []A2AMessageExtension `json:"extensions"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *A2AMessageAgentCard) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("A2AMessageAgentCard: null is not a valid object")
	}
	type A2AMessageAgentCardAlias A2AMessageAgentCard
	var named A2AMessageAgentCardAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = A2AMessageAgentCard(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"extensions"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "extensions")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v A2AMessageAgentCard) MarshalJSON() ([]byte, error) {
	type A2AMessageAgentCardAlias A2AMessageAgentCard
	named, err := json.Marshal(A2AMessageAgentCardAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *A2AMessageAgentCard) Validate() error {
	if v.present != nil {
		if !v.present["extensions"] {
			return errors.New("extensions: required property is missing")
		}
	}
	if len(v.Extensions) < 1 {
		return errors.New("extensions: has fewer than minItems 1")
	}
	for i := range v.Extensions {
		if err := v.Extensions[i].Validate(); err != nil {
			return err
		}
	}
	return nil
}

// A2AMessageExtension A2A Agent Card extension advertisement for UCP.
type A2AMessageExtension struct {
	Description *string `json:"description,omitzero"`
	// Extension parameters such as advertised UCP capabilities.
	Params map[string]any `json:"params,omitzero"`
	// Extension URI. UCP uses its versioned reference URI.
	//
	// Annotation only in draft 2020-12, so not asserted: format.
	URI string `json:"uri"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *A2AMessageExtension) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("A2AMessageExtension: null is not a valid object")
	}
	type A2AMessageExtensionAlias A2AMessageExtension
	var named A2AMessageExtensionAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = A2AMessageExtension(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"uri"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "description")
	delete(all, "params")
	delete(all, "uri")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v A2AMessageExtension) MarshalJSON() ([]byte, error) {
	type A2AMessageExtensionAlias A2AMessageExtension
	named, err := json.Marshal(A2AMessageExtensionAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *A2AMessageExtension) Validate() error {
	if v.present != nil {
		if !v.present["uri"] {
			return errors.New("uri: required property is missing")
		}
	}
	return nil
}

// A2AMessageMessage A2A Message carrying natural-language or structured UCP data parts.
type A2AMessageMessage struct {
	Contextid string           `json:"contextId"`
	Kind      string           `json:"kind"`
	Messageid string           `json:"messageId"`
	Parts     []A2AMessagePart `json:"parts"`
	// Message sender role.
	Role string `json:"role"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *A2AMessageMessage) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("A2AMessageMessage: null is not a valid object")
	}
	type A2AMessageMessageAlias A2AMessageMessage
	var named A2AMessageMessageAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = A2AMessageMessage(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 5)
	for _, name := range []string{"contextId", "kind", "messageId", "parts", "role"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "contextId")
	delete(all, "kind")
	delete(all, "messageId")
	delete(all, "parts")
	delete(all, "role")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v A2AMessageMessage) MarshalJSON() ([]byte, error) {
	type A2AMessageMessageAlias A2AMessageMessage
	named, err := json.Marshal(A2AMessageMessageAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *A2AMessageMessage) Validate() error {
	if v.present != nil {
		if !v.present["contextId"] {
			return errors.New("contextId: required property is missing")
		}
		if !v.present["kind"] {
			return errors.New("kind: required property is missing")
		}
		if !v.present["messageId"] {
			return errors.New("messageId: required property is missing")
		}
		if !v.present["parts"] {
			return errors.New("parts: required property is missing")
		}
		if !v.present["role"] {
			return errors.New("role: required property is missing")
		}
	}
	if v.Kind != "message" {
		return errors.New("kind: must be \"message\"")
	}
	if len(v.Parts) < 1 {
		return errors.New("parts: has fewer than minItems 1")
	}
	if v.Role != "user" && v.Role != "agent" {
		return errors.New("role: not one of the permitted values")
	}
	for i := range v.Parts {
		if err := v.Parts[i].Validate(); err != nil {
			return err
		}
	}
	return nil
}

// A2AMessageMessageRequest A2A message/send JSON-RPC request whose params carry a UCP-bearing Message from the platform to the business agent.
type A2AMessageMessageRequest struct {
	// JSON-RPC request identifier. Notifications omit id; responses echo the request id, or use null when the request id could not be determined.
	ID json.RawMessage `json:"id,omitzero"`
	// JSON-RPC protocol version.
	Jsonrpc string `json:"jsonrpc"`
	// Transport method name. Binding-specific schemas constrain the method namespace.
	Method string `json:"method"`
	// Method parameters. Binding-specific schemas define the object shape.
	Params A2AMessageMessageRequestParams `json:"params"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and records which of the
// required ones were present.
func (v *A2AMessageMessageRequest) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("A2AMessageMessageRequest: null is not a valid object")
	}
	type A2AMessageMessageRequestAlias A2AMessageMessageRequest
	var named A2AMessageMessageRequestAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = A2AMessageMessageRequest(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 3)
	for _, name := range []string{"jsonrpc", "method", "params"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *A2AMessageMessageRequest) Validate() error {
	if v.present != nil {
		if !v.present["jsonrpc"] {
			return errors.New("jsonrpc: required property is missing")
		}
		if !v.present["method"] {
			return errors.New("method: required property is missing")
		}
		if !v.present["params"] {
			return errors.New("params: required property is missing")
		}
	}
	if v.Jsonrpc != "2.0" {
		return errors.New("jsonrpc: must be \"2.0\"")
	}
	if v.Method != "message/send" {
		return errors.New("method: must be \"message/send\"")
	}
	if utf8.RuneCountInString(string(v.Method)) < 1 {
		return errors.New("method: is shorter than minLength 1")
	}
	if err := v.Params.Validate(); err != nil {
		return err
	}
	return nil
}

// A2AMessageMessageResponse JSON-RPC success response whose result is an A2A Message from the business agent.
type A2AMessageMessageResponse struct {
	// JSON-RPC request identifier. Notifications omit id; responses echo the request id, or use null when the request id could not be determined.
	ID json.RawMessage `json:"id"`
	// JSON-RPC protocol version.
	Jsonrpc string `json:"jsonrpc"`
	// Successful transport result. UCP bindings define the nested result payload.
	Result A2AMessageMessage `json:"result"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and records which of the
// required ones were present.
func (v *A2AMessageMessageResponse) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("A2AMessageMessageResponse: null is not a valid object")
	}
	type A2AMessageMessageResponseAlias A2AMessageMessageResponse
	var named A2AMessageMessageResponseAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = A2AMessageMessageResponse(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 3)
	for _, name := range []string{"id", "jsonrpc", "result"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	return nil
}

// Validate reports the first constraint violation, or nil.
func (v *A2AMessageMessageResponse) Validate() error {
	if v.present != nil {
		if !v.present["id"] {
			return errors.New("id: required property is missing")
		}
		if !v.present["jsonrpc"] {
			return errors.New("jsonrpc: required property is missing")
		}
		if !v.present["result"] {
			return errors.New("result: required property is missing")
		}
	}
	if v.Jsonrpc != "2.0" {
		return errors.New("jsonrpc: must be \"2.0\"")
	}
	if err := v.Result.Validate(); err != nil {
		return err
	}
	return nil
}

// A2AMessagePart A2A message part. UCP examples use text parts for natural language and data parts for structured UCP payloads.
type A2AMessagePart struct {
	// Structured data payload. UCP reserves a2a.ucp.* keys for UCP payloads.
	Data map[string]any `json:"data,omitzero"`
	Kind *string        `json:"kind,omitzero"`
	Text *string        `json:"text,omitzero"`
	Type *string        `json:"type,omitzero"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *A2AMessagePart) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("A2AMessagePart: null is not a valid object")
	}
	type A2AMessagePartAlias A2AMessagePart
	var named A2AMessagePartAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = A2AMessagePart(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	delete(all, "data")
	delete(all, "kind")
	delete(all, "text")
	delete(all, "type")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v A2AMessagePart) MarshalJSON() ([]byte, error) {
	type A2AMessagePartAlias A2AMessagePart
	named, err := json.Marshal(A2AMessagePartAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *A2AMessagePart) Validate() error {
	return nil
}

// A2AMessageMessageRequestParams Method parameters. Binding-specific schemas define the object shape.
//
// The schema also declares 2 oneOf variants that narrow or replace
// these fields; they are not modeled as distinct types yet (phase 4),
// so this type reflects only the shared base.
type A2AMessageMessageRequestParams struct {
	Message A2AMessageMessage `json:"message"`

	// Extra holds properties the schema does not name. The schema is
	// open (additionalProperties is not false), so extension keys are
	// preserved here and re-emitted on marshal rather than dropped.
	Extra map[string]json.RawMessage `json:"-"`

	// present records which properties the decoder saw, so a required
	// property that was absent can be told from one decoded to its zero
	// value. A nil map means this value was never decoded from JSON.
	present map[string]bool
}

// UnmarshalJSON decodes the named properties and keeps everything else
// in Extra.
func (v *A2AMessageMessageRequestParams) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return errors.New("A2AMessageMessageRequestParams: null is not a valid object")
	}
	type A2AMessageMessageRequestParamsAlias A2AMessageMessageRequestParams
	var named A2AMessageMessageRequestParamsAlias
	if err := json.Unmarshal(data, &named); err != nil {
		return err
	}
	*v = A2AMessageMessageRequestParams(named)

	var all map[string]json.RawMessage
	if err := json.Unmarshal(data, &all); err != nil {
		return err
	}
	v.present = make(map[string]bool, 1)
	for _, name := range []string{"message"} {
		if _, ok := all[name]; ok {
			v.present[name] = true
		}
	}
	delete(all, "message")
	if len(all) > 0 {
		v.Extra = all
	}
	return nil
}

// MarshalJSON emits the named properties alongside anything held in
// Extra.
func (v A2AMessageMessageRequestParams) MarshalJSON() ([]byte, error) {
	type A2AMessageMessageRequestParamsAlias A2AMessageMessageRequestParams
	named, err := json.Marshal(A2AMessageMessageRequestParamsAlias(v))
	if err != nil {
		return nil, err
	}
	if len(v.Extra) == 0 {
		return named, nil
	}
	var merged map[string]json.RawMessage
	if err := json.Unmarshal(named, &merged); err != nil {
		return nil, err
	}
	if merged == nil {
		merged = map[string]json.RawMessage{}
	}
	for k, val := range v.Extra {
		if _, named := merged[k]; !named {
			merged[k] = val
		}
	}
	return json.Marshal(merged)
}

// Validate reports the first constraint violation, or nil.
func (v *A2AMessageMessageRequestParams) Validate() error {
	if v.present != nil {
		if !v.present["message"] {
			return errors.New("message: required property is missing")
		}
	}
	if err := v.Message.Validate(); err != nil {
		return err
	}
	return nil
}
